import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;
import 'dart:typed_data';

import 'package:image/image.dart' as img;
import 'package:path/path.dart' as p;

const int selbrumePortReferenceAssetDivergenceExitCode = 2;
const int _tileSize = 32;
const int _spriteAtlasWidthCells = 48;
const int _waterPatternSizeCells = 8;
const int _waterFrameCount = 8;
const JsonEncoder _prettyJson = JsonEncoder.withIndent('  ');

const String selbrumePortReferenceSpriteAtlasPath =
    'assets/tilesets/port_reference_v3/selbrume_port_reference_v3.png';
const String selbrumePortReferenceGroundAtlasPath =
    'assets/tilesets/port_reference_v3/selbrume_port_ground_v3.png';
const String selbrumePortReferenceWaterAtlasPath =
    'assets/tilesets/port_reference_v3/selbrume_port_water_v3.png';
const String selbrumePortReferenceManifestPath =
    'assets/provenance/selbrume_port_reference_v3.json';

final class SelbrumePortReferenceAssetOptions {
  SelbrumePortReferenceAssetOptions({
    required Directory projectRoot,
    this.write = false,
  }) : projectRoot = Directory(p.normalize(p.absolute(projectRoot.path)));

  final Directory projectRoot;
  final bool write;
}

final class SelbrumePortReferenceAssetResult {
  const SelbrumePortReferenceAssetResult({
    required this.exitCode,
    required this.divergentRelativePaths,
    required this.entryCount,
  });

  final int exitCode;
  final List<String> divergentRelativePaths;
  final int entryCount;
}

SelbrumePortReferenceAssetOptions parseSelbrumePortReferenceAssetOptions(
  List<String> arguments,
) {
  Directory? projectRoot;
  var write = false;
  for (var index = 0; index < arguments.length; index += 1) {
    switch (arguments[index]) {
      case '--project-root':
        if (++index >= arguments.length || arguments[index].trim().isEmpty) {
          throw const FormatException('--project-root requires a path.');
        }
        projectRoot = Directory(arguments[index]);
        break;
      case '--write':
        write = true;
        break;
      case '--check':
        write = false;
        break;
      default:
        throw FormatException('Unknown argument: ${arguments[index]}');
    }
  }
  if (projectRoot == null) {
    throw const FormatException('--project-root is required.');
  }
  return SelbrumePortReferenceAssetOptions(
    projectRoot: projectRoot,
    write: write,
  );
}

/// Builds only the normalized Port v3 asset family.
///
/// The supplied map image is evidence and visual direction, never an atlas
/// underlay. `write=false` is a deterministic drift check; it must not mutate
/// the project so CI and reviewers can prove the generated bytes are current.
Future<SelbrumePortReferenceAssetResult> buildSelbrumePortReferenceAssets(
  SelbrumePortReferenceAssetOptions options,
) async {
  final root = await _validatedProjectRoot(options.projectRoot);
  final sources = await _loadSources(root);
  final grassSource = await _loadGrassSource(root);
  final spriteBuild = _buildSpriteAtlas(sources);
  final groundAtlas = _buildGroundAtlas(grassSource.image);
  final waterAtlas = _buildWaterAtlas();
  final spriteBytes = Uint8List.fromList(img.encodePng(spriteBuild.atlas));
  final groundBytes = Uint8List.fromList(img.encodePng(groundAtlas));
  final waterBytes = Uint8List.fromList(img.encodePng(waterAtlas));

  final desiredBytes = <String, Uint8List>{
    selbrumePortReferenceSpriteAtlasPath: spriteBytes,
    selbrumePortReferenceGroundAtlasPath: groundBytes,
    selbrumePortReferenceWaterAtlasPath: waterBytes,
  };
  final hashes = <String, String>{};
  for (final entry in desiredBytes.entries) {
    hashes[entry.key] = await _sha256Bytes(entry.value);
  }
  final tileModuleJson = <Object?>[];
  for (final module in spriteBuild.tileModules) {
    final moduleHash = await _sha256Bytes(
      Uint8List.fromList(img.encodePng(module.image)),
    );
    tileModuleJson.add(
      module.toJson(
        atlasWidthCells: _spriteAtlasWidthCells,
        sha256: moduleHash,
      ),
    );
  }
  final manifest = <String, Object?>{
    'schemaVersion': 1,
    'mapId': 'map_port_brisants',
    'status': 'candidate_pending_owner_approval',
    'licenseDecision': 'user_supplied_reference_and_user_requested_derivation',
    'referenceOnlySource': <String, Object?>{
      'file': 'ChatGPT Image Jun 6, 2026, 07_10_04 PM.png',
      'sha256':
          '25fdc9419850028a6e79787ac53dd8e34dcf457ed2d90c1126b5e9b60ecfb219',
      'runtimeUnderlay': false,
    },
    'generation': <String, Object?>{
      'tool': 'built-in image_gen',
      'backgroundRemoval':
          'remove_chroma_key.py auto-key border, soft matte, edge contract 1',
      'normalization':
          'cell crop, alpha trim, binary alpha, nearest-neighbor resize, bottom-center anchor',
      'prompts': const <String>[
        'six isolated Selbrume harbor architecture sprites',
        'three modular docks and three working fishing boats',
        'six isolated Selbrume landscaping sprites',
        'natural continuous rocky Selbrume coastline sections',
        'transparent shoreline foam overlays',
        'compact isolated working-port prop clusters',
        'one empty sea-bird nest prop',
        'one lamp, one bench, one sign and three small coastal rock variants',
      ],
    },
    'groundTextureSource': <String, Object?>{
      'path': grassSource.relativePath,
      'sha256': grassSource.sha256,
      'tool': 'owner_supplied_exact_asset',
      'referenceRole': 'runtime_texture_source',
    },
    'nativePavementPath': const <String, Object?>{
      'presetId': 'pavement_path',
      'tilesetId': 'pavement_path',
      'tool': 'existing_project_path_preset',
      'referenceRole': 'runtime_path_source',
    },
    'sourceSheets': <Object?>[
      for (final source in sources.values)
        <String, Object?>{
          'key': source.key,
          'chromaPath': source.chromaRelativePath,
          'chromaSha256': source.chromaSha256,
          'alphaPath': source.alphaRelativePath,
          'alphaSha256': source.alphaSha256,
          'width': source.image.width,
          'height': source.image.height,
        },
    ],
    'atlases': <String, Object?>{
      'sprites': <String, Object?>{
        'relativePath': selbrumePortReferenceSpriteAtlasPath,
        'sha256': hashes[selbrumePortReferenceSpriteAtlasPath],
        'widthCells': spriteBuild.atlas.width ~/ _tileSize,
        'heightCells': spriteBuild.atlas.height ~/ _tileSize,
      },
      'ground': <String, Object?>{
        'relativePath': selbrumePortReferenceGroundAtlasPath,
        'sha256': hashes[selbrumePortReferenceGroundAtlasPath],
        'widthCells': groundAtlas.width ~/ _tileSize,
        'heightCells': groundAtlas.height ~/ _tileSize,
      },
      'water': <String, Object?>{
        'relativePath': selbrumePortReferenceWaterAtlasPath,
        'sha256': hashes[selbrumePortReferenceWaterAtlasPath],
        'patternSizeCells': _waterPatternSizeCells,
        'frameCount': _waterFrameCount,
        'frameDurationMs': 180,
        'widthCells': waterAtlas.width ~/ _tileSize,
        'heightCells': waterAtlas.height ~/ _tileSize,
      },
    },
    'entries': <Object?>[
      for (final entry in spriteBuild.entries) entry.toJson(),
    ],
    'tileModuleGeneration': const <String, Object?>{
      'method': 'deterministic_existing_source_derivation',
      'generativeArt': false,
      'packing': 'append_only_after_published_entries',
      'tileOrder': 'row_major',
    },
    'tileModules': tileModuleJson,
  };
  final manifestBytes = Uint8List.fromList(
    utf8.encode('${_prettyJson.convert(manifest)}\n'),
  );
  desiredBytes[selbrumePortReferenceManifestPath] = manifestBytes;

  final divergent = <String>[];
  for (final entry in desiredBytes.entries) {
    final file = File(p.join(root.path, entry.key));
    if (!await file.exists() ||
        !_sameBytes(await file.readAsBytes(), entry.value)) {
      divergent.add(entry.key);
    }
  }
  if (options.write) {
    for (final relative in <String>[
      selbrumePortReferenceSpriteAtlasPath,
      selbrumePortReferenceGroundAtlasPath,
      selbrumePortReferenceWaterAtlasPath,
      selbrumePortReferenceManifestPath,
    ]) {
      final file = File(p.join(root.path, relative));
      await file.parent.create(recursive: true);
      await file.writeAsBytes(desiredBytes[relative]!, flush: true);
    }
  }
  return SelbrumePortReferenceAssetResult(
    exitCode: options.write || divergent.isEmpty
        ? 0
        : selbrumePortReferenceAssetDivergenceExitCode,
    divergentRelativePaths:
        options.write ? const <String>[] : List<String>.unmodifiable(divergent),
    entryCount: spriteBuild.entries.length,
  );
}

Future<Map<String, _SourceSheet>> _loadSources(Directory root) async {
  const specs = <(String, String)>[
    ('architecture', 'architecture_sheet'),
    ('docks_boats', 'docks_boats_sheet'),
    ('nature', 'nature_sheet'),
    ('coast', 'coast_sheet'),
    ('natural_coast', 'natural_coast'),
    ('shore_foam', 'shore_foam'),
    ('small_harbor_props', 'small_harbor_props'),
    ('nest', 'nest'),
    ('small_props', 'small_props'),
  ];
  final result = <String, _SourceSheet>{};
  for (final spec in specs) {
    final base = 'assets/sources/port_reference_v3/${spec.$2}';
    final chromaRelativePath = '${base}_chroma.png';
    final alphaRelativePath = '${base}_alpha.png';
    final chroma = File(p.join(root.path, chromaRelativePath));
    final alpha = File(p.join(root.path, alphaRelativePath));
    if (!await chroma.exists() || !await alpha.exists()) {
      throw StateError('Missing generated Port source pair: $base.');
    }
    final decoded = img.decodePng(await alpha.readAsBytes());
    if (decoded == null || decoded.numChannels != 4) {
      throw StateError('Invalid RGBA Port source: $alphaRelativePath.');
    }
    result[spec.$1] = _SourceSheet(
      key: spec.$1,
      chromaRelativePath: chromaRelativePath,
      alphaRelativePath: alphaRelativePath,
      chromaSha256: await _sha256File(chroma),
      alphaSha256: await _sha256File(alpha),
      image: decoded,
    );
  }
  return result;
}

Future<_OpaqueSource> _loadGrassSource(Directory root) async {
  const relativePath =
      'assets/sources/port_reference_v3/grass_texture_owner.png';
  final file = File(p.join(root.path, relativePath));
  if (!await file.exists()) {
    throw StateError('Missing generated Port grass texture: $relativePath.');
  }
  final decoded = img.decodePng(await file.readAsBytes());
  if (decoded == null || decoded.width < 64 || decoded.height < 64) {
    throw StateError('Invalid Port grass texture: $relativePath.');
  }
  return _OpaqueSource(
    relativePath: relativePath,
    sha256: await _sha256File(file),
    image: decoded,
  );
}

_SpriteBuild _buildSpriteAtlas(Map<String, _SourceSheet> sources) {
  final prepared = <(_SpriteSpec, img.Image)>[];
  final preparedById = <String, img.Image>{};
  for (final spec in _spriteSpecs) {
    final source = sources[spec.sheetKey];
    if (source == null) throw StateError('Unknown sheet ${spec.sheetKey}.');
    final cell =
        spec.sheetKey == 'nest' ? source.image : _sheetCell(source.image, spec);
    final trimmed = _trimAlpha(cell);
    final normalized = _normalizeSprite(trimmed, spec);
    prepared.add((spec, normalized));
    preparedById[spec.id] = normalized;
  }

  var x = 0;
  var y = 0;
  var rowHeight = 0;
  final placements = <(_SpriteSpec, img.Image, int, int)>[];
  for (final item in prepared) {
    final widthCells = item.$1.widthCells;
    final heightCells = item.$1.heightCells;
    if (x > 0 && x + widthCells > _spriteAtlasWidthCells) {
      x = 0;
      y += rowHeight;
      rowHeight = 0;
    }
    placements.add((item.$1, item.$2, x, y));
    x += widthCells;
    rowHeight = math.max(rowHeight, heightCells);
  }
  final publishedHeightCells = y + rowHeight;
  final preparedModules = <(_TileModuleSpec, img.Image)>[
    for (final spec in _tileModuleSpecs)
      (spec, _buildTileModuleImage(spec, sources, preparedById)),
  ];
  x = 0;
  y = publishedHeightCells;
  rowHeight = 0;
  final modulePlacements = <(_TileModuleSpec, img.Image, int, int)>[];
  for (final item in preparedModules) {
    if (x > 0 && x + item.$1.widthCells > _spriteAtlasWidthCells) {
      x = 0;
      y += rowHeight;
      rowHeight = 0;
    }
    modulePlacements.add((item.$1, item.$2, x, y));
    x += item.$1.widthCells;
    rowHeight = math.max(rowHeight, item.$1.heightCells);
  }
  final heightCells = y + rowHeight;
  final atlas = img.Image(
    width: _spriteAtlasWidthCells * _tileSize,
    height: heightCells * _tileSize,
    numChannels: 4,
  );
  final entries = <_BuiltSpriteEntry>[];
  for (final placement in placements) {
    img.compositeImage(
      atlas,
      placement.$2,
      dstX: placement.$3 * _tileSize,
      dstY: placement.$4 * _tileSize,
    );
    entries.add(
      _BuiltSpriteEntry(
        spec: placement.$1,
        x: placement.$3,
        y: placement.$4,
      ),
    );
  }
  final tileModules = <_BuiltTileModule>[];
  for (final placement in modulePlacements) {
    img.compositeImage(
      atlas,
      placement.$2,
      dstX: placement.$3 * _tileSize,
      dstY: placement.$4 * _tileSize,
    );
    tileModules.add(
      _BuiltTileModule(
        spec: placement.$1,
        image: placement.$2,
        x: placement.$3,
        y: placement.$4,
      ),
    );
  }
  return _SpriteBuild(
    atlas: atlas,
    entries: entries,
    tileModules: tileModules,
  );
}

img.Image _sheetCell(img.Image source, _SpriteSpec spec) {
  var x0 = spec.column * source.width ~/ 3;
  var x1 = (spec.column + 1) * source.width ~/ 3;
  var y0 = spec.row * source.height ~/ 2;
  var y1 = (spec.row + 1) * source.height ~/ 2;
  // The image generator keeps a clear 3x2 reading order, but wide boats and
  // the dense forest cluster intentionally cross the mathematical third-line.
  // These hash-locked sheet-specific gutters capture each whole sprite without
  // importing any neighbor or treating the full reference map as an underlay.
  if (spec.sheetKey == 'docks_boats') {
    const left = <int>[0, 620, 1100];
    const right = <int>[620, 1120, 1536];
    x0 = left[spec.column];
    x1 = right[spec.column];
  } else if (spec.sheetKey == 'nature') {
    const left = <int>[0, 630, 990];
    const right = <int>[630, 990, 1448];
    x0 = left[spec.column];
    x1 = right[spec.column];
  } else if (spec.sheetKey == 'natural_coast') {
    if (spec.column == 0) {
      x0 = 0;
      x1 = 650;
      y0 = 0;
      y1 = source.height;
    } else {
      x0 = 650;
      x1 = source.width;
      y0 = source.height * 3 ~/ 8;
      y1 = source.height;
    }
  }
  return img.copyCrop(
    source,
    x: x0,
    y: y0,
    width: x1 - x0,
    height: y1 - y0,
  );
}

img.Image _trimAlpha(img.Image source) {
  var left = source.width;
  var top = source.height;
  var right = -1;
  var bottom = -1;
  for (var y = 0; y < source.height; y += 1) {
    for (var x = 0; x < source.width; x += 1) {
      if (source.getPixel(x, y).a.toInt() < 64) continue;
      left = math.min(left, x);
      right = math.max(right, x);
      top = math.min(top, y);
      bottom = math.max(bottom, y);
    }
  }
  if (right < left || bottom < top) {
    throw StateError('Generated source cell is fully transparent.');
  }
  return img.copyCrop(
    source,
    x: math.max(0, left - 1),
    y: math.max(0, top - 1),
    width: math.min(source.width - math.max(0, left - 1), right - left + 3),
    height: math.min(source.height - math.max(0, top - 1), bottom - top + 3),
  );
}

img.Image _normalizeSprite(img.Image source, _SpriteSpec spec) {
  final clean = source.convert(numChannels: 4);
  for (var y = 0; y < clean.height; y += 1) {
    for (var x = 0; x < clean.width; x += 1) {
      final pixel = clean.getPixel(x, y);
      if (pixel.a.toInt() < 220) {
        clean.setPixelRgba(x, y, 0, 0, 0, 0);
      } else {
        clean.setPixelRgba(
          x,
          y,
          pixel.r.toInt(),
          pixel.g.toInt(),
          pixel.b.toInt(),
          255,
        );
      }
    }
  }
  final targetWidth = spec.widthCells * _tileSize;
  final targetHeight = spec.heightCells * _tileSize;
  final scale = math.min(
        (targetWidth - 4) / clean.width,
        (targetHeight - 2) / clean.height,
      ) *
      _visualScaleFor(spec);
  final resized = img.copyResize(
    clean,
    width: math.max(1, (clean.width * scale).floor()),
    height: math.max(1, (clean.height * scale).floor()),
    interpolation: img.Interpolation.nearest,
  );
  final canvas = img.Image(
    width: targetWidth,
    height: targetHeight,
    numChannels: 4,
  );
  img.compositeImage(
    canvas,
    resized,
    dstX: (targetWidth - resized.width) ~/ 2,
    dstY: targetHeight - resized.height,
  );
  return canvas;
}

double _visualScaleFor(_SpriteSpec spec) {
  if (spec.id == 'el_port_ref_quay_steps') return 0.78;
  return switch (spec.category) {
    'building' => 0.92,
    'boat' => 0.82,
    'nature' => 0.75,
    'garden' => 0.88,
    'prop' => 0.78,
    'interaction' => 0.80,
    'coast' => 0.90,
    'coastline' => 1.0,
    'dock' => 1.0,
    'foam' => 1.0,
    _ => 0.85,
  };
}

img.Image _buildTileModuleImage(
  _TileModuleSpec spec,
  Map<String, _SourceSheet> sources,
  Map<String, img.Image> preparedById,
) {
  img.Image existing(String id) {
    final image = preparedById[id];
    if (image == null) throw StateError('Unknown published sprite $id.');
    return image;
  }

  img.Image normalized(
    String sheetKey,
    int column,
    int row,
    int widthCells,
    int heightCells,
    String category,
  ) {
    final source = sources[sheetKey];
    if (source == null) throw StateError('Unknown sheet $sheetKey.');
    final adapter = _SpriteSpec(
      id: spec.id,
      name: spec.id,
      sheetKey: sheetKey,
      column: column,
      row: row,
      widthCells: widthCells,
      heightCells: heightCells,
      category: category,
      recommendedLayerId: 'tile_only',
      collisionIntent: 'none',
    );
    return _normalizeSprite(
      _trimAlpha(_sheetCell(source.image, adapter)),
      adapter,
    );
  }

  final image = switch (spec.id) {
    'module_port_ref_wall_h_short' => _cropCells(
        existing('el_port_ref_walled_garden'),
        x: 2,
        y: 3,
        width: 3,
        height: 2,
      ),
    'module_port_ref_wall_h_long' => _cropCells(
        existing('el_port_ref_walled_garden'),
        x: 0,
        y: 3,
        width: 6,
        height: 2,
      ),
    'module_port_ref_wall_end_left' => _cropCells(
        existing('el_port_ref_walled_garden'),
        x: 0,
        y: 3,
        width: 2,
        height: 2,
      ),
    'module_port_ref_wall_end_right' => _cropCells(
        existing('el_port_ref_walled_garden'),
        x: 5,
        y: 3,
        width: 2,
        height: 2,
      ),
    'module_port_ref_garden_gate_open' => _buildOpenGate(
        _cropCells(
          existing('el_port_ref_walled_garden'),
          x: 1,
          y: 1,
          width: 6,
          height: 2,
        ),
      ),
    'module_port_ref_flower_bed_compact' =>
      normalized('nature', 0, 1, 5, 3, 'garden'),
    'module_port_ref_quay_steps_compact' =>
      normalized('coast', 1, 1, 5, 5, 'dock'),
    'module_port_ref_quay_pier_join' => _cropCells(
        existing('el_port_ref_pier_t'),
        x: 2,
        y: 0,
        width: 5,
        height: 3,
      ),
    'module_port_ref_pier_endcap' => _cropCells(
        existing('el_port_ref_pier_vertical'),
        x: 0,
        y: 7,
        width: 5,
        height: 2,
      ),
    'module_port_ref_coast_east_complete' =>
      normalized('natural_coast', 1, 0, 9, 6, 'coastline'),
    'module_port_ref_coast_quay_join' =>
      normalized('coast', 2, 0, 3, 3, 'coastline'),
    'module_port_ref_coast_quay_join_mirrored' => _mirrorHorizontal(
        normalized('coast', 2, 0, 3, 3, 'coastline'),
      ),
    'module_port_ref_foam_h_short' =>
      normalized('shore_foam', 1, 0, 4, 1, 'foam'),
    'module_port_ref_foam_corner' =>
      normalized('shore_foam', 2, 0, 3, 3, 'foam'),
    'module_port_ref_foam_wake_short' =>
      normalized('shore_foam', 2, 1, 4, 2, 'foam'),
    _ => throw StateError('Unknown tile module recipe: ${spec.id}.'),
  };
  if (image.width != spec.widthCells * _tileSize ||
      image.height != spec.heightCells * _tileSize) {
    throw StateError(
      'Tile module ${spec.id} produced ${image.width}x${image.height}; '
      'expected ${spec.widthCells * _tileSize}x'
      '${spec.heightCells * _tileSize}.',
    );
  }
  return image;
}

img.Image _cropCells(
  img.Image source, {
  required int x,
  required int y,
  required int width,
  required int height,
}) {
  return img.copyCrop(
    source,
    x: x * _tileSize,
    y: y * _tileSize,
    width: width * _tileSize,
    height: height * _tileSize,
  );
}

img.Image _buildOpenGate(img.Image fence) {
  final canvas = img.Image(
    width: 3 * _tileSize,
    height: 2 * _tileSize,
    numChannels: 4,
  );
  img.compositeImage(
    canvas,
    _cropCells(fence, x: 0, y: 0, width: 1, height: 2),
  );
  img.compositeImage(
    canvas,
    _cropCells(fence, x: 5, y: 0, width: 1, height: 2),
    dstX: 2 * _tileSize,
  );
  return canvas;
}

img.Image _mirrorHorizontal(img.Image source) {
  final mirrored = img.Image(
    width: source.width,
    height: source.height,
    numChannels: 4,
  );
  for (var y = 0; y < source.height; y += 1) {
    for (var x = 0; x < source.width; x += 1) {
      final pixel = source.getPixel(x, y);
      mirrored.setPixelRgba(
        source.width - x - 1,
        y,
        pixel.r,
        pixel.g,
        pixel.b,
        pixel.a,
      );
    }
  }
  return mirrored;
}

/// Packs owner-approved grass plus the two non-road fallback tiles.
///
/// Pavement is intentionally absent: the map renders the project's native
/// `pavement_path` preset so a creator can still edit every road cell.
img.Image _buildGroundAtlas(img.Image grassSource) {
  const grassPatternTiles = 8;
  const grassTileCount = grassPatternTiles * grassPatternTiles;
  const stoneTileX = grassTileCount;
  const waterTileX = stoneTileX + 1;
  const tileCount = waterTileX + 1;
  final atlas = img.Image(
    width: tileCount * _tileSize,
    height: _tileSize,
    numChannels: 4,
  );
  final grassPattern = _cropGroundPattern(
    grassSource,
    seed: 17,
    sizeInTiles: grassPatternTiles,
  );
  _sealGroundTileEdges(grassPattern);
  _paintGroundPatternTiles(
    atlas,
    pattern: grassPattern,
    startTileX: 0,
    sizeInTiles: grassPatternTiles,
  );
  _paintStoneTile(atlas, tileX: stoneTileX);
  _paintStaticWaterTile(atlas, tileX: waterTileX);
  return atlas;
}

img.Image _cropGroundPattern(
  img.Image source, {
  required int seed,
  required int sizeInTiles,
}) {
  final patternSize = _tileSize * sizeInTiles;
  if (source.width < patternSize || source.height < patternSize) {
    throw StateError(
      'Ground source ${source.width}x${source.height} is smaller than '
      '${patternSize}x$patternSize.',
    );
  }
  final maxX = math.max(0, source.width - patternSize);
  final maxY = math.max(0, source.height - patternSize);
  final x = maxX == 0 ? 0 : _hash2(seed, 13) % (maxX + 1);
  final y = maxY == 0 ? 0 : _hash2(seed, 31) % (maxY + 1);
  return img
      .copyCrop(
        source,
        x: x,
        y: y,
        width: math.min(patternSize, source.width),
        height: math.min(patternSize, source.height),
      )
      .convert(numChannels: 4);
}

void _paintGroundPatternTiles(
  img.Image atlas, {
  required img.Image pattern,
  required int startTileX,
  required int sizeInTiles,
}) {
  if (pattern.width != _tileSize * sizeInTiles ||
      pattern.height != _tileSize * sizeInTiles) {
    throw StateError('Ground pattern has invalid tile dimensions.');
  }
  for (var localY = 0; localY < sizeInTiles; localY += 1) {
    for (var localX = 0; localX < sizeInTiles; localX += 1) {
      final tile = img.copyCrop(
        pattern,
        x: localX * _tileSize,
        y: localY * _tileSize,
        width: _tileSize,
        height: _tileSize,
      );
      final tileIndex = localY * sizeInTiles + localX;
      img.compositeImage(
        atlas,
        tile,
        dstX: (startTileX + tileIndex) * _tileSize,
      );
    }
  }
}

void _sealGroundTileEdges(img.Image tile) {
  for (var y = 0; y < tile.height; y += 1) {
    final left = tile.getPixel(1, y);
    final right = tile.getPixel(tile.width - 2, y);
    final red = (left.r.toInt() + right.r.toInt()) ~/ 2;
    final green = (left.g.toInt() + right.g.toInt()) ~/ 2;
    final blue = (left.b.toInt() + right.b.toInt()) ~/ 2;
    tile.setPixelRgba(0, y, red, green, blue, 255);
    tile.setPixelRgba(tile.width - 1, y, red, green, blue, 255);
  }
  for (var x = 0; x < tile.width; x += 1) {
    final top = tile.getPixel(x, 1);
    final bottom = tile.getPixel(x, tile.height - 2);
    final red = (top.r.toInt() + bottom.r.toInt()) ~/ 2;
    final green = (top.g.toInt() + bottom.g.toInt()) ~/ 2;
    final blue = (top.b.toInt() + bottom.b.toInt()) ~/ 2;
    tile.setPixelRgba(x, 0, red, green, blue, 255);
    tile.setPixelRgba(x, tile.height - 1, red, green, blue, 255);
  }
}

void _paintStoneTile(img.Image atlas, {required int tileX}) {
  for (var y = 0; y < _tileSize; y += 1) {
    for (var x = 0; x < _tileSize; x += 1) {
      final rowOffset = (y ~/ 8).isOdd ? 4 : 0;
      final mortar = y % 8 == 0 || (x + rowOffset) % 12 == 0;
      final noise = _hash2(x + 9, y + 17) % 10 - 5;
      final value = mortar ? 116 : 157 + noise;
      atlas.setPixelRgba(
          tileX * _tileSize + x, y, value, value, value - 8, 255);
    }
  }
}

void _paintStaticWaterTile(img.Image atlas, {required int tileX}) {
  for (var y = 0; y < _tileSize; y += 1) {
    for (var x = 0; x < _tileSize; x += 1) {
      final detail = _hash2(x ~/ 2, y ~/ 2) % 13;
      atlas.setPixelRgba(
        tileX * _tileSize + x,
        y,
        14 + detail ~/ 4,
        83 + detail,
        151 + detail * 2,
        255,
      );
    }
  }
}

/// Builds a spatially seamless eight-frame sea loop without scrolling its base.
///
/// Only local curved wavelets pulse and drift (by at most one pixel). This
/// protects the calm blue palette approved by the owner while avoiding the
/// previous blinking horizontal-dash animation.
img.Image _buildWaterAtlas() {
  const frameSize = _waterPatternSizeCells * _tileSize;
  final atlas = img.Image(
    width: _waterFrameCount * frameSize,
    height: frameSize,
    numChannels: 4,
  );
  for (var frame = 0; frame < _waterFrameCount; frame += 1) {
    for (var y = 0; y < frameSize; y += 1) {
      for (var x = 0; x < frameSize; x += 1) {
        final block = _hash2(x ~/ 2, y ~/ 2) % 19;
        var red = 16 + block ~/ 6;
        var green = 87 + block;
        var blue = 165 + block * 2;
        final wave = _waterWaveAt(x, y, frame, frameSize);
        if (wave == 4) {
          red = 190;
          green = 226;
          blue = 245;
        } else if (wave == 3) {
          red = 112;
          green = 181;
          blue = 222;
        } else if (wave == 2) {
          red = 65;
          green = 147;
          blue = 207;
        } else if (wave == 1) {
          red = 12;
          green = 76;
          blue = 149;
        }
        atlas.setPixelRgba(frame * frameSize + x, y, red, green, blue, 255);
      }
    }
    final originX = frame * frameSize;
    for (var y = 0; y < frameSize; y += 1) {
      final source = atlas.getPixel(originX, y);
      atlas.setPixelRgba(
        originX + frameSize - 1,
        y,
        source.r,
        source.g,
        source.b,
        source.a,
      );
    }
    for (var x = 0; x < frameSize; x += 1) {
      final source = atlas.getPixel(originX + x, 0);
      atlas.setPixelRgba(
        originX + x,
        frameSize - 1,
        source.r,
        source.g,
        source.b,
        source.a,
      );
    }
  }
  return atlas;
}

/// Resolves layered wave color strength: 0 base, 1 shadow, 2–4 crest levels.
int _waterWaveAt(int x, int y, int frame, int period) {
  const pulse = <int>[1, 1, 2, 3, 3, 2, 1, 1];
  const driftX = <int>[0, 0, 0, 1, 1, 1, 0, 0];
  var result = 0;
  for (var index = 0; index < 72; index += 1) {
    final centerX = _hash2(index * 7 + 3, 19) % period;
    final centerY = _hash2(index * 11 + 5, 31) % period;
    final phase = (frame + index * 3) % _waterFrameCount;
    final halfLength = 4 + _hash2(index, 47) % 8;
    final dx = _signedCircularDelta(
      x,
      _wrap(centerX + driftX[phase], period),
      period,
    );
    if (dx.abs() > halfLength) continue;
    if (_hash2(index * 17 + dx + halfLength, 113) % 7 == 0) continue;

    final bend = (dx * dx * (2 + _hash2(index, 89) % 2)) ~/
        (halfLength * halfLength + 1);
    final direction = _hash2(index, 97).isEven ? 1 : -1;
    final arcY = _wrap(centerY + direction * bend, period);
    final dy = _signedCircularDelta(y, arcY, period);
    if (dy == 0) {
      final strength = pulse[phase];
      final crest = strength == 1
          ? 2
          : strength == 2
              ? 3
              : index % 5 == 0
                  ? 4
                  : 3;
      result = math.max(result, crest);
    } else if (dy == 1 && index % 3 != 0) {
      result = math.max(result, 1);
    }
  }
  return result;
}

int _signedCircularDelta(int value, int target, int period) {
  final normalized = ((value - target) % period + period) % period;
  return normalized > period ~/ 2 ? normalized - period : normalized;
}

int _wrap(int value, int period) => ((value % period) + period) % period;

int _hash2(int x, int y) {
  var value = (x * 0x1f123bb5) ^ (y * 0x5f356495) ^ 0x6d2b79f5;
  value = (value ^ (value >> 16)) * 0x45d9f3b;
  value = (value ^ (value >> 16)) * 0x45d9f3b;
  return (value ^ (value >> 16)) & 0x7fffffff;
}

Future<Directory> _validatedProjectRoot(Directory requested) async {
  if (!await requested.exists()) {
    throw StateError('Project root does not exist: ${requested.path}');
  }
  final resolved = Directory(await requested.resolveSymbolicLinks());
  if (!await File(p.join(resolved.path, 'project.json')).exists()) {
    throw StateError('Missing project.json in ${resolved.path}.');
  }
  return resolved;
}

Future<String> _sha256File(File file) async {
  final result = await Process.run('shasum', <String>['-a', '256', file.path]);
  if (result.exitCode != 0) throw StateError('shasum failed for ${file.path}.');
  return result.stdout.toString().trim().split(RegExp(r'\s+')).first;
}

Future<String> _sha256Bytes(Uint8List bytes) async {
  final directory = await Directory.systemTemp.createTemp('port_ref_hash_');
  try {
    final file = File(p.join(directory.path, 'payload'));
    await file.writeAsBytes(bytes, flush: true);
    return await _sha256File(file);
  } finally {
    await directory.delete(recursive: true);
  }
}

bool _sameBytes(List<int> left, List<int> right) {
  if (left.length != right.length) return false;
  for (var index = 0; index < left.length; index += 1) {
    if (left[index] != right[index]) return false;
  }
  return true;
}

final class _SourceSheet {
  const _SourceSheet({
    required this.key,
    required this.chromaRelativePath,
    required this.alphaRelativePath,
    required this.chromaSha256,
    required this.alphaSha256,
    required this.image,
  });

  final String key;
  final String chromaRelativePath;
  final String alphaRelativePath;
  final String chromaSha256;
  final String alphaSha256;
  final img.Image image;
}

final class _OpaqueSource {
  const _OpaqueSource({
    required this.relativePath,
    required this.sha256,
    required this.image,
  });

  final String relativePath;
  final String sha256;
  final img.Image image;
}

final class _SpriteBuild {
  const _SpriteBuild({
    required this.atlas,
    required this.entries,
    required this.tileModules,
  });

  final img.Image atlas;
  final List<_BuiltSpriteEntry> entries;
  final List<_BuiltTileModule> tileModules;
}

final class _BuiltTileModule {
  const _BuiltTileModule({
    required this.spec,
    required this.image,
    required this.x,
    required this.y,
  });

  final _TileModuleSpec spec;
  final img.Image image;
  final int x;
  final int y;

  Map<String, Object?> toJson({
    required int atlasWidthCells,
    required String sha256,
  }) {
    final tileIds = <int>[
      for (var localY = 0; localY < spec.heightCells; localY += 1)
        for (var localX = 0; localX < spec.widthCells; localX += 1)
          (y + localY) * atlasWidthCells + x + localX + 1,
    ];
    return <String, Object?>{
      'id': spec.id,
      'source': <String, int>{
        'x': x,
        'y': y,
        'width': spec.widthCells,
        'height': spec.heightCells,
      },
      'tileIds': tileIds,
      'sha256': sha256,
      'futurePlacement': spec.futurePlacement,
      'derivation': <String, Object?>{
        'kind': spec.derivationKind,
        'sourceSheets': spec.sourceSheets,
        'sourceEntries': spec.sourceEntries,
        'recipe': spec.recipe,
        'generativeArt': false,
      },
    };
  }
}

final class _TileModuleSpec {
  const _TileModuleSpec({
    required this.id,
    required this.widthCells,
    required this.heightCells,
    required this.futurePlacement,
    required this.derivationKind,
    required this.sourceSheets,
    required this.sourceEntries,
    required this.recipe,
  });

  final String id;
  final int widthCells;
  final int heightCells;
  final String futurePlacement;
  final String derivationKind;
  final List<String> sourceSheets;
  final List<String> sourceEntries;
  final String recipe;
}

final class _BuiltSpriteEntry {
  const _BuiltSpriteEntry({
    required this.spec,
    required this.x,
    required this.y,
  });

  final _SpriteSpec spec;
  final int x;
  final int y;

  Map<String, Object?> toJson() => <String, Object?>{
        'id': spec.id,
        'name': spec.name,
        'category': spec.category,
        'recommendedLayerId': spec.recommendedLayerId,
        'sourceSheet': spec.sheetKey,
        'sourceCell': <String, int>{
          'column': spec.column,
          'row': spec.row,
        },
        'source': <String, int>{
          'x': x,
          'y': y,
          'width': spec.widthCells,
          'height': spec.heightCells,
        },
        'anchor': 'bottom_center',
        'collisionIntent': spec.collisionIntent,
      };
}

final class _SpriteSpec {
  const _SpriteSpec({
    required this.id,
    required this.name,
    required this.sheetKey,
    required this.column,
    required this.row,
    required this.widthCells,
    required this.heightCells,
    required this.category,
    required this.recommendedLayerId,
    required this.collisionIntent,
  });

  final String id;
  final String name;
  final String sheetKey;
  final int column;
  final int row;
  final int widthCells;
  final int heightCells;
  final String category;
  final String recommendedLayerId;
  final String collisionIntent;
}

const List<_TileModuleSpec> _tileModuleSpecs = <_TileModuleSpec>[
  _TileModuleSpec(
    id: 'module_port_ref_wall_h_short',
    widthCells: 3,
    heightCells: 2,
    futurePlacement: 'short west and east garden limits',
    derivationKind: 'published_entry_crop',
    sourceSheets: <String>[],
    sourceEntries: <String>['el_port_ref_walled_garden'],
    recipe: 'crop cells 2,3 3x2 from the published low garden border',
  ),
  _TileModuleSpec(
    id: 'module_port_ref_wall_h_long',
    widthCells: 6,
    heightCells: 2,
    futurePlacement: 'harbor master terrace retaining wall',
    derivationKind: 'published_entry_crop',
    sourceSheets: <String>[],
    sourceEntries: <String>['el_port_ref_walled_garden'],
    recipe: 'crop cells 0,3 6x2 from the published low garden border',
  ),
  _TileModuleSpec(
    id: 'module_port_ref_wall_end_left',
    widthCells: 2,
    heightCells: 2,
    futurePlacement: 'left side of visual door openings',
    derivationKind: 'published_entry_crop',
    sourceSheets: <String>[],
    sourceEntries: <String>['el_port_ref_walled_garden'],
    recipe: 'crop cells 0,3 2x2 from the published low garden border',
  ),
  _TileModuleSpec(
    id: 'module_port_ref_wall_end_right',
    widthCells: 2,
    heightCells: 2,
    futurePlacement: 'right side of visual door openings',
    derivationKind: 'published_entry_crop',
    sourceSheets: <String>[],
    sourceEntries: <String>['el_port_ref_walled_garden'],
    recipe: 'crop cells 5,3 2x2 from the published low garden border',
  ),
  _TileModuleSpec(
    id: 'module_port_ref_garden_gate_open',
    widthCells: 3,
    heightCells: 2,
    futurePlacement: 'explicit visual opening in front of house doors',
    derivationKind: 'deterministic_composition',
    sourceSheets: <String>[],
    sourceEntries: <String>['el_port_ref_walled_garden'],
    recipe: 'outer cells of published garden fence with transparent center',
  ),
  _TileModuleSpec(
    id: 'module_port_ref_flower_bed_compact',
    widthCells: 5,
    heightCells: 3,
    futurePlacement: 'compact central planted island',
    derivationKind: 'normalized_source_cell',
    sourceSheets: <String>['nature'],
    sourceEntries: <String>[],
    recipe: 'nature cell 0,1 normalized to 5x3',
  ),
  _TileModuleSpec(
    id: 'module_port_ref_quay_steps_compact',
    widthCells: 5,
    heightCells: 5,
    futurePlacement: 'compact central quay access',
    derivationKind: 'normalized_source_cell',
    sourceSheets: <String>['coast'],
    sourceEntries: <String>[],
    recipe: 'coast steps cell 1,1 normalized to 5x5',
  ),
  _TileModuleSpec(
    id: 'module_port_ref_quay_pier_join',
    widthCells: 5,
    heightCells: 3,
    futurePlacement: 'continuous center quay to pier junction',
    derivationKind: 'published_sprite_crop',
    sourceSheets: <String>['docks_boats'],
    sourceEntries: <String>['el_port_ref_pier_t'],
    recipe: 'crop cells 2,0 5x3 from normalized T pier',
  ),
  _TileModuleSpec(
    id: 'module_port_ref_pier_endcap',
    widthCells: 5,
    heightCells: 2,
    futurePlacement: 'distinct west and east pier ends',
    derivationKind: 'published_sprite_crop',
    sourceSheets: <String>['docks_boats'],
    sourceEntries: <String>['el_port_ref_pier_vertical'],
    recipe: 'crop cells 0,7 5x2 from normalized vertical pier',
  ),
  _TileModuleSpec(
    id: 'module_port_ref_coast_east_complete',
    widthCells: 9,
    heightCells: 6,
    futurePlacement: 'complete south-east in-bounds coastline',
    derivationKind: 'normalized_source_cell',
    sourceSheets: <String>['natural_coast'],
    sourceEntries: <String>[],
    recipe: 'natural coast east cell normalized to 9x6',
  ),
  _TileModuleSpec(
    id: 'module_port_ref_coast_quay_join',
    widthCells: 3,
    heightCells: 3,
    futurePlacement: 'east quay to rocky coast transition',
    derivationKind: 'normalized_source_cell',
    sourceSheets: <String>['coast'],
    sourceEntries: <String>[],
    recipe: 'coast corner cell 2,0 normalized to 3x3',
  ),
  _TileModuleSpec(
    id: 'module_port_ref_coast_quay_join_mirrored',
    widthCells: 3,
    heightCells: 3,
    futurePlacement: 'west quay to rocky coast transition',
    derivationKind: 'deterministic_mirror',
    sourceSheets: <String>['coast'],
    sourceEntries: <String>[],
    recipe: 'horizontal mirror of normalized coast corner cell 2,0',
  ),
  _TileModuleSpec(
    id: 'module_port_ref_foam_h_short',
    widthCells: 4,
    heightCells: 1,
    futurePlacement: 'short local foam below quay piles',
    derivationKind: 'normalized_source_cell',
    sourceSheets: <String>['shore_foam'],
    sourceEntries: <String>[],
    recipe: 'shore foam cell 1,0 normalized to 4x1',
  ),
  _TileModuleSpec(
    id: 'module_port_ref_foam_corner',
    widthCells: 3,
    heightCells: 3,
    futurePlacement: 'local foam at coast corners',
    derivationKind: 'normalized_source_cell',
    sourceSheets: <String>['shore_foam'],
    sourceEntries: <String>[],
    recipe: 'shore foam corner cell 2,0 normalized to 3x3',
  ),
  _TileModuleSpec(
    id: 'module_port_ref_foam_wake_short',
    widthCells: 4,
    heightCells: 2,
    futurePlacement: 'restrained local wake below boat hulls',
    derivationKind: 'normalized_source_cell',
    sourceSheets: <String>['shore_foam'],
    sourceEntries: <String>[],
    recipe: 'shore foam wake cell 2,1 normalized to 4x2',
  ),
];

const List<_SpriteSpec> _spriteSpecs = <_SpriteSpec>[
  _SpriteSpec(
      id: 'el_port_ref_harbor_master',
      name: 'Capitainerie de Port des Brisants',
      sheetKey: 'architecture',
      column: 0,
      row: 0,
      widthCells: 8,
      heightCells: 6,
      category: 'building',
      recommendedLayerId: 'l_tile_port_ref_structures',
      collisionIntent: 'solid_building_base'),
  _SpriteSpec(
      id: 'el_port_ref_house_orange',
      name: 'Maison de pecheur orange',
      sheetKey: 'architecture',
      column: 1,
      row: 0,
      widthCells: 7,
      heightCells: 5,
      category: 'building',
      recommendedLayerId: 'l_tile_port_ref_structures',
      collisionIntent: 'solid_building_base'),
  _SpriteSpec(
      id: 'el_port_ref_house_blue',
      name: 'Maison de pecheur bleue',
      sheetKey: 'architecture',
      column: 2,
      row: 0,
      widthCells: 7,
      heightCells: 5,
      category: 'building',
      recommendedLayerId: 'l_tile_port_ref_structures',
      collisionIntent: 'solid_building_base'),
  _SpriteSpec(
      id: 'el_port_ref_fish_market',
      name: 'Marche aux poissons',
      sheetKey: 'architecture',
      column: 0,
      row: 1,
      widthCells: 8,
      heightCells: 6,
      category: 'building',
      recommendedLayerId: 'l_tile_port_ref_structures',
      collisionIntent: 'solid_shop_base'),
  _SpriteSpec(
      id: 'el_port_ref_chandlery',
      name: 'Accastillage et filets',
      sheetKey: 'architecture',
      column: 1,
      row: 1,
      widthCells: 8,
      heightCells: 6,
      category: 'building',
      recommendedLayerId: 'l_tile_port_ref_structures',
      collisionIntent: 'solid_shop_base'),
  _SpriteSpec(
      id: 'el_port_ref_quay_horizontal',
      name: 'Quai horizontal',
      sheetKey: 'docks_boats',
      column: 0,
      row: 0,
      widthCells: 12,
      heightCells: 4,
      category: 'dock',
      recommendedLayerId: 'l_tile_port_ref_structures',
      collisionIntent: 'walkable_deck'),
  _SpriteSpec(
      id: 'el_port_ref_pier_t',
      name: 'Ponton en T',
      sheetKey: 'docks_boats',
      column: 1,
      row: 0,
      widthCells: 9,
      heightCells: 9,
      category: 'dock',
      recommendedLayerId: 'l_tile_port_ref_structures',
      collisionIntent: 'walkable_deck'),
  _SpriteSpec(
      id: 'el_port_ref_pier_vertical',
      name: 'Ponton vertical',
      sheetKey: 'docks_boats',
      column: 2,
      row: 0,
      widthCells: 5,
      heightCells: 9,
      category: 'dock',
      recommendedLayerId: 'l_tile_port_ref_structures',
      collisionIntent: 'walkable_deck'),
  _SpriteSpec(
      id: 'el_port_ref_boat_large',
      name: 'Grand bateau de peche',
      sheetKey: 'docks_boats',
      column: 0,
      row: 1,
      widthCells: 10,
      heightCells: 5,
      category: 'boat',
      recommendedLayerId: 'l_tile_port_ref_structures',
      collisionIntent: 'solid_boat'),
  _SpriteSpec(
      id: 'el_port_ref_boat_medium',
      name: 'Bateau de peche moyen',
      sheetKey: 'docks_boats',
      column: 1,
      row: 1,
      widthCells: 8,
      heightCells: 4,
      category: 'boat',
      recommendedLayerId: 'l_tile_port_ref_structures',
      collisionIntent: 'solid_boat'),
  _SpriteSpec(
      id: 'el_port_ref_boat_small',
      name: 'Canot de peche',
      sheetKey: 'docks_boats',
      column: 2,
      row: 1,
      widthCells: 6,
      heightCells: 4,
      category: 'boat',
      recommendedLayerId: 'l_tile_port_ref_structures',
      collisionIntent: 'solid_boat'),
  _SpriteSpec(
      id: 'el_port_ref_forest_cluster',
      name: 'Lisiere forestiere dense',
      sheetKey: 'nature',
      column: 0,
      row: 0,
      widthCells: 11,
      heightCells: 7,
      category: 'nature',
      recommendedLayerId: 'l_tile_port_ref_overhead',
      collisionIntent: 'solid_tree_trunks'),
  _SpriteSpec(
      id: 'el_port_ref_tree',
      name: 'Grand arbre de Selbrume',
      sheetKey: 'nature',
      column: 1,
      row: 0,
      widthCells: 5,
      heightCells: 6,
      category: 'nature',
      recommendedLayerId: 'l_tile_port_ref_overhead',
      collisionIntent: 'solid_tree_trunk'),
  _SpriteSpec(
      id: 'el_port_ref_walled_garden',
      name: 'Jardin clos fleuri',
      sheetKey: 'nature',
      column: 2,
      row: 0,
      widthCells: 7,
      heightCells: 5,
      category: 'garden',
      recommendedLayerId: 'l_tile_port_ref_structures',
      collisionIntent: 'solid_garden_border'),
  _SpriteSpec(
      id: 'el_port_ref_flower_bed',
      name: 'Massif fleuri',
      sheetKey: 'nature',
      column: 0,
      row: 1,
      widthCells: 8,
      heightCells: 4,
      category: 'garden',
      recommendedLayerId: 'l_tile_port_ref_ground',
      collisionIntent: 'decorative'),
  _SpriteSpec(
      id: 'el_port_ref_rock_cluster',
      name: 'Rochers cotiers',
      sheetKey: 'nature',
      column: 2,
      row: 1,
      widthCells: 6,
      heightCells: 4,
      category: 'coast',
      recommendedLayerId: 'l_tile_port_ref_structures',
      collisionIntent: 'solid_rocks'),
  _SpriteSpec(
      id: 'el_port_ref_coast_west_continuous',
      name: 'Cote rocheuse naturelle ouest',
      sheetKey: 'natural_coast',
      column: 0,
      row: 0,
      widthCells: 8,
      heightCells: 19,
      category: 'coastline',
      recommendedLayerId: 'l_tile_port_ref_structures',
      collisionIntent: 'decorative'),
  _SpriteSpec(
      id: 'el_port_ref_coast_east_peninsula',
      name: 'Cote rocheuse naturelle est',
      sheetKey: 'natural_coast',
      column: 1,
      row: 0,
      widthCells: 9,
      heightCells: 5,
      category: 'coastline',
      recommendedLayerId: 'l_tile_port_ref_structures',
      collisionIntent: 'decorative'),
  _SpriteSpec(
      id: 'el_port_ref_quay_steps',
      name: 'Escalier du quai',
      sheetKey: 'coast',
      column: 1,
      row: 1,
      widthCells: 7,
      heightCells: 7,
      category: 'dock',
      recommendedLayerId: 'l_tile_port_ref_structures',
      collisionIntent: 'walkable_steps'),
  _SpriteSpec(
      id: 'el_port_ref_foam_quay_horizontal',
      name: 'Ecume horizontale de quai',
      sheetKey: 'shore_foam',
      column: 1,
      row: 0,
      widthCells: 12,
      heightCells: 2,
      category: 'foam',
      recommendedLayerId: 'l_tile_port_ref_structures',
      collisionIntent: 'decorative'),
  _SpriteSpec(
      id: 'el_port_ref_foam_rock_cluster',
      name: 'Ecume de groupe de rochers',
      sheetKey: 'shore_foam',
      column: 1,
      row: 1,
      widthCells: 6,
      heightCells: 4,
      category: 'foam',
      recommendedLayerId: 'l_tile_port_ref_structures',
      collisionIntent: 'decorative'),
  _SpriteSpec(
      id: 'el_port_ref_foam_boat_wake',
      name: 'Sillage discret de bateau',
      sheetKey: 'shore_foam',
      column: 2,
      row: 1,
      widthCells: 4,
      heightCells: 2,
      category: 'foam',
      recommendedLayerId: 'l_tile_port_ref_structures',
      collisionIntent: 'decorative'),
  _SpriteSpec(
      id: 'el_port_ref_fish_crates_small',
      name: 'Petites caisses de poisson',
      sheetKey: 'small_harbor_props',
      column: 0,
      row: 0,
      widthCells: 2,
      heightCells: 2,
      category: 'prop',
      recommendedLayerId: 'l_tile_port_ref_structures',
      collisionIntent: 'solid_prop_base'),
  _SpriteSpec(
      id: 'el_port_ref_rope_coil_small',
      name: 'Petit cordage et bouee',
      sheetKey: 'small_harbor_props',
      column: 1,
      row: 0,
      widthCells: 2,
      heightCells: 2,
      category: 'prop',
      recommendedLayerId: 'l_tile_port_ref_structures',
      collisionIntent: 'solid_prop_base'),
  _SpriteSpec(
      id: 'el_port_ref_net_rack_small',
      name: 'Etendoir a filet etroit',
      sheetKey: 'small_harbor_props',
      column: 2,
      row: 0,
      widthCells: 2,
      heightCells: 3,
      category: 'prop',
      recommendedLayerId: 'l_tile_port_ref_structures',
      collisionIntent: 'solid_prop_base'),
  _SpriteSpec(
      id: 'el_port_ref_fish_basket_small',
      name: 'Petit panier de poisson',
      sheetKey: 'small_harbor_props',
      column: 0,
      row: 1,
      widthCells: 2,
      heightCells: 2,
      category: 'prop',
      recommendedLayerId: 'l_tile_port_ref_structures',
      collisionIntent: 'solid_prop_base'),
  _SpriteSpec(
      id: 'el_port_ref_lobster_pots_small',
      name: 'Petits casiers et bouee',
      sheetKey: 'small_harbor_props',
      column: 1,
      row: 1,
      widthCells: 2,
      heightCells: 2,
      category: 'prop',
      recommendedLayerId: 'l_tile_port_ref_structures',
      collisionIntent: 'solid_prop_base'),
  _SpriteSpec(
      id: 'el_port_ref_barrel_buoy_small',
      name: 'Petit tonneau et bouee',
      sheetKey: 'small_harbor_props',
      column: 2,
      row: 1,
      widthCells: 2,
      heightCells: 2,
      category: 'prop',
      recommendedLayerId: 'l_tile_port_ref_structures',
      collisionIntent: 'solid_prop_base'),
  _SpriteSpec(
      id: 'el_port_ref_nest',
      name: 'Nid de Goelise',
      sheetKey: 'nest',
      column: 0,
      row: 0,
      widthCells: 2,
      heightCells: 2,
      category: 'interaction',
      recommendedLayerId: 'l_tile_port_ref_ground',
      collisionIntent: 'decorative_interaction'),
  _SpriteSpec(
      id: 'el_port_ref_lamp',
      name: 'Lampadaire du port',
      sheetKey: 'small_props',
      column: 0,
      row: 0,
      widthCells: 1,
      heightCells: 3,
      category: 'prop',
      recommendedLayerId: 'l_tile_port_ref_structures',
      collisionIntent: 'solid_prop_base'),
  _SpriteSpec(
      id: 'el_port_ref_bench',
      name: 'Banc du port',
      sheetKey: 'small_props',
      column: 1,
      row: 0,
      widthCells: 3,
      heightCells: 2,
      category: 'prop',
      recommendedLayerId: 'l_tile_port_ref_structures',
      collisionIntent: 'solid_prop_base'),
  _SpriteSpec(
      id: 'el_port_ref_sign_small',
      name: 'Petit panneau du port',
      sheetKey: 'small_props',
      column: 2,
      row: 0,
      widthCells: 2,
      heightCells: 2,
      category: 'prop',
      recommendedLayerId: 'l_tile_port_ref_structures',
      collisionIntent: 'solid_prop_base'),
  _SpriteSpec(
      id: 'el_port_ref_rock_small',
      name: 'Petit rocher cotier',
      sheetKey: 'small_props',
      column: 0,
      row: 1,
      widthCells: 1,
      heightCells: 1,
      category: 'coast',
      recommendedLayerId: 'l_tile_port_ref_structures',
      collisionIntent: 'solid_rocks'),
  _SpriteSpec(
      id: 'el_port_ref_rock_pair',
      name: 'Paire de rochers cotiers',
      sheetKey: 'small_props',
      column: 1,
      row: 1,
      widthCells: 2,
      heightCells: 2,
      category: 'coast',
      recommendedLayerId: 'l_tile_port_ref_structures',
      collisionIntent: 'solid_rocks'),
  _SpriteSpec(
      id: 'el_port_ref_rock_trio',
      name: 'Groupe de rochers cotiers',
      sheetKey: 'small_props',
      column: 2,
      row: 1,
      widthCells: 3,
      heightCells: 2,
      category: 'coast',
      recommendedLayerId: 'l_tile_port_ref_structures',
      collisionIntent: 'solid_rocks'),
];

Future<void> main(List<String> arguments) async {
  try {
    final options = parseSelbrumePortReferenceAssetOptions(arguments);
    final result = await buildSelbrumePortReferenceAssets(options);
    if (result.divergentRelativePaths.isEmpty) {
      stdout.writeln('Port reference assets are up to date.');
    } else {
      stderr.writeln('Port reference asset divergence:');
      for (final path in result.divergentRelativePaths) {
        stderr.writeln('  $path');
      }
    }
    exitCode = result.exitCode;
  } catch (error, stackTrace) {
    stderr.writeln('Port reference asset build failed: $error');
    stderr.writeln(stackTrace);
    exitCode = 1;
  }
}
