import '../errors/application_errors.dart';
import '../models/pokemon_project_data_models.dart';

/// Normalise des payloads de catalogues externes vers [PokemonCatalogFile].
///
/// Cette classe couvre seulement le besoin de la phase 7A :
/// - convertir des fixtures externes représentatives ;
/// - produire des catalogues internes cohérents ;
/// - rester totalement pure et locale.
///
/// Non-objectifs explicites :
/// - pas de réseau ;
/// - pas d'écriture workspace ;
/// - pas de stratégie multi-source générique ;
/// - pas de validation croisée avec les autres données Pokédex.
class ExternalPokemonCatalogNormalizer {
  const ExternalPokemonCatalogNormalizer();

  /// Convertit un payload de type "dex object" proche de Pokémon Showdown.
  ///
  /// Le contrat minimal assumé ici :
  /// - la racine est déjà un objet JSON ;
  /// - chaque entrée du payload est une map JSON ;
  /// - la clé de l'entrée sert d'identifiant par défaut si l'entrée n'en porte
  ///   pas un explicitement.
  PokemonCatalogFile normalizeShowdownCatalog({
    required String catalogKey,
    required Map<String, dynamic> payload,
  }) {
    final normalizedCatalogKey = catalogKey.trim();
    if (normalizedCatalogKey.isEmpty) {
      throw const EditorValidationException(
        'External catalog key cannot be empty',
      );
    }
    if (payload.isEmpty) {
      throw const EditorValidationException(
        'Showdown catalog payload cannot be empty',
      );
    }

    final entries = <Map<String, dynamic>>[];
    for (final rawEntry in payload.entries) {
      final normalizedId = _normalizeExternalId(rawEntry.key);
      if (normalizedId.isEmpty) {
        throw const EditorValidationException(
          'Showdown catalog entries must have a usable id',
        );
      }

      final rawValue = rawEntry.value;
      if (rawValue is! Map) {
        throw EditorPersistenceException(
          'Showdown catalog entry "$normalizedId" must be an object',
        );
      }

      final entry = _sanitizeJsonMap(
        rawValue.cast<Object?, Object?>(),
        context: 'Showdown catalog entry "$normalizedId"',
      );

      final existingId = (entry['id'] as String?)?.trim();
      entry['id'] = existingId == null || existingId.isEmpty
          ? _canonicalizeCatalogEntryId(normalizedCatalogKey, normalizedId)
          : _canonicalizeCatalogEntryId(normalizedCatalogKey, existingId);

      final existingName = (entry['name'] as String?)?.trim();
      if (existingName == null || existingName.isEmpty) {
        // On complète un nom minimal lisible quand la source n'en fournit pas.
        // Cela évite de fabriquer un catalogue interne rempli d'entrées
        // techniquement valides mais inutilisables en curation humaine.
        entry['name'] = _humanizeIdentifier(entry['id'] as String);
      }

      entries.add(entry);
    }

    entries.sort(
      (left, right) => ((left['id'] as String?) ?? '').compareTo(
        (right['id'] as String?) ?? '',
      ),
    );

    return PokemonCatalogFile(
      schemaVersion: 1,
      kind: 'pokemon_catalog',
      catalog: normalizedCatalogKey,
      meta: PokemonDataMeta(
        description:
            'Normalized $normalizedCatalogKey catalog from Pokémon Showdown.',
        sourcePriority: const <String>['showdown', 'internal_normalized'],
        notes: const <String>[
          'Generated by the Phase 7A external catalog normalizer.',
        ],
      ),
      entries: entries,
    );
  }

  /// Convertit une réponse PokeAPI de type "named resource list".
  ///
  /// Cette forme est utile pour les référentiels qui n'ont pas besoin d'être
  /// sur-typés à ce stade : growth rates, habitats, egg groups, version groups,
  /// etc. On conserve donc un contrat volontairement petit :
  /// - `results` doit être une liste ;
  /// - chaque entrée doit fournir au moins un `name` exploitable ;
  /// - `url` est conservé comme méta-référence si disponible.
  PokemonCatalogFile normalizePokeApiNamedResourceCatalog({
    required String catalogKey,
    required Map<String, dynamic> payload,
  }) {
    final normalizedCatalogKey = catalogKey.trim();
    if (normalizedCatalogKey.isEmpty) {
      throw const EditorValidationException(
        'External catalog key cannot be empty',
      );
    }

    final rawResults = payload['results'];
    if (rawResults is! List) {
      throw const EditorPersistenceException(
        'PokeAPI catalog payload must contain a results list',
      );
    }
    if (rawResults.isEmpty) {
      throw const EditorValidationException(
        'PokeAPI catalog results cannot be empty',
      );
    }

    final entries = <Map<String, dynamic>>[];
    for (var index = 0; index < rawResults.length; index++) {
      final rawEntry = rawResults[index];
      if (rawEntry is! Map) {
        throw EditorPersistenceException(
          'PokeAPI catalog result at index $index must be an object',
        );
      }

      final entry = rawEntry.cast<Object?, Object?>();
      final name = (entry['name'] as String?)?.trim() ?? '';
      if (name.isEmpty) {
        throw EditorValidationException(
          'PokeAPI catalog result at index $index must define a name',
        );
      }

      final url = (entry['url'] as String?)?.trim();
      final normalizedId =
          _canonicalizeCatalogEntryId(normalizedCatalogKey, name);
      entries.add(
        <String, dynamic>{
          'id': normalizedId,
          'name': _humanizeIdentifier(name),
          if (url != null && url.isNotEmpty) 'sourceUrl': url,
        },
      );
    }

    entries.sort(
      (left, right) => ((left['id'] as String?) ?? '').compareTo(
        (right['id'] as String?) ?? '',
      ),
    );

    return PokemonCatalogFile(
      schemaVersion: 1,
      kind: 'pokemon_catalog',
      catalog: normalizedCatalogKey,
      meta: PokemonDataMeta(
        description:
            'Normalized $normalizedCatalogKey catalog from PokeAPI resources.',
        sourcePriority: const <String>['pokeapi', 'internal_normalized'],
        notes: const <String>[
          'Generated by the Phase 7A external catalog normalizer.',
        ],
      ),
      entries: entries,
    );
  }

  Map<String, dynamic> _sanitizeJsonMap(
    Map<Object?, Object?> raw, {
    required String context,
  }) {
    final sanitized = <String, dynamic>{};
    for (final entry in raw.entries) {
      final key = entry.key;
      if (key is! String) {
        throw EditorPersistenceException('$context contains a non-string key');
      }
      sanitized[key] = _sanitizeJsonValue(
        entry.value,
        context: '$context.$key',
      );
    }
    return sanitized;
  }

  Object? _sanitizeJsonValue(
    Object? value, {
    required String context,
  }) {
    if (value == null || value is String || value is num || value is bool) {
      return value;
    }
    if (value is List) {
      return value
          .map(
            (entry) => _sanitizeJsonValue(
              entry,
              context: '$context[]',
            ),
          )
          .toList(growable: false);
    }
    if (value is Map) {
      return _sanitizeJsonMap(
        value.cast<Object?, Object?>(),
        context: context,
      );
    }

    throw EditorPersistenceException(
      '$context contains a non-JSON value of type ${value.runtimeType}',
    );
  }

  String _normalizeExternalId(String raw) {
    final trimmed = raw.trim().toLowerCase();
    if (trimmed.isEmpty) return '';
    return trimmed.replaceAll(RegExp(r'[^a-z0-9_-]+'), '_');
  }

  String _canonicalizeCatalogEntryId(String catalogKey, String raw) {
    final trimmedCatalogKey = catalogKey.trim().toLowerCase();
    if (_snakeCaseCatalogKeys.contains(trimmedCatalogKey)) {
      return _normalizeSnakeCaseId(raw);
    }
    return _normalizeExternalId(raw);
  }

  String _normalizeSnakeCaseId(String raw) {
    final trimmed = raw.trim().toLowerCase();
    if (trimmed.isEmpty) return '';
    final separated = trimmed.replaceAll(RegExp(r'[\s-]+'), '_');
    return separated.replaceAll(RegExp(r'[^a-z0-9_]+'), '');
  }

  String _humanizeIdentifier(String identifier) {
    final spaced = identifier.replaceAll(RegExp(r'[_-]+'), ' ').trim();
    if (spaced.isEmpty) return identifier;
    return spaced
        .split(RegExp(r'\s+'))
        .map(
          (part) => part.isEmpty
              ? part
              : '${part[0].toUpperCase()}${part.substring(1)}',
        )
        .join(' ');
  }

  static const Set<String> _snakeCaseCatalogKeys = <String>{
    'types',
    'abilities',
    'moves',
    'growth_rates',
    'egg_groups',
  };
}
