enum BattleMoveVisualRecipeId {
  genericContactLight,
  genericContactHeavy,
  genericPunch,
  genericBite,
  genericSlash,
  genericProjectileNeutral,
  genericProjectilePulse,
  genericProjectileFire,
  genericProjectileWater,
  genericProjectileElectric,
  genericProjectileGhost,
  genericProjectileDark,
  genericProjectileFairy,
  genericProjectileIce,
  genericBuffSelf,
  genericDebuffTarget,
  genericStatusPulse,
  protectBarrier,
  setStealthRock,
  setSpikes,
  weatherRain,
  weatherSandstorm,
  pseudoWeatherTrickRoom,
  chargeUp,
  rechargePause,
  sdkExactAcidArmor,
  sdkExactAcrobatics,
  sdkExactAerialAce,
  sdkExactAirSlash,
  sdkExactAquaRing,
  sdkExactAquaTail,
  sdkExactAssurance,
  sdkExactAstonish,
  sdkExactAvalanche,
  sdkExactKarateChop,
  sdkExactLeechSeed,
  sdkExactPoisonPowder,
  sdkExactRecover,
  sdkExactSleepPowder,
  sdkExactStunSpore,
  sdkExactTailWhip,
  sdkExactThunderWave,
  sdkExactVineWhip,
  sdkTackle,
  sdkScratch,
  sdkQuickAttack,
  sdkSlash,
  sdkAerialAce,
  sdkCloseCombat,
  sdkThunderbolt,
  sdkChargeBeam,
  sdkHiddenPower,
  sdkDoomDesire,
  sdkSeedFlare,
  sdkIcyWind,
  sdkWeatherBall,
  sdkScald,
  sdkTriAttack,
  sdkClangingScales,
  sdkFlameBurst,
  sdkSteamEruption,
  sdkWaterSport,
  sdkShadowBall,
  sdkDarkPulse,
  sdkAuraSphere,
  sdkBubbleBeam,
  sdkFireBlast,
  sdkBlizzard,
  sdkDazzlingGleam,
  sdkCalmMind,
  sdkSwordsDance,
  sdkAgility,
  sdkBulkUp,
  sdkCharm,
  sdkConfuseRay,
  sdkGrowl,
  sdkTaunt,
  sdkInstruct,
  sdkQuash,
  sdkSwagger,
  sdkEncore,
  sdkBabyDollEyes,
  sdkThunderWave,
  sdkProtect,
  sdkBurningBulwark,
  sdkBanefulBunker,
  sdkReflect,
  sdkLightScreen,
  sdkMist,
  sdkAuroraVeil,
  sdkSafeguard,
  sdkQuickGuard,
  sdkWideGuard,
  sdkTailwind,
  sdkRainDance,
  sdkSandstorm,
  sdkTrickRoom,
  sdkStealthRock,
  sdkSpikes,
  sdkAquaJet,
  sdkExtremeSpeed,
  sdkMachPunch,
  sdkShadowPunch,
  sdkFocusPunch,
  sdkDrainPunch,
  sdkDynamicPunch,
  sdkCometPunch,
  sdkMegaPunch,
  sdkPowerUpPunch,
  sdkDizzyPunch,
  sdkJetPunch,
  sdkFirePunch,
  sdkIcePunch,
  sdkThunderPunch,
  sdkBlazeKick,
  sdkThunderousKick,
  sdkTropKick,
  sdkDoubleKick,
  sdkDualWingBeat,
  sdkBoneMerang,
  sdkBodySlam,
  sdkHighJumpKick,
  sdkKarateChop,
  sdkDrillRun,
  sdkGunkShot,
  sdkMudShot,
  sdkElectroBall,
  sdkElectricShock,
  sdkRockBlast,
  sdkSpark,
  sdkWildCharge,
  sdkFlareBlitz,
  sdkAccelerock,
  sdkWickedBlow,
  sdkDoubleHit,
  sdkCrunch,
  sdkFlamethrower,
  sdkIceBeam,
  sdkPsychic,
  sdkMoonBlast,
  sdkPoisonJab,
  sdkEarthquake,
  sdkEnergyBall,
  sdkRockSlide,
  sdkNightSlash,
  sdkGigaImpact,
  sdkPowerWhip,
  sdkWoodHammer,
  sdkIvyCudgel,
  sdkIvyCudgelWater,
  sdkIvyCudgelFire,
  sdkIvyCudgelRock,
  sdkCut,
  sdkShadowClaw,
  sdkMultiAttack,
  sdkBite,
  sdkSuperFang,
  sdkBugBite,
  sdkPsychicFangs,
  sdkIronHead,
  sdkHeadbutt,
  sdkStomp,
  sdkHammerArm,
  sdkIceHammer,
  sdkSkyUppercut,
  sdkNeedleArm,
  sdkRockSmash,
  sdkCrabHammer,
  sdkDischarge,
  sdkSmartStrike,
  sdkMegaHorn,
  sdkDragonClaw,
  sdkPsychoCut,
  sdkWaterPulse,
  sdkPowerGem,
  sdkHeatWave,
  sdkMuddyWater,
  sdkEarthPower,
  sdkBugBuzz,
  sdkHyperVoice,
  sdkFlashCannon,
  sdkDragonPulse,
  sdkSludgeBomb,
  sdkMagicalLeaf,
  sdkStarVolley,
  sdkElectroweb,
  sdkBulletSeed,
  sdkSlam,
  sdkSpore,
  sdkPainSplit,
  sdkSkillSwap,
  sdkPlayRough,
  sdkSurf,
  sdkHydroPump,
  sdkLeafBlade,
  sdkXScissor,
  sdkFireFang,
  sdkIceFang,
  sdkThunderFang,
  sdkAirSlash,
  sdkDracoMeteor,
  sdkQuiverDance,
  sdkVictoryDance,
  sdkDragonDance,
  sdkFeatherDance,
  sdkFocusBlast,
  sdkSpinAttack,
  sdkVoltSwitch,
  sdkShockWave,
  sdkExplosion,
  sdkPopulationBomb,
  sdkAirCutter,
  sdkHurricane,
  sdkSunnyDay,
  sdkHail,
  sdkElectricTerrain,
  sdkGrassyTerrain,
  sdkMistyTerrain,
  sdkFollowMe,
  sdkKinesis,
  sdkSolarBeam,
  sdkThunder,
  sdkStoredPower,
  sdkPsychoBoost,
  sdkPsyshock,
  sdkHex,
  sdkWillOWisp,
  sdkLifeDew,
  sdkAromatherapy,
  sdkRest,
  sdkIngrain,
  sdkMorningSun,
  sdkShoreUp,
  sdkDrain,
  sdkLeechLife,
  sdkHornLeech,
  sdkParabolicCharge,
  sdkDrainingKiss,
  sdkOblivionWing,
  sdkLeechSeed,
  sdkWhirlwind,
  sdkFreezeDry,
  sdkMagmaStorm,
  sdkOriginPulse,
  sdkPsybeam,
  sdkAeroblast,
  sdkRoarOfTime,
  sdkRevelationDance,
  sdkHyperBeam,
  sdkSignalBeam,
  sdkFleurCannon,
  sdkArmorCannon,
  sdkSteelBeam,
  sdkBeakBlast,
  sdkTwinBeam,
  sdkSpikeCannon,
  sdkWaterShuriken,
  sdkTerastarStorm,
  sdkMeteorMash,
  sdkToxic,
  sdkToxicSpikes,
  sdkPoisonGas,
  sdkSmog,
  sdkClearSmog,
  sdkPoisonFang,
  sdkCrossPoison,
  sdkDireClaw,
  sdkSplash,
  sdkCelebrate,
  sdkOrderUp,
  sdkHeartStamp,
  sdkMatchaGotcha,
  sdkPresent,
  sdkPayDay,
  sdkRmxpMoveAnimation,
  noAnimation,
}

final class BattleMoveVisualCatalog {
  static const Map<String, BattleMoveVisualRecipeId> recipeBySDKMoveId =
      <String, BattleMoveVisualRecipeId>{
    'tackle': BattleMoveVisualRecipeId.sdkTackle,
    'scratch': BattleMoveVisualRecipeId.sdkScratch,
    'quickattack': BattleMoveVisualRecipeId.sdkQuickAttack,
    'slash': BattleMoveVisualRecipeId.sdkSlash,
    'aerialace': BattleMoveVisualRecipeId.sdkExactAerialAce,
    'closecombat': BattleMoveVisualRecipeId.sdkCloseCombat,
    'thunderbolt': BattleMoveVisualRecipeId.sdkThunderbolt,
    'chargebeam': BattleMoveVisualRecipeId.sdkChargeBeam,
    'doomdesire': BattleMoveVisualRecipeId.sdkDoomDesire,
    'seedflare': BattleMoveVisualRecipeId.sdkSeedFlare,
    'icywind': BattleMoveVisualRecipeId.sdkIcyWind,
    'weatherball': BattleMoveVisualRecipeId.sdkWeatherBall,
    'scald': BattleMoveVisualRecipeId.sdkScald,
    'triattack': BattleMoveVisualRecipeId.sdkTriAttack,
    'clangingscales': BattleMoveVisualRecipeId.sdkClangingScales,
    'flameburst': BattleMoveVisualRecipeId.sdkFlameBurst,
    'steameruption': BattleMoveVisualRecipeId.sdkSteamEruption,
    'watersport': BattleMoveVisualRecipeId.sdkWaterSport,
    'shadowball': BattleMoveVisualRecipeId.sdkShadowBall,
    'darkpulse': BattleMoveVisualRecipeId.sdkDarkPulse,
    'aurasphere': BattleMoveVisualRecipeId.sdkAuraSphere,
    'bubblebeam': BattleMoveVisualRecipeId.sdkBubbleBeam,
    'fireblast': BattleMoveVisualRecipeId.sdkFireBlast,
    'blizzard': BattleMoveVisualRecipeId.sdkBlizzard,
    'dazzlinggleam': BattleMoveVisualRecipeId.sdkDazzlingGleam,
    'growl': BattleMoveVisualRecipeId.sdkGrowl,
    'thunderwave': BattleMoveVisualRecipeId.sdkExactThunderWave,
    'thunder_wave': BattleMoveVisualRecipeId.sdkExactThunderWave,
    'calmmind': BattleMoveVisualRecipeId.sdkCalmMind,
    'swordsdance': BattleMoveVisualRecipeId.sdkSwordsDance,
    'agility': BattleMoveVisualRecipeId.sdkAgility,
    'bulkup': BattleMoveVisualRecipeId.sdkBulkUp,
    'focusenergy': BattleMoveVisualRecipeId.sdkBulkUp,
    'harden': BattleMoveVisualRecipeId.sdkReflect,
    'defensecurl': BattleMoveVisualRecipeId.sdkReflect,
    'irondefense': BattleMoveVisualRecipeId.sdkReflect,
    'cottonguard': BattleMoveVisualRecipeId.sdkReflect,
    'defendorder': BattleMoveVisualRecipeId.sdkReflect,
    'barrier': BattleMoveVisualRecipeId.sdkReflect,
    'flowershield': BattleMoveVisualRecipeId.sdkReflect,
    'howl': BattleMoveVisualRecipeId.sdkBulkUp,
    'meditate': BattleMoveVisualRecipeId.sdkBulkUp,
    'laserfocus': BattleMoveVisualRecipeId.sdkBulkUp,
    'sharpen': BattleMoveVisualRecipeId.sdkSwordsDance,
    'honeclaws': BattleMoveVisualRecipeId.sdkSwordsDance,
    'charge': BattleMoveVisualRecipeId.sdkCalmMind,
    'luckychant': BattleMoveVisualRecipeId.sdkCalmMind,
    'growth': BattleMoveVisualRecipeId.sdkCalmMind,
    'cosmicpower': BattleMoveVisualRecipeId.sdkCalmMind,
    'chargeup': BattleMoveVisualRecipeId.sdkCalmMind,
    'rockpolish': BattleMoveVisualRecipeId.sdkAgility,
    'autotomize': BattleMoveVisualRecipeId.sdkAgility,
    'shiftgear': BattleMoveVisualRecipeId.sdkAgility,
    'magnetrise': BattleMoveVisualRecipeId.sdkAgility,
    'minimize': BattleMoveVisualRecipeId.sdkAgility,
    'gearup': BattleMoveVisualRecipeId.sdkAgility,
    'tailglow': BattleMoveVisualRecipeId.sdkQuiverDance,
    'geomancy': BattleMoveVisualRecipeId.sdkQuiverDance,
    'charm': BattleMoveVisualRecipeId.sdkCharm,
    'confuseray': BattleMoveVisualRecipeId.sdkConfuseRay,
    'stealthrock': BattleMoveVisualRecipeId.sdkStealthRock,
    'spikes': BattleMoveVisualRecipeId.sdkSpikes,
    'raindance': BattleMoveVisualRecipeId.sdkRainDance,
    'sandstorm': BattleMoveVisualRecipeId.sdkSandstorm,
    'trickroom': BattleMoveVisualRecipeId.sdkTrickRoom,
    'protect': BattleMoveVisualRecipeId.sdkProtect,
    'detect': BattleMoveVisualRecipeId.sdkProtect,
    'kingsshield': BattleMoveVisualRecipeId.sdkProtect,
    'spikyshield': BattleMoveVisualRecipeId.sdkProtect,
    'endure': BattleMoveVisualRecipeId.sdkProtect,
    'magiccoat': BattleMoveVisualRecipeId.sdkProtect,
    'craftyshield': BattleMoveVisualRecipeId.sdkQuickGuard,
    'matblock': BattleMoveVisualRecipeId.sdkQuickGuard,
    'burningbulwark': BattleMoveVisualRecipeId.sdkBurningBulwark,
    'banefulbunker': BattleMoveVisualRecipeId.sdkBanefulBunker,
    'reflect': BattleMoveVisualRecipeId.sdkReflect,
    'lightscreen': BattleMoveVisualRecipeId.sdkLightScreen,
    'mist': BattleMoveVisualRecipeId.sdkMist,
    'auroraveil': BattleMoveVisualRecipeId.sdkAuroraVeil,
    'safeguard': BattleMoveVisualRecipeId.sdkSafeguard,
    'quickguard': BattleMoveVisualRecipeId.sdkQuickGuard,
    'wideguard': BattleMoveVisualRecipeId.sdkWideGuard,
    'tailwind': BattleMoveVisualRecipeId.sdkTailwind,
    'aquajet': BattleMoveVisualRecipeId.sdkAquaJet,
    'extremespeed': BattleMoveVisualRecipeId.sdkExtremeSpeed,
    'machpunch': BattleMoveVisualRecipeId.sdkMachPunch,
    'shadowpunch': BattleMoveVisualRecipeId.sdkShadowPunch,
    'focuspunch': BattleMoveVisualRecipeId.sdkFocusPunch,
    'drainpunch': BattleMoveVisualRecipeId.sdkDrainPunch,
    'dynamicpunch': BattleMoveVisualRecipeId.sdkDynamicPunch,
    'cometpunch': BattleMoveVisualRecipeId.sdkCometPunch,
    'megapunch': BattleMoveVisualRecipeId.sdkMegaPunch,
    'poweruppunch': BattleMoveVisualRecipeId.sdkPowerUpPunch,
    'dizzypunch': BattleMoveVisualRecipeId.sdkDizzyPunch,
    'jetpunch': BattleMoveVisualRecipeId.sdkJetPunch,
    'firepunch': BattleMoveVisualRecipeId.sdkFirePunch,
    'icepunch': BattleMoveVisualRecipeId.sdkIcePunch,
    'thunderpunch': BattleMoveVisualRecipeId.sdkThunderPunch,
    'blazekick': BattleMoveVisualRecipeId.sdkBlazeKick,
    'thunderouskick': BattleMoveVisualRecipeId.sdkThunderousKick,
    'tropkick': BattleMoveVisualRecipeId.sdkTropKick,
    'doublekick': BattleMoveVisualRecipeId.sdkDoubleKick,
    'bodyslam': BattleMoveVisualRecipeId.sdkBodySlam,
    'heavyslam': BattleMoveVisualRecipeId.sdkBodySlam,
    'bodypress': BattleMoveVisualRecipeId.sdkBodySlam,
    'dragonhammer': BattleMoveVisualRecipeId.sdkBodySlam,
    'jumpkick': BattleMoveVisualRecipeId.sdkHighJumpKick,
    'highjumpkick': BattleMoveVisualRecipeId.sdkHighJumpKick,
    'lowkick': BattleMoveVisualRecipeId.sdkHighJumpKick,
    'circlethrow': BattleMoveVisualRecipeId.sdkHighJumpKick,
    'axekick': BattleMoveVisualRecipeId.sdkHighJumpKick,
    'megakick': BattleMoveVisualRecipeId.sdkHighJumpKick,
    'karatechop': BattleMoveVisualRecipeId.sdkExactKarateChop,
    'forcepalm': BattleMoveVisualRecipeId.sdkKarateChop,
    'brickbreak': BattleMoveVisualRecipeId.sdkKarateChop,
    'throatchop': BattleMoveVisualRecipeId.sdkKarateChop,
    'stormthrow': BattleMoveVisualRecipeId.sdkKarateChop,
    'vitalthrow': BattleMoveVisualRecipeId.sdkKarateChop,
    'drillrun': BattleMoveVisualRecipeId.sdkDrillRun,
    'hyperdrill': BattleMoveVisualRecipeId.sdkDrillRun,
    'gunkshot': BattleMoveVisualRecipeId.sdkGunkShot,
    'sludge': BattleMoveVisualRecipeId.sdkGunkShot,
    'acid': BattleMoveVisualRecipeId.sdkSmog,
    'acidspray': BattleMoveVisualRecipeId.sdkSmog,
    'belch': BattleMoveVisualRecipeId.sdkGunkShot,
    'venomdrench': BattleMoveVisualRecipeId.sdkSmog,
    'mudshot': BattleMoveVisualRecipeId.sdkMudShot,
    'mudbomb': BattleMoveVisualRecipeId.sdkMudShot,
    'mudslap': BattleMoveVisualRecipeId.sdkMudShot,
    'electroball': BattleMoveVisualRecipeId.sdkElectroBall,
    'thundershock': BattleMoveVisualRecipeId.sdkRmxpMoveAnimation,
    'rockblast': BattleMoveVisualRecipeId.sdkRockBlast,
    'smackdown': BattleMoveVisualRecipeId.sdkRockBlast,
    'dualwingbeat': BattleMoveVisualRecipeId.sdkDualWingBeat,
    'bonemerang': BattleMoveVisualRecipeId.sdkBoneMerang,
    'spark': BattleMoveVisualRecipeId.sdkSpark,
    'wildcharge': BattleMoveVisualRecipeId.sdkWildCharge,
    'flareblitz': BattleMoveVisualRecipeId.sdkFlareBlitz,
    'accelerock': BattleMoveVisualRecipeId.sdkAccelerock,
    'wickedblow': BattleMoveVisualRecipeId.sdkWickedBlow,
    'doublehit': BattleMoveVisualRecipeId.sdkDoubleHit,
    'crunch': BattleMoveVisualRecipeId.sdkCrunch,
    'flamethrower': BattleMoveVisualRecipeId.sdkFlamethrower,
    'icebeam': BattleMoveVisualRecipeId.sdkIceBeam,
    'psychic': BattleMoveVisualRecipeId.sdkPsychic,
    'moonblast': BattleMoveVisualRecipeId.sdkMoonBlast,
    'poisonjab': BattleMoveVisualRecipeId.sdkPoisonJab,
    'earthquake': BattleMoveVisualRecipeId.sdkEarthquake,
    'energyball': BattleMoveVisualRecipeId.sdkEnergyBall,
    'rockslide': BattleMoveVisualRecipeId.sdkRockSlide,
    'nightslash': BattleMoveVisualRecipeId.sdkNightSlash,
    'gigaimpact': BattleMoveVisualRecipeId.sdkGigaImpact,
    'powerwhip': BattleMoveVisualRecipeId.sdkPowerWhip,
    'woodhammer': BattleMoveVisualRecipeId.sdkWoodHammer,
    'ivycudgel': BattleMoveVisualRecipeId.sdkIvyCudgel,
    'ivycudgelwater': BattleMoveVisualRecipeId.sdkIvyCudgelWater,
    'ivycudgelfire': BattleMoveVisualRecipeId.sdkIvyCudgelFire,
    'ivycudgelrock': BattleMoveVisualRecipeId.sdkIvyCudgelRock,
    'cut': BattleMoveVisualRecipeId.sdkCut,
    'shadowclaw': BattleMoveVisualRecipeId.sdkShadowClaw,
    'multiattack': BattleMoveVisualRecipeId.sdkMultiAttack,
    'bite': BattleMoveVisualRecipeId.sdkBite,
    'superfang': BattleMoveVisualRecipeId.sdkSuperFang,
    'bugbite': BattleMoveVisualRecipeId.sdkBugBite,
    'psychicfangs': BattleMoveVisualRecipeId.sdkPsychicFangs,
    'ironhead': BattleMoveVisualRecipeId.sdkIronHead,
    'headbutt': BattleMoveVisualRecipeId.sdkHeadbutt,
    'stomp': BattleMoveVisualRecipeId.sdkStomp,
    'hammerarm': BattleMoveVisualRecipeId.sdkHammerArm,
    'icehammer': BattleMoveVisualRecipeId.sdkIceHammer,
    'skyuppercut': BattleMoveVisualRecipeId.sdkSkyUppercut,
    'needlearm': BattleMoveVisualRecipeId.sdkNeedleArm,
    'rocksmash': BattleMoveVisualRecipeId.sdkRockSmash,
    'highhorsepower': BattleMoveVisualRecipeId.sdkStomp,
    'hyperfang': BattleMoveVisualRecipeId.sdkSuperFang,
    'firelash': BattleMoveVisualRecipeId.sdkMultiAttack,
    'crabhammer': BattleMoveVisualRecipeId.sdkCrabHammer,
    'discharge': BattleMoveVisualRecipeId.sdkDischarge,
    'smartstrike': BattleMoveVisualRecipeId.sdkSmartStrike,
    'megahorn': BattleMoveVisualRecipeId.sdkMegaHorn,
    'dragonclaw': BattleMoveVisualRecipeId.sdkDragonClaw,
    'psychocut': BattleMoveVisualRecipeId.sdkPsychoCut,
    'waterpulse': BattleMoveVisualRecipeId.sdkWaterPulse,
    'powergem': BattleMoveVisualRecipeId.sdkPowerGem,
    'heatwave': BattleMoveVisualRecipeId.sdkHeatWave,
    'muddywater': BattleMoveVisualRecipeId.sdkMuddyWater,
    'earthpower': BattleMoveVisualRecipeId.sdkEarthPower,
    'bugbuzz': BattleMoveVisualRecipeId.sdkBugBuzz,
    'hypervoice': BattleMoveVisualRecipeId.sdkHyperVoice,
    'hyperbeam': BattleMoveVisualRecipeId.sdkHyperBeam,
    'flashcannon': BattleMoveVisualRecipeId.sdkFlashCannon,
    'signalbeam': BattleMoveVisualRecipeId.sdkSignalBeam,
    'dragonpulse': BattleMoveVisualRecipeId.sdkDragonPulse,
    'sludgebomb': BattleMoveVisualRecipeId.sdkSludgeBomb,
    'magicalleaf': BattleMoveVisualRecipeId.sdkMagicalLeaf,
    'electroweb': BattleMoveVisualRecipeId.sdkElectroweb,
    'bulletseed': BattleMoveVisualRecipeId.sdkBulletSeed,
    'slam': BattleMoveVisualRecipeId.sdkSlam,
    'spore': BattleMoveVisualRecipeId.sdkSpore,
    'painsplit': BattleMoveVisualRecipeId.sdkPainSplit,
    'skillswap': BattleMoveVisualRecipeId.sdkSkillSwap,
    'playrough': BattleMoveVisualRecipeId.sdkPlayRough,
    'surf': BattleMoveVisualRecipeId.sdkSurf,
    'hydropump': BattleMoveVisualRecipeId.sdkHydroPump,
    'leafblade': BattleMoveVisualRecipeId.sdkLeafBlade,
    'xscissor': BattleMoveVisualRecipeId.sdkXScissor,
    'firefang': BattleMoveVisualRecipeId.sdkFireFang,
    'icefang': BattleMoveVisualRecipeId.sdkIceFang,
    'thunderfang': BattleMoveVisualRecipeId.sdkThunderFang,
    'airslash': BattleMoveVisualRecipeId.sdkExactAirSlash,
    'dracometeor': BattleMoveVisualRecipeId.sdkDracoMeteor,
    'fleurcannon': BattleMoveVisualRecipeId.sdkFleurCannon,
    'armorcannon': BattleMoveVisualRecipeId.sdkArmorCannon,
    'steelbeam': BattleMoveVisualRecipeId.sdkSteelBeam,
    'beakblast': BattleMoveVisualRecipeId.sdkBeakBlast,
    'twinbeam': BattleMoveVisualRecipeId.sdkTwinBeam,
    'spikecannon': BattleMoveVisualRecipeId.sdkSpikeCannon,
    'terastarstorm': BattleMoveVisualRecipeId.sdkTerastarStorm,
    'meteormash': BattleMoveVisualRecipeId.sdkMeteorMash,
    'toxic': BattleMoveVisualRecipeId.sdkToxic,
    'toxicspikes': BattleMoveVisualRecipeId.sdkToxicSpikes,
    'poisongas': BattleMoveVisualRecipeId.sdkPoisonGas,
    'smog': BattleMoveVisualRecipeId.sdkSmog,
    'clearsmog': BattleMoveVisualRecipeId.sdkClearSmog,
    'poisonfang': BattleMoveVisualRecipeId.sdkPoisonFang,
    'crosspoison': BattleMoveVisualRecipeId.sdkCrossPoison,
    'direclaw': BattleMoveVisualRecipeId.sdkDireClaw,
    'quiverdance': BattleMoveVisualRecipeId.sdkQuiverDance,
    'victorydance': BattleMoveVisualRecipeId.sdkVictoryDance,
    'dragondance': BattleMoveVisualRecipeId.sdkDragonDance,
    'featherdance': BattleMoveVisualRecipeId.sdkFeatherDance,
    'bravebird': BattleMoveVisualRecipeId.sdkAerialAce,
    'acrobatics': BattleMoveVisualRecipeId.sdkExactAcrobatics,
    'flyingpress': BattleMoveVisualRecipeId.sdkAerialAce,
    'steelwing': BattleMoveVisualRecipeId.sdkAerialAce,
    'wingattack': BattleMoveVisualRecipeId.sdkAerialAce,
    'fly': BattleMoveVisualRecipeId.sdkAerialAce,
    'skyattack': BattleMoveVisualRecipeId.sdkAerialAce,
    'dragonbreath': BattleMoveVisualRecipeId.sdkDragonPulse,
    'focusblast': BattleMoveVisualRecipeId.sdkFocusBlast,
    'uturn': BattleMoveVisualRecipeId.sdkSpinAttack,
    'rapidspin': BattleMoveVisualRecipeId.sdkSpinAttack,
    'gyroball': BattleMoveVisualRecipeId.sdkSpinAttack,
    'flipturn': BattleMoveVisualRecipeId.sdkSpinAttack,
    'mortalspin': BattleMoveVisualRecipeId.sdkSpinAttack,
    'icespinner': BattleMoveVisualRecipeId.sdkSpinAttack,
    'voltswitch': BattleMoveVisualRecipeId.sdkVoltSwitch,
    'shockwave': BattleMoveVisualRecipeId.sdkRmxpMoveAnimation,
    'explosion': BattleMoveVisualRecipeId.sdkExplosion,
    'populationbomb': BattleMoveVisualRecipeId.sdkPopulationBomb,
    'aircutter': BattleMoveVisualRecipeId.sdkAirCutter,
    'hurricane': BattleMoveVisualRecipeId.sdkHurricane,
    'sunnyday': BattleMoveVisualRecipeId.sdkSunnyDay,
    'hail': BattleMoveVisualRecipeId.sdkHail,
    'snowscape': BattleMoveVisualRecipeId.sdkHail,
    'chillyreception': BattleMoveVisualRecipeId.sdkHail,
    'magicroom': BattleMoveVisualRecipeId.sdkTrickRoom,
    'wonderroom': BattleMoveVisualRecipeId.sdkTrickRoom,
    'afteryou': BattleMoveVisualRecipeId.sdkAgility,
    'babydolleyes': BattleMoveVisualRecipeId.sdkBabyDollEyes,
    'faketears': BattleMoveVisualRecipeId.sdkGrowl,
    'tearfullook': BattleMoveVisualRecipeId.sdkGrowl,
    'foresight': BattleMoveVisualRecipeId.sdkKinesis,
    'sketch': BattleMoveVisualRecipeId.sdkSkillSwap,
    'doodle': BattleMoveVisualRecipeId.sdkSkillSwap,
    'odorsleuth': BattleMoveVisualRecipeId.sdkKinesis,
    'playnice': BattleMoveVisualRecipeId.sdkGrowl,
    'tailwhip': BattleMoveVisualRecipeId.sdkExactTailWhip,
    'leer': BattleMoveVisualRecipeId.sdkGrowl,
    'snatch': BattleMoveVisualRecipeId.sdkFollowMe,
    'electricterrain': BattleMoveVisualRecipeId.sdkElectricTerrain,
    'grassyterrain': BattleMoveVisualRecipeId.sdkGrassyTerrain,
    'mistyterrain': BattleMoveVisualRecipeId.sdkMistyTerrain,
    'junglehealing': BattleMoveVisualRecipeId.sdkGrassyTerrain,
    'followme': BattleMoveVisualRecipeId.sdkFollowMe,
    'kinesis': BattleMoveVisualRecipeId.sdkKinesis,
    'technoblast': BattleMoveVisualRecipeId.sdkFocusBlast,
    'flail': BattleMoveVisualRecipeId.sdkSlam,
    'facade': BattleMoveVisualRecipeId.sdkSlam,
    'furyattack': BattleMoveVisualRecipeId.sdkDoubleHit,
    'flamecharge': BattleMoveVisualRecipeId.sdkFlareBlitz,
    'leafstorm': BattleMoveVisualRecipeId.sdkMagicalLeaf,
    'solarbeam': BattleMoveVisualRecipeId.sdkSolarBeam,
    'thunder': BattleMoveVisualRecipeId.sdkThunder,
    'zapcannon': BattleMoveVisualRecipeId.sdkThunder,
    'sludgewave': BattleMoveVisualRecipeId.sdkSludgeBomb,
    'meteorbeam': BattleMoveVisualRecipeId.sdkSolarBeam,
    'blastburn': BattleMoveVisualRecipeId.sdkArmorCannon,
    'chloroblast': BattleMoveVisualRecipeId.sdkFleurCannon,
    'simplebeam': BattleMoveVisualRecipeId.sdkSignalBeam,
    'magnetbomb': BattleMoveVisualRecipeId.sdkSteelBeam,
    'maxstarfall': BattleMoveVisualRecipeId.sdkTerastarStorm,
    'storedpower': BattleMoveVisualRecipeId.sdkStoredPower,
    'powertrip': BattleMoveVisualRecipeId.sdkStoredPower,
    'psychoboost': BattleMoveVisualRecipeId.sdkPsychoBoost,
    'psychicnoise': BattleMoveVisualRecipeId.sdkPsychoBoost,
    'prismaticlaser': BattleMoveVisualRecipeId.sdkPsychoBoost,
    'psyshock': BattleMoveVisualRecipeId.sdkPsyshock,
    'psystrike': BattleMoveVisualRecipeId.sdkPsyshock,
    'hex': BattleMoveVisualRecipeId.sdkHex,
    'nightshade': BattleMoveVisualRecipeId.sdkHex,
    'ominouswind': BattleMoveVisualRecipeId.sdkHex,
    'blackholeeclipse': BattleMoveVisualRecipeId.sdkHex,
    'neverendingnightmare': BattleMoveVisualRecipeId.sdkHex,
    'moongeistbeam': BattleMoveVisualRecipeId.sdkHex,
    'astralbarrage': BattleMoveVisualRecipeId.sdkHex,
    'soulstealing7starstrike': BattleMoveVisualRecipeId.sdkHex,
    'willowisp': BattleMoveVisualRecipeId.sdkWillOWisp,
    'lifedew': BattleMoveVisualRecipeId.sdkLifeDew,
    'healpulse': BattleMoveVisualRecipeId.sdkLifeDew,
    'aquaring': BattleMoveVisualRecipeId.sdkExactAquaRing,
    'softboiled': BattleMoveVisualRecipeId.sdkLifeDew,
    'moonlight': BattleMoveVisualRecipeId.sdkLifeDew,
    'lunarblessing': BattleMoveVisualRecipeId.sdkLifeDew,
    'revivalblessing': BattleMoveVisualRecipeId.sdkLifeDew,
    'recover': BattleMoveVisualRecipeId.sdkExactRecover,
    'roost': BattleMoveVisualRecipeId.sdkLifeDew,
    'healorder': BattleMoveVisualRecipeId.sdkLifeDew,
    'aromatherapy': BattleMoveVisualRecipeId.sdkAromatherapy,
    'healbell': BattleMoveVisualRecipeId.sdkAromatherapy,
    'refresh': BattleMoveVisualRecipeId.sdkAromatherapy,
    'rest': BattleMoveVisualRecipeId.sdkRest,
    'swallow': BattleMoveVisualRecipeId.sdkRest,
    'milkdrink': BattleMoveVisualRecipeId.sdkRest,
    'ingrain': BattleMoveVisualRecipeId.sdkIngrain,
    'morningsun': BattleMoveVisualRecipeId.sdkMorningSun,
    'shoreup': BattleMoveVisualRecipeId.sdkShoreUp,
    'absorb': BattleMoveVisualRecipeId.sdkDrain,
    'megadrain': BattleMoveVisualRecipeId.sdkDrain,
    'gigadrain': BattleMoveVisualRecipeId.sdkDrain,
    'leechlife': BattleMoveVisualRecipeId.sdkLeechLife,
    'strengthsap': BattleMoveVisualRecipeId.sdkLeechLife,
    'hornleech': BattleMoveVisualRecipeId.sdkHornLeech,
    'paraboliccharge': BattleMoveVisualRecipeId.sdkParabolicCharge,
    'drainingkiss': BattleMoveVisualRecipeId.sdkDrainingKiss,
    'oblivionwing': BattleMoveVisualRecipeId.sdkOblivionWing,
    'whirlwind': BattleMoveVisualRecipeId.sdkWhirlwind,
    'gust': BattleMoveVisualRecipeId.sdkWhirlwind,
    'silverwind': BattleMoveVisualRecipeId.sdkWhirlwind,
    'twister': BattleMoveVisualRecipeId.sdkWhirlwind,
    'freezedry': BattleMoveVisualRecipeId.sdkFreezeDry,
    'frostbreath': BattleMoveVisualRecipeId.sdkFreezeDry,
    'glaciate': BattleMoveVisualRecipeId.sdkFreezeDry,
    'magmastorm': BattleMoveVisualRecipeId.sdkMagmaStorm,
    'fierydance': BattleMoveVisualRecipeId.sdkMagmaStorm,
    'inferno': BattleMoveVisualRecipeId.sdkMagmaStorm,
    'originpulse': BattleMoveVisualRecipeId.sdkOriginPulse,
    'hydrovortex': BattleMoveVisualRecipeId.sdkOriginPulse,
    'maxgeyser': BattleMoveVisualRecipeId.sdkOriginPulse,
    'gmaxcannonade': BattleMoveVisualRecipeId.sdkOriginPulse,
    'gmaxhydrosnipe': BattleMoveVisualRecipeId.sdkOriginPulse,
    'psybeam': BattleMoveVisualRecipeId.sdkPsybeam,
    'psywave': BattleMoveVisualRecipeId.sdkPsybeam,
    'expandingforce': BattleMoveVisualRecipeId.sdkPsybeam,
    'aeroblast': BattleMoveVisualRecipeId.sdkAeroblast,
    'terablastflying': BattleMoveVisualRecipeId.sdkAeroblast,
    'roaroftime': BattleMoveVisualRecipeId.sdkRoarOfTime,
    'eternabeam': BattleMoveVisualRecipeId.sdkRoarOfTime,
    'revelationdance': BattleMoveVisualRecipeId.sdkRevelationDance,
    'pollenpuff': BattleMoveVisualRecipeId.sdkRevelationDance,
    'taunt': BattleMoveVisualRecipeId.sdkTaunt,
    'instruct': BattleMoveVisualRecipeId.sdkInstruct,
    'doubleteam': BattleMoveVisualRecipeId.sdkAgility,
    'metronome': BattleMoveVisualRecipeId.sdkSkillSwap,
    'teeterdance': BattleMoveVisualRecipeId.sdkConfuseRay,
    'encore': BattleMoveVisualRecipeId.sdkEncore,
    'gravity': BattleMoveVisualRecipeId.sdkTrickRoom,
    'topsyturvy': BattleMoveVisualRecipeId.sdkSkillSwap,
    'allyswitch': BattleMoveVisualRecipeId.sdkAgility,
    'healblock': BattleMoveVisualRecipeId.sdkGrowl,
    'flash': BattleMoveVisualRecipeId.sdkKinesis,
    'transform': BattleMoveVisualRecipeId.sdkSkillSwap,
    'bellydrum': BattleMoveVisualRecipeId.sdkBulkUp,
    'bide': BattleMoveVisualRecipeId.sdkBulkUp,
    'acupressure': BattleMoveVisualRecipeId.sdkCalmMind,
    'curse': BattleMoveVisualRecipeId.sdkBulkUp,
    'shellsmash': BattleMoveVisualRecipeId.sdkQuiverDance,
    'coil': BattleMoveVisualRecipeId.sdkBulkUp,
    'powertrick': BattleMoveVisualRecipeId.sdkSkillSwap,
    'recycle': BattleMoveVisualRecipeId.sdkCalmMind,
    'teleport': BattleMoveVisualRecipeId.sdkAgility,
    'happyhour': BattleMoveVisualRecipeId.sdkCalmMind,
    'acidarmor': BattleMoveVisualRecipeId.sdkExactAcidArmor,
    'batonpass': BattleMoveVisualRecipeId.sdkAgility,
    'nastyplot': BattleMoveVisualRecipeId.sdkCalmMind,
    'takeheart': BattleMoveVisualRecipeId.sdkCalmMind,
    'trick': BattleMoveVisualRecipeId.sdkSkillSwap,
    'switcheroo': BattleMoveVisualRecipeId.sdkSkillSwap,
    'haze': BattleMoveVisualRecipeId.sdkMist,
    'assist': BattleMoveVisualRecipeId.sdkSkillSwap,
    'mirrormove': BattleMoveVisualRecipeId.sdkSkillSwap,
    'naturepower': BattleMoveVisualRecipeId.sdkSkillSwap,
    'copycat': BattleMoveVisualRecipeId.sdkSkillSwap,
    'sleeptalk': BattleMoveVisualRecipeId.sdkSkillSwap,
    'yawn': BattleMoveVisualRecipeId.sdkConfuseRay,
    'sing': BattleMoveVisualRecipeId.sdkHyperVoice,
    'perishsong': BattleMoveVisualRecipeId.sdkHyperVoice,
    'screech': BattleMoveVisualRecipeId.sdkHyperVoice,
    'snore': BattleMoveVisualRecipeId.sdkHyperVoice,
    'synchronoise': BattleMoveVisualRecipeId.sdkHyperVoice,
    'sonicboom': BattleMoveVisualRecipeId.sdkHyperVoice,
    'eerieimpulse': BattleMoveVisualRecipeId.sdkGrowl,
    'metalsound': BattleMoveVisualRecipeId.sdkGrowl,
    'supersonic': BattleMoveVisualRecipeId.sdkConfuseRay,
    'confide': BattleMoveVisualRecipeId.sdkGrowl,
    'defog': BattleMoveVisualRecipeId.sdkMist,
    'grasswhistle': BattleMoveVisualRecipeId.sdkHyperVoice,
    'boomburst': BattleMoveVisualRecipeId.sdkHyperVoice,
    'snarl': BattleMoveVisualRecipeId.sdkDarkPulse,
    'fairylock': BattleMoveVisualRecipeId.sdkMist,
    'spicyextract': BattleMoveVisualRecipeId.sdkCharm,
    'tickle': BattleMoveVisualRecipeId.sdkCharm,
    'disarmingvoice': BattleMoveVisualRecipeId.sdkHyperVoice,
    'round': BattleMoveVisualRecipeId.sdkHyperVoice,
    'splash': BattleMoveVisualRecipeId.sdkSplash,
    'celebrate': BattleMoveVisualRecipeId.sdkCelebrate,
    'holdback': BattleMoveVisualRecipeId.sdkTackle,
    'knockdown': BattleMoveVisualRecipeId.sdkBodySlam,
    'seismictoss': BattleMoveVisualRecipeId.sdkBodySlam,
    'irontail': BattleMoveVisualRecipeId.sdkIronHead,
    'pursuit': BattleMoveVisualRecipeId.sdkNightSlash,
    'dragontail': BattleMoveVisualRecipeId.sdkBodySlam,
    'reversal': BattleMoveVisualRecipeId.sdkCloseCombat,
    'punishment': BattleMoveVisualRecipeId.sdkNightSlash,
    'knockoff': BattleMoveVisualRecipeId.sdkNightSlash,
    'assurance': BattleMoveVisualRecipeId.sdkExactAssurance,
    'chipaway': BattleMoveVisualRecipeId.sdkTackle,
    'bloodmoon': BattleMoveVisualRecipeId.sdkMoonBlast,
    'gigatonhammer': BattleMoveVisualRecipeId.sdkHammerArm,
    'pound': BattleMoveVisualRecipeId.sdkTackle,
    'clamp': BattleMoveVisualRecipeId.sdkCrabHammer,
    'lick': BattleMoveVisualRecipeId.sdkShadowPunch,
    'visegrip': BattleMoveVisualRecipeId.sdkCrabHammer,
    'block': BattleMoveVisualRecipeId.sdkConfuseRay,
    'guillotine': BattleMoveVisualRecipeId.sdkDrillRun,
    'return': BattleMoveVisualRecipeId.sdkTackle,
    'endeavor': BattleMoveVisualRecipeId.sdkTackle,
    'strength': BattleMoveVisualRecipeId.sdkBodySlam,
    'ragefist': BattleMoveVisualRecipeId.sdkShadowPunch,
    'fakeout': BattleMoveVisualRecipeId.sdkQuickAttack,
    'covet': BattleMoveVisualRecipeId.sdkTackle,
    'feint': BattleMoveVisualRecipeId.sdkQuickAttack,
    'thief': BattleMoveVisualRecipeId.sdkNightSlash,
    'shadowsneak': BattleMoveVisualRecipeId.sdkShadowPunch,
    'struggle': BattleMoveVisualRecipeId.sdkTackle,
    'bulldoze': BattleMoveVisualRecipeId.sdkEarthquake,
    'shadowbone': BattleMoveVisualRecipeId.sdkShadowPunch,
    'spinout': BattleMoveVisualRecipeId.sdkIronHead,
    'geargrind': BattleMoveVisualRecipeId.sdkSpikeCannon,
    'iciclespear': BattleMoveVisualRecipeId.sdkBulletSeed,
    'tailslap': BattleMoveVisualRecipeId.sdkDoubleHit,
    'furyswipes': BattleMoveVisualRecipeId.sdkDoubleHit,
    'twineedle': BattleMoveVisualRecipeId.sdkBulletSeed,
    'aquastep': BattleMoveVisualRecipeId.sdkAquaJet,
    'iceshard': BattleMoveVisualRecipeId.sdkQuickAttack,
    'ancientpower': BattleMoveVisualRecipeId.sdkPowerGem,
    'rockwrecker': BattleMoveVisualRecipeId.sdkRockSlide,
    'stoneedge': BattleMoveVisualRecipeId.sdkRockBlast,
    'hiddenpower': BattleMoveVisualRecipeId.sdkHiddenPower,
    'vacuumwave': BattleMoveVisualRecipeId.sdkAuraSphere,
    'burnup': BattleMoveVisualRecipeId.sdkFlamethrower,
    'springtidestorm': BattleMoveVisualRecipeId.sdkMoonBlast,
    'sandsearstorm': BattleMoveVisualRecipeId.sdkEarthPower,
    'leaftornado': BattleMoveVisualRecipeId.sdkMagicalLeaf,
    'roar': BattleMoveVisualRecipeId.sdkHyperVoice,
    'bounce': BattleMoveVisualRecipeId.sdkHighJumpKick,
    'dig': BattleMoveVisualRecipeId.sdkDrillRun,
    'skydrop': BattleMoveVisualRecipeId.sdkAerialAce,
    'skullbash': BattleMoveVisualRecipeId.sdkHeadbutt,
    'vcreate': BattleMoveVisualRecipeId.sdkFlareBlitz,
    'ragingfury': BattleMoveVisualRecipeId.sdkFlareBlitz,
    'zenheadbutt': BattleMoveVisualRecipeId.sdkHeadbutt,
    'firespin': BattleMoveVisualRecipeId.sdkMagmaStorm,
    'thundercage': BattleMoveVisualRecipeId.sdkChargeBeam,
    'wavecrash': BattleMoveVisualRecipeId.sdkOriginPulse,
    'freezingglare': BattleMoveVisualRecipeId.sdkFreezeDry,
    'stickyweb': BattleMoveVisualRecipeId.sdkElectroweb,
    'mysticalpower': BattleMoveVisualRecipeId.sdkPsychic,
    'barbbarrage': BattleMoveVisualRecipeId.sdkBulletSeed,
    'sandtomb': BattleMoveVisualRecipeId.sdkMagmaStorm,
    'lusterpurge': BattleMoveVisualRecipeId.sdkPsychic,
    'grassknot': BattleMoveVisualRecipeId.sdkMagicalLeaf,
    'makeitrain': BattleMoveVisualRecipeId.sdkFlashCannon,
    'brine': BattleMoveVisualRecipeId.sdkWaterPulse,
    'octazooka': BattleMoveVisualRecipeId.sdkWaterPulse,
    'waterpledge': BattleMoveVisualRecipeId.sdkBubbleBeam,
    'soak': BattleMoveVisualRecipeId.sdkWaterSport,
    'lavaplume': BattleMoveVisualRecipeId.sdkHeatWave,
    'eruption': BattleMoveVisualRecipeId.sdkFireBlast,
    'waterspout': BattleMoveVisualRecipeId.sdkOriginPulse,
    'solarblade': BattleMoveVisualRecipeId.sdkLeafBlade,
    'lightofruin': BattleMoveVisualRecipeId.sdkDazzlingGleam,
    'glaciallance': BattleMoveVisualRecipeId.sdkIceHammer,
    'freezeshock': BattleMoveVisualRecipeId.sdkBlizzard,
    'overheat': BattleMoveVisualRecipeId.sdkFireBlast,
    'sacredfire': BattleMoveVisualRecipeId.sdkFireBlast,
    'blueflare': BattleMoveVisualRecipeId.sdkFireBlast,
    'rockthrow': BattleMoveVisualRecipeId.sdkRockBlast,
    'hypnosis': BattleMoveVisualRecipeId.sdkConfuseRay,
    'darkvoid': BattleMoveVisualRecipeId.sdkConfuseRay,
    'spacialrend': BattleMoveVisualRecipeId.sdkDracoMeteor,
    'dragonascent': BattleMoveVisualRecipeId.sdkAerialAce,
    'petalblizzard': BattleMoveVisualRecipeId.sdkMagicalLeaf,
    'leafage': BattleMoveVisualRecipeId.sdkMagicalLeaf,
    'lockon': BattleMoveVisualRecipeId.sdkKinesis,
    'avalanche': BattleMoveVisualRecipeId.sdkExactAvalanche,
    'thousandarrows': BattleMoveVisualRecipeId.sdkEarthquake,
    'thousandwaves': BattleMoveVisualRecipeId.sdkEarthquake,
    'iciclecrash': BattleMoveVisualRecipeId.sdkIceHammer,
    'fierywrath': BattleMoveVisualRecipeId.sdkDarkPulse,
    'terrainpulse': BattleMoveVisualRecipeId.sdkWeatherBall,
    'naturesmadness': BattleMoveVisualRecipeId.sdkPainSplit,
    'ruination': BattleMoveVisualRecipeId.sdkPainSplit,
    'flowertrick': BattleMoveVisualRecipeId.sdkLeafBlade,
    'worryseed': BattleMoveVisualRecipeId.sdkMagicalLeaf,
    'tripleaxel': BattleMoveVisualRecipeId.sdkDoubleKick,
    'hyperspacehole': BattleMoveVisualRecipeId.sdkPsychic,
    'hyperspacefury': BattleMoveVisualRecipeId.sdkNightSlash,
    'bestow': BattleMoveVisualRecipeId.sdkSkillSwap,
    'finalgambit': BattleMoveVisualRecipeId.sdkPainSplit,
    'forestscurse': BattleMoveVisualRecipeId.sdkSkillSwap,
    'trickortreat': BattleMoveVisualRecipeId.sdkSkillSwap,
    'spite': BattleMoveVisualRecipeId.sdkHex,
    'spiritshackle': BattleMoveVisualRecipeId.sdkNightSlash,
    'brutalswing': BattleMoveVisualRecipeId.sdkDarkPulse,
    'firstimpression': BattleMoveVisualRecipeId.sdkQuickAttack,
    'plasmafists': BattleMoveVisualRecipeId.sdkThunderPunch,
    'collisioncourse': BattleMoveVisualRecipeId.sdkCloseCombat,
    'electrodrift': BattleMoveVisualRecipeId.sdkWildCharge,
    'sunsteelstrike': BattleMoveVisualRecipeId.sdkSmartStrike,
    'photongeyser': BattleMoveVisualRecipeId.sdkPsychic,
    'coreenforcer': BattleMoveVisualRecipeId.sdkDragonPulse,
    'stokedsparksurfer': BattleMoveVisualRecipeId.sdkThunderbolt,
    'catastropika': BattleMoveVisualRecipeId.sdkThunderbolt,
    'sinisterarrowraid': BattleMoveVisualRecipeId.sdkNightSlash,
    'oceanicoperetta': BattleMoveVisualRecipeId.sdkOriginPulse,
    'splinteredstormshards': BattleMoveVisualRecipeId.sdkRockSlide,
    'letssnuggleforever': BattleMoveVisualRecipeId.sdkPlayRough,
    'clangoroussoulblaze': BattleMoveVisualRecipeId.sdkClangingScales,
    'searingsunrazesmash': BattleMoveVisualRecipeId.sdkFlareBlitz,
    'supercellslam': BattleMoveVisualRecipeId.sdkWildCharge,
    'fishiousrend': BattleMoveVisualRecipeId.sdkAquaJet,
    'stompingtantrum': BattleMoveVisualRecipeId.sdkStomp,
    'temperflare': BattleMoveVisualRecipeId.sdkFlareBlitz,
    'thunderclap': BattleMoveVisualRecipeId.sdkSpark,
    'spiritbreak': BattleMoveVisualRecipeId.sdkPlayRough,
    'stoneaxe': BattleMoveVisualRecipeId.sdkRockBlast,
    'malignantchain': BattleMoveVisualRecipeId.sdkToxic,
    'hardpress': BattleMoveVisualRecipeId.sdkBodySlam,
    'dragoncheer': BattleMoveVisualRecipeId.sdkDragonDance,
    'upperhand': BattleMoveVisualRecipeId.sdkMachPunch,
    'blazingtorque': BattleMoveVisualRecipeId.sdkFlareBlitz,
    'combattorque': BattleMoveVisualRecipeId.sdkCloseCombat,
    'magicaltorque': BattleMoveVisualRecipeId.sdkPlayRough,
    'noxioustorque': BattleMoveVisualRecipeId.sdkGunkShot,
    'wickedtorque': BattleMoveVisualRecipeId.sdkNightSlash,
    'watershuriken': BattleMoveVisualRecipeId.sdkWaterShuriken,
    'triplearrows': BattleMoveVisualRecipeId.sdkBulletSeed,
    'judgment': BattleMoveVisualRecipeId.sdkFocusBlast,
    'gmaxsteelsurge': BattleMoveVisualRecipeId.sdkFlashCannon,
    'saltcure': BattleMoveVisualRecipeId.sdkStealthRock,
    'iceburn': BattleMoveVisualRecipeId.sdkFireBlast,
    'orderup': BattleMoveVisualRecipeId.sdkOrderUp,
    'heartstamp': BattleMoveVisualRecipeId.sdkHeartStamp,
    'matchagotcha': BattleMoveVisualRecipeId.sdkMatchaGotcha,
    'present': BattleMoveVisualRecipeId.sdkPresent,
    'payday': BattleMoveVisualRecipeId.sdkPayDay,
    'fling': BattleMoveVisualRecipeId.sdkGunkShot,
    'swift': BattleMoveVisualRecipeId.sdkRmxpMoveAnimation,
    'guardianofalola': BattleMoveVisualRecipeId.sdkMoonBlast,
    'ragepowder': BattleMoveVisualRecipeId.sdkFollowMe,
    'spotlight': BattleMoveVisualRecipeId.sdkFollowMe,
    'wish': BattleMoveVisualRecipeId.sdkLifeDew,
    'healingwish': BattleMoveVisualRecipeId.sdkLifeDew,
    'nobleroar': BattleMoveVisualRecipeId.sdkGrowl,
    'partingshot': BattleMoveVisualRecipeId.sdkGrowl,
    'sandattack': BattleMoveVisualRecipeId.sdkKinesis,
    'smokescreen': BattleMoveVisualRecipeId.sdkKinesis,
    'swagger': BattleMoveVisualRecipeId.sdkSwagger,
    'mimic': BattleMoveVisualRecipeId.sdkSkillSwap,
    'conversion': BattleMoveVisualRecipeId.sdkCalmMind,
    'shelltrap': BattleMoveVisualRecipeId.sdkMagmaStorm,
    'outrage': BattleMoveVisualRecipeId.sdkDragonClaw,
    'bind': BattleMoveVisualRecipeId.sdkPowerWhip,
    'thrash': BattleMoveVisualRecipeId.sdkGigaImpact,
    'quash': BattleMoveVisualRecipeId.sdkQuash,
    'boneclub': BattleMoveVisualRecipeId.sdkDrillRun,
    'mindreader': BattleMoveVisualRecipeId.sdkKinesis,
    'meanlook': BattleMoveVisualRecipeId.sdkConfuseRay,
    'attract': BattleMoveVisualRecipeId.sdkCharm,
    'smellingsalts': BattleMoveVisualRecipeId.sdkBodySlam,
    'shadowforce': BattleMoveVisualRecipeId.sdkShadowClaw,
    'lovelykiss': BattleMoveVisualRecipeId.sdkDrainingKiss,
    'embargo': BattleMoveVisualRecipeId.sdkKinesis,
    'petaldance': BattleMoveVisualRecipeId.sdkMagicalLeaf,
    'pulverizingpancake': BattleMoveVisualRecipeId.sdkBodySlam,
    'precipiceblades': BattleMoveVisualRecipeId.sdkEarthquake,
    'sheercold': BattleMoveVisualRecipeId.sdkBlizzard,
    'fusionflare': BattleMoveVisualRecipeId.sdkFireBlast,
    'breakneckblitz': BattleMoveVisualRecipeId.sdkGigaImpact,
    'devastatingdrake': BattleMoveVisualRecipeId.sdkDragonPulse,
    'savagespinout': BattleMoveVisualRecipeId.sdkElectroweb,
    'shatteredpsyche': BattleMoveVisualRecipeId.sdkPsychic,
    'bloomdoom': BattleMoveVisualRecipeId.sdkMagicalLeaf,
    'tectonicrage': BattleMoveVisualRecipeId.sdkEarthquake,
    'subzeroslammer': BattleMoveVisualRecipeId.sdkBlizzard,
    'genesissupernova': BattleMoveVisualRecipeId.sdkPsychoBoost,
    'lightthatburnsthesky': BattleMoveVisualRecipeId.sdkFireBlast,
    'maliciousmoonsault': BattleMoveVisualRecipeId.sdkBodySlam,
    'menacingmoonrazemaelstrom': BattleMoveVisualRecipeId.sdkHex,
    'mindblown': BattleMoveVisualRecipeId.sdkExplosion,
    'gigavolthavoc': BattleMoveVisualRecipeId.sdkThunderbolt,
    's10000000voltthunderbolt': BattleMoveVisualRecipeId.sdkThunderbolt,
    'alloutpummeling': BattleMoveVisualRecipeId.sdkCloseCombat,
    'infernooverdrive': BattleMoveVisualRecipeId.sdkFireBlast,
    'supersonicskystrike': BattleMoveVisualRecipeId.sdkHurricane,
    'aciddownpour': BattleMoveVisualRecipeId.sdkSludgeBomb,
    'continentalcrush': BattleMoveVisualRecipeId.sdkRockSlide,
    'corkscrewcrash': BattleMoveVisualRecipeId.sdkSmartStrike,
    'extremeevoboost': BattleMoveVisualRecipeId.sdkQuiverDance,
    'stockpile': BattleMoveVisualRecipeId.sdkBulkUp,
    'feintattack': BattleMoveVisualRecipeId.sdkNightSlash,
    'steamroller': BattleMoveVisualRecipeId.sdkStomp,
    'spectralthief': BattleMoveVisualRecipeId.sdkHex,
    'memento': BattleMoveVisualRecipeId.sdkPainSplit,
    'esperwing': BattleMoveVisualRecipeId.sdkPsyshock,
    'substitute': BattleMoveVisualRecipeId.sdkProtect,
    'withdraw': BattleMoveVisualRecipeId.sdkReflect,
    'infernalparade': BattleMoveVisualRecipeId.sdkHex,
    'dive': BattleMoveVisualRecipeId.sdkAquaJet,
    'torchsong': BattleMoveVisualRecipeId.sdkFireBlast,
    'iceball': BattleMoveVisualRecipeId.sdkFreezeDry,
    'boltstrike': BattleMoveVisualRecipeId.sdkThunderbolt,
    'electroshot': BattleMoveVisualRecipeId.sdkChargeBeam,
    'anchorshot': BattleMoveVisualRecipeId.sdkSpikeCannon,
    'diamondstorm': BattleMoveVisualRecipeId.sdkPowerGem,
    'twinkletackle': BattleMoveVisualRecipeId.sdkPlayRough,
    'headlongrush': BattleMoveVisualRecipeId.sdkEarthquake,
    'crosschop': BattleMoveVisualRecipeId.sdkKarateChop,
    'aquatail': BattleMoveVisualRecipeId.sdkExactAquaTail,
    'aqua_tail': BattleMoveVisualRecipeId.sdkExactAquaTail,
    'astonish': BattleMoveVisualRecipeId.sdkExactAstonish,
    'leechseed': BattleMoveVisualRecipeId.sdkExactLeechSeed,
    'leech_seed': BattleMoveVisualRecipeId.sdkExactLeechSeed,
    'poisonpowder': BattleMoveVisualRecipeId.sdkExactPoisonPowder,
    'poison_powder': BattleMoveVisualRecipeId.sdkExactPoisonPowder,
    'sleeppowder': BattleMoveVisualRecipeId.sdkExactSleepPowder,
    'sleep_powder': BattleMoveVisualRecipeId.sdkExactSleepPowder,
    'stunspore': BattleMoveVisualRecipeId.sdkExactStunSpore,
    'stun_spore': BattleMoveVisualRecipeId.sdkExactStunSpore,
    'vinewhip': BattleMoveVisualRecipeId.sdkExactVineWhip,
    'vine_whip': BattleMoveVisualRecipeId.sdkExactVineWhip,
    'crushclaw': BattleMoveVisualRecipeId.sdkShadowClaw,
    'falseswipe': BattleMoveVisualRecipeId.sdkCut,
    'metalclaw': BattleMoveVisualRecipeId.sdkShadowClaw,
    'furycutter': BattleMoveVisualRecipeId.sdkXScissor,
    'razorshell': BattleMoveVisualRecipeId.sdkCut,
    'aquacutter': BattleMoveVisualRecipeId.sdkCut,
    'bitterblade': BattleMoveVisualRecipeId.sdkLeafBlade,
    'sacredsword': BattleMoveVisualRecipeId.sdkLeafBlade,
    'secretsword': BattleMoveVisualRecipeId.sdkPsychoCut,
    'mightycleave': BattleMoveVisualRecipeId.sdkLeafBlade,
    'tachyoncutter': BattleMoveVisualRecipeId.sdkXScissor,
  };

  static const Map<String, String> aliasBySDKMoveId = <String, String>{
    'bubble': 'bubblebeam',
    'sparklingaria': 'bubble',
    'electrify': 'thunderwave',
    'nightdaze': 'darkpulse',
    'comeuppance': 'darkpulse',
    'retaliate': 'closecombat',
    'superpower': 'closecombat',
    'submission': 'closecombat',
    'fairywind': 'dazzlinggleam',
    'strangesteam': 'dazzlinggleam',
    'meteorassault': 'aurasphere',
    'workup': 'bulkup',
    'tidyup': 'workup',
    'coaching': 'workup',
    'filletaway': 'workup',
    'waterfall': 'aquajet',
    'surgingstrikes': 'aquajet',
    'bulletpunch': 'machpunch',
    'wringout': 'forcepalm',
    'rollingkick': 'doublekick',
    'triplekick': 'doublekick',
    'suckerpunch': 'quickattack',
    'astonish': 'quickattack',
    'rollout': 'quickattack',
    'boltbeak': 'spark',
    'wideguard': 'quickguard',
    'volttackle': 'wildcharge',
    'zingzap': 'wildcharge',
    'doubleshock': 'wildcharge',
    'terablastelectric': 'thunderbolt',
    'terablastdark': 'darkpulse',
    'terablastpsychic': 'psychic',
    'terablastfairy': 'moonblast',
    'terablastfire': 'flamethrower',
    'terablastice': 'icebeam',
    'heatcrash': 'flareblitz',
    'darkestlariat': 'flareblitz',
    'nuzzle': 'spark',
    'doubleslap': 'doublehit',
    'dualchop': 'doublehit',
    'lashout': 'nightslash',
    'ceaselessedge': 'nightslash',
    'kowtowcleave': 'nightslash',
    'jawlock': 'crunch',
    'hyperfang': 'superfang',
    'highhorsepower': 'stomp',
    'firelash': 'multiattack',
    'mysticalfire': 'flamethrower',
    'firepledge': 'flamethrower',
    'ember': 'flamethrower',
    'incinerate': 'flamethrower',
    'aurorabeam': 'icebeam',
    'appleacid': 'energyball',
    'gravapple': 'energyball',
    'poisonsting': 'poisonjab',
    'poisontail': 'poisonjab',
    'shellsidearmphysical': 'poisonjab',
    'magnitude': 'earthquake',
    'fissure': 'earthquake',
    'landswrath': 'earthquake',
    'rocktomb': 'rockslide',
    'headsmash': 'gigaimpact',
    'headcharge': 'gigaimpact',
    'takedown': 'gigaimpact',
    'dragonrush': 'gigaimpact',
    'lastresort': 'gigaimpact',
    'horndrill': 'gigaimpact',
    'trumpcard': 'gigaimpact',
    'doubleedge': 'gigaimpact',
    'ragingbull': 'gigaimpact',
    'vinewhip': 'powerwhip',
    'grassyglide': 'powerwhip',
    'trailblaze': 'powerwhip',
    'branchpoke': 'vinewhip',
    'aquatail': 'crabhammer',
    'liquidation': 'crabhammer',
    'aurawheel': 'discharge',
    'overdrive': 'discharge',
    'risingvoltage': 'discharge',
    'behemothblade': 'smartstrike',
    'behemothbash': 'smartstrike',
    'hornattack': 'megahorn',
    'lunge': 'megahorn',
    'skittersmack': 'megahorn',
    'breakingswipe': 'dragonclaw',
    'psyblade': 'psychocut',
    'chillingwater': 'waterpulse',
    'snipeshot': 'waterpulse',
    'mountaingale': 'powergem',
    'terablastrock': 'powergem',
    'burningjealousy': 'heatwave',
    'paleowave': 'muddywater',
    'scorchingsands': 'earthpower',
    'terablastground': 'earthpower',
    'terablastbug': 'bugbuzz',
    'chatter': 'hypervoice',
    'echoedvoice': 'hypervoice',
    'relicsong': 'hypervoice',
    'uproar': 'hypervoice',
    'mirrorshot': 'flashcannon',
    'mirrorcoat': 'flashcannon',
    'metalburst': 'flashcannon',
    'terablaststeel': 'flashcannon',
    'dynamaxcannon': 'dragonpulse',
    'terablastdragon': 'dragonpulse',
    'venoshock': 'sludgebomb',
    'shellsidearmspecial': 'sludgebomb',
    'terablastpoison': 'sludgebomb',
    'gastroacid': 'toxic',
    'razorleaf': 'magicalleaf',
    'grasspledge': 'magicalleaf',
    'drumbeating': 'magicalleaf',
    'snaptrap': 'magicalleaf',
    'spiderweb': 'electroweb',
    'stringshot': 'electroweb',
    'toxicthread': 'electroweb',
    'corrosivegas': 'poisongas',
    'pinmissile': 'bulletseed',
    'attackorder': 'bulletseed',
    'fellstinger': 'bulletseed',
    'strugglebug': 'bulletseed',
    'infestation': 'bulletseed',
    'beatup': 'slam',
    'counter': 'slam',
    'payback': 'slam',
    'revenge': 'slam',
    'rockclimb': 'slam',
    'sleeppowder': 'spore',
    'poisonpowder': 'spore',
    'stunspore': 'spore',
    'powder': 'spore',
    'cottonspore': 'spore',
    'magicpowder': 'spore',
    'decorate': 'spore',
    'psychoshift': 'painsplit',
    'helpinghand': 'painsplit',
    'entrainment': 'painsplit',
    'roleplay': 'painsplit',
    'psychup': 'painsplit',
    'destinybond': 'painsplit',
    'reflecttype': 'painsplit',
    'guardsplit': 'skillswap',
    'powersplit': 'skillswap',
    'guardswap': 'skillswap',
    'heartswap': 'skillswap',
    'powerswap': 'skillswap',
    'speedswap': 'skillswap',
    'courtchange': 'skillswap',
    'powershift': 'skillswap',
    'hydrocannon': 'hydropump',
    'terablastwater': 'hydropump',
    'razorwind': 'airslash',
    'terablaststellar': 'dracometeor',
    'gmaxfinale': 'maxstarfall',
    'gmaxsmite': 'maxstarfall',
    'selfdestruct': 'explosion',
    'mindblown': 'explosion',
    'mistyexplosion': 'explosion',
    'drillpeck': 'bravebird',
    'peck': 'bravebird',
    'pluck': 'bravebird',
    'bleakwindstorm': 'hurricane',
    'dragonenergy': 'dragonbreath',
    'futuresight': 'doomdesire',
    'powdersnow': 'icywind',
    'purify': 'weatherball',
    '10000000voltthunderbolt': 's10000000voltthunderbolt',
    'dragondarts': 'dragonbreath',
    'pyroball': 'flameburst',
    'scaleshot': 'clangingscales',
    'terablast': 'scald',
    'terablastgrass': 'seedflare',
    'hydrosteam': 'steameruption',
    'watergun': 'watersport',
    'extrasensory': 'psychic',
    'confusion': 'psychic',
    'maximumpsybreaker': 'psychic',
    'torment': 'swagger',
    'mefirst': 'mimic',
    'conversion2': 'conversion',
    'searingshot': 'shelltrap',
    'flamewheel': 'flamecharge',
    'whirlpool': 'watersport',
    'magikarpsrevenge': 'outrage',
    'constrict': 'bind',
    'wrap': 'bind',
    'lowsweep': 'lowkick',
    'wakeupslap': 'smellingsalts',
    'frustration': 'thrash',
    'rage': 'thrash',
    'frenzyplant': 'leafstorm',
    'holdhands': 'painsplit',
    'lunardance': 'moonlight',
    'crushgrip': 'quash',
    'bonerush': 'boneclub',
    'dragonrage': 'dragonbreath',
    'camouflage': 'tailglow',
    'telekinesis': 'kinesis',
    'foulplay': 'psyshock',
    'miracleeye': 'mindreader',
    'glare': 'meanlook',
    'grudge': 'meanlook',
    'scaryface': 'meanlook',
    'disable': 'meanlook',
    'captivate': 'attract',
    'flatter': 'attract',
    'armthrust': 'smellingsalts',
    'shadowstrike': 'shadowforce',
    'phantomforce': 'shadowforce',
    'nightmare': 'nightshade',
    'dreameater': 'drainingkiss',
    'sweetkiss': 'lovelykiss',
    'mudsport': 'mudbomb',
    'barrage': 'magnetbomb',
    'eggbomb': 'magnetbomb',
    'spitup': 'magnetbomb',
    'aromaticmist': 'mistyterrain',
    'sweetscent': 'mistyterrain',
    'psychicterrain': 'mistyterrain',
    'iondeluge': 'electricterrain',
    'magneticflux': 'electricterrain',
    'rototiller': 'electricterrain',
    'imprison': 'embargo',
    'synthesis': 'recover',
    'floralhealing': 'healpulse',
    'amnesia': 'rest',
    'slackoff': 'rest',
    'secretpower': 'technoblast',
    'naturalgift': 'technoblast',
    'maliciousmoonsault': 'pulverizingpancake',
    'genesissupernova': 'psychoboost',
    'menacingmoonrazemaelstrom': 'moongeistbeam',
    'lightthatburnsthesky': 'fusionflare',
    'maxflutterby': 'savagespinout',
    'gmaxbefuddle': 'savagespinout',
    'maxdarkness': 'maliciousmoonsault',
    'gmaxsnooze': 'maliciousmoonsault',
    'maxwyrmwind': 'devastatingdrake',
    'gmaxdepletion': 'devastatingdrake',
    'maxlightning': 'gigavolthavoc',
    'maxknuckle': 'alloutpummeling',
    'gmaxoneblow': 'alloutpummeling',
    'gmaxrapidflow': 'alloutpummeling',
    'maxflare': 'infernooverdrive',
    'gmaxcentiferno': 'infernooverdrive',
    'gmaxfireball': 'infernooverdrive',
    'maxairstream': 'supersonicskystrike',
    'maxphantasm': 'neverendingnightmare',
    'maxovergrowth': 'bloomdoom',
    'gmaxvinelash': 'bloomdoom',
    'gmaxdrumsolo': 'bloomdoom',
    'maxquake': 'tectonicrage',
    'gmaxsandblast': 'tectonicrage',
    'maxhailstorm': 'subzeroslammer',
    'gmaxresonance': 'subzeroslammer',
    'maxstrike': 'breakneckblitz',
    'gmaxcuddle': 'breakneckblitz',
    'gmaxreplenish': 'breakneckblitz',
    'maxooze': 'aciddownpour',
    'gmaxmalodor': 'aciddownpour',
    'maxmindstorm': 'shatteredpsyche',
    'gmaxgravitas': 'shatteredpsyche',
    'maxrockfall': 'continentalcrush',
    'maxsteelspike': 'corkscrewcrash',
    'aciddownpour2': 'aciddownpour',
    'alloutpummeling2': 'alloutpummeling',
    'blackholeeclipse2': 'blackholeeclipse',
    'bloomdoom2': 'bloomdoom',
    'breakneckblitz2': 'breakneckblitz',
    'continentalcrush2': 'continentalcrush',
    'corkscrewcrash2': 'corkscrewcrash',
    'devastatingdrake2': 'devastatingdrake',
    'gigavolthavoc2': 'gigavolthavoc',
    'hydrovortex2': 'hydrovortex',
    'infernooverdrive2': 'infernooverdrive',
    'neverendingnightmare2': 'neverendingnightmare',
    'savagespinout2': 'savagespinout',
    'shatteredpsyche2': 'shatteredpsyche',
    'subzeroslammer2': 'subzeroslammer',
    'supersonicskystrike2': 'supersonicskystrike',
    'tectonicrage2': 'tectonicrage',
    'twinkletackle2': 'twinkletackle',
    'stuffcheeks': 'stockpile',
    'noretreat': 'stockpile',
    'tarshot': 'mudbomb',
    'teatime': 'healbell',
    'octolock': 'bind',
    'clangoroussoul': 'extremeevoboost',
    'obstruct': 'kingsshield',
    'maxguard': 'banefulbunker',
    'falsesurrender': 'feintattack',
    'poltergeist': 'neverendingnightmare',
    'steelroller': 'steamroller',
    'eeriespell': 'psyshock',
    'bittermalice': 'spectralthief',
    'glaiverush': 'outrage',
    'lastrespects': 'memento',
    'luminacrash': 'esperwing',
    'pounce': 'bodyslam',
    'shedtail': 'substitute',
    'shelter': 'withdraw',
    'terablastfighting': 'focusblast',
    'terablastghost': 'infernalparade',
    'terablastnormal': 'technoblast',
    'tripledive': 'dive',
    'polarflare': 'torchsong',
    'mistball': 'iceball',
    'fusionbolt': 'boltstrike',
    'wildboltstorm': 'boltstrike',
    'seedbomb': 'bulletseed',
    'syrupbomb': 'sludgebomb',
  };

  static const Set<String> exactRubySDKMoveIds = <String>{
    'acidarmor',
    'acrobatics',
    'aerialace',
    'airslash',
    'aquaring',
    'aquatail',
    'assurance',
    'astonish',
    'avalanche',
    'karatechop',
    'leechseed',
    'poisonpowder',
    'recover',
    'sleeppowder',
    'stunspore',
    'tailwhip',
    'thunderwave',
    'vinewhip',
  };

  static const Set<String> adaptedSDKMoveIds = <String>{
    'aciddownpour',
    'aciddownpour2',
    'alloutpummeling',
    'alloutpummeling2',
    'blackholeeclipse',
    'blackholeeclipse2',
    'bloomdoom',
    'bloomdoom2',
    'breakneckblitz',
    'breakneckblitz2',
    'catastropika',
    'clangoroussoulblaze',
    'continentalcrush',
    'continentalcrush2',
    'corkscrewcrash',
    'corkscrewcrash2',
    'devastatingdrake',
    'devastatingdrake2',
    'extremeevoboost',
    'genesissupernova',
    'gigavolthavoc',
    'gigavolthavoc2',
    'guardianofalola',
    'hydrovortex',
    'hydrovortex2',
    'infernooverdrive',
    'infernooverdrive2',
    'letssnuggleforever',
    'lightthatburnsthesky',
    'maliciousmoonsault',
    'menacingmoonrazemaelstrom',
    'mindblown',
    'neverendingnightmare',
    'neverendingnightmare2',
    'oceanicoperetta',
    'photongeyser',
    'plasmafists',
    'pulverizingpancake',
    'savagespinout',
    'savagespinout2',
    'searingsunrazesmash',
    'shatteredpsyche',
    'shatteredpsyche2',
    'sinisterarrowraid',
    'soulstealing7starstrike',
    'splinteredstormshards',
    'stokedsparksurfer',
    'subzeroslammer',
    'subzeroslammer2',
    'supersonicskystrike',
    'supersonicskystrike2',
    'tectonicrage',
    'tectonicrage2',
    'twinkletackle',
    'twinkletackle2',
    's10000000voltthunderbolt',
    '10000000voltthunderbolt',
  };

  static const Set<String> explicitNoAnimationSDKIds = <String>{};

  static String? normalizeSDKMoveId(String? value) {
    if (value == null) {
      return null;
    }
    final normalized = value.trim().toLowerCase().replaceAll(
          RegExp(r'[^a-z0-9]+'),
          '',
        );
    return normalized.isEmpty ? null : normalized;
  }
}
