enum BattleMoveVisualRecipeId {
  genericContactLight,
  genericContactHeavy,
  genericPunch,
  genericBite,
  genericSlash,
  genericProjectileNeutral,
  genericProjectilePulse,
  genericProjectileFire,
  genericProjectileWater,
  genericProjectileElectric,
  genericProjectileGhost,
  genericProjectileDark,
  genericProjectileFairy,
  genericProjectileIce,
  genericBuffSelf,
  genericDebuffTarget,
  genericStatusPulse,
  protectBarrier,
  setStealthRock,
  setSpikes,
  weatherRain,
  weatherSandstorm,
  pseudoWeatherTrickRoom,
  chargeUp,
  rechargePause,
  showdownTackle,
  showdownScratch,
  showdownQuickAttack,
  showdownSlash,
  showdownAerialAce,
  showdownCloseCombat,
  showdownThunderbolt,
  showdownChargeBeam,
  showdownHiddenPower,
  showdownDoomDesire,
  showdownSeedFlare,
  showdownIcyWind,
  showdownWeatherBall,
  showdownScald,
  showdownTriAttack,
  showdownClangingScales,
  showdownFlameBurst,
  showdownSteamEruption,
  showdownWaterSport,
  showdownShadowBall,
  showdownDarkPulse,
  showdownAuraSphere,
  showdownBubbleBeam,
  showdownFireBlast,
  showdownBlizzard,
  showdownDazzlingGleam,
  showdownCalmMind,
  showdownSwordsDance,
  showdownAgility,
  showdownBulkUp,
  showdownCharm,
  showdownConfuseRay,
  showdownGrowl,
  showdownTaunt,
  showdownInstruct,
  showdownQuash,
  showdownSwagger,
  showdownEncore,
  showdownBabyDollEyes,
  showdownThunderWave,
  showdownProtect,
  showdownBurningBulwark,
  showdownBanefulBunker,
  showdownReflect,
  showdownLightScreen,
  showdownMist,
  showdownAuroraVeil,
  showdownSafeguard,
  showdownQuickGuard,
  showdownWideGuard,
  showdownTailwind,
  showdownRainDance,
  showdownSandstorm,
  showdownTrickRoom,
  showdownStealthRock,
  showdownSpikes,
  showdownAquaJet,
  showdownExtremeSpeed,
  showdownMachPunch,
  showdownShadowPunch,
  showdownFocusPunch,
  showdownDrainPunch,
  showdownDynamicPunch,
  showdownCometPunch,
  showdownMegaPunch,
  showdownPowerUpPunch,
  showdownDizzyPunch,
  showdownJetPunch,
  showdownFirePunch,
  showdownIcePunch,
  showdownThunderPunch,
  showdownBlazeKick,
  showdownThunderousKick,
  showdownTropKick,
  showdownDoubleKick,
  showdownDualWingBeat,
  showdownBoneMerang,
  showdownBodySlam,
  showdownHighJumpKick,
  showdownKarateChop,
  showdownDrillRun,
  showdownGunkShot,
  showdownMudShot,
  showdownElectroBall,
  showdownRockBlast,
  showdownSpark,
  showdownWildCharge,
  showdownFlareBlitz,
  showdownAccelerock,
  showdownWickedBlow,
  showdownDoubleHit,
  showdownCrunch,
  showdownFlamethrower,
  showdownIceBeam,
  showdownPsychic,
  showdownMoonBlast,
  showdownPoisonJab,
  showdownEarthquake,
  showdownEnergyBall,
  showdownRockSlide,
  showdownNightSlash,
  showdownGigaImpact,
  showdownPowerWhip,
  showdownWoodHammer,
  showdownIvyCudgel,
  showdownIvyCudgelWater,
  showdownIvyCudgelFire,
  showdownIvyCudgelRock,
  showdownCut,
  showdownShadowClaw,
  showdownMultiAttack,
  showdownBite,
  showdownSuperFang,
  showdownBugBite,
  showdownPsychicFangs,
  showdownIronHead,
  showdownHeadbutt,
  showdownStomp,
  showdownHammerArm,
  showdownIceHammer,
  showdownSkyUppercut,
  showdownNeedleArm,
  showdownRockSmash,
  showdownCrabHammer,
  showdownDischarge,
  showdownSmartStrike,
  showdownMegaHorn,
  showdownDragonClaw,
  showdownPsychoCut,
  showdownWaterPulse,
  showdownPowerGem,
  showdownHeatWave,
  showdownMuddyWater,
  showdownEarthPower,
  showdownBugBuzz,
  showdownHyperVoice,
  showdownFlashCannon,
  showdownDragonPulse,
  showdownSludgeBomb,
  showdownMagicalLeaf,
  showdownElectroweb,
  showdownBulletSeed,
  showdownSlam,
  showdownSpore,
  showdownPainSplit,
  showdownSkillSwap,
  showdownPlayRough,
  showdownSurf,
  showdownHydroPump,
  showdownLeafBlade,
  showdownXScissor,
  showdownFireFang,
  showdownIceFang,
  showdownThunderFang,
  showdownAirSlash,
  showdownDracoMeteor,
  showdownQuiverDance,
  showdownVictoryDance,
  showdownDragonDance,
  showdownFeatherDance,
  showdownFocusBlast,
  showdownSpinAttack,
  showdownVoltSwitch,
  showdownShockWave,
  showdownExplosion,
  showdownPopulationBomb,
  showdownAirCutter,
  showdownHurricane,
  showdownSunnyDay,
  showdownHail,
  showdownElectricTerrain,
  showdownGrassyTerrain,
  showdownMistyTerrain,
  showdownFollowMe,
  showdownKinesis,
  showdownSolarBeam,
  showdownThunder,
  showdownStoredPower,
  showdownPsychoBoost,
  showdownPsyshock,
  showdownHex,
  showdownWillOWisp,
  showdownLifeDew,
  showdownAromatherapy,
  showdownRest,
  showdownIngrain,
  showdownMorningSun,
  showdownShoreUp,
  showdownDrain,
  showdownLeechLife,
  showdownHornLeech,
  showdownParabolicCharge,
  showdownDrainingKiss,
  showdownOblivionWing,
  showdownLeechSeed,
  showdownWhirlwind,
  showdownFreezeDry,
  showdownMagmaStorm,
  showdownOriginPulse,
  showdownPsybeam,
  showdownAeroblast,
  showdownRoarOfTime,
  showdownRevelationDance,
  showdownHyperBeam,
  showdownSignalBeam,
  showdownFleurCannon,
  showdownArmorCannon,
  showdownSteelBeam,
  showdownBeakBlast,
  showdownTwinBeam,
  showdownSpikeCannon,
  showdownWaterShuriken,
  showdownTerastarStorm,
  showdownMeteorMash,
  showdownToxic,
  showdownToxicSpikes,
  showdownPoisonGas,
  showdownSmog,
  showdownClearSmog,
  showdownPoisonFang,
  showdownCrossPoison,
  showdownDireClaw,
  showdownSplash,
  showdownCelebrate,
  showdownOrderUp,
  showdownHeartStamp,
  showdownMatchaGotcha,
  showdownPresent,
  showdownPayDay,
  noAnimation,
}

final class BattleMoveVisualCatalog {
  static const Map<String, BattleMoveVisualRecipeId> recipeByShowdownMoveId =
      <String, BattleMoveVisualRecipeId>{
    'tackle': BattleMoveVisualRecipeId.showdownTackle,
    'scratch': BattleMoveVisualRecipeId.showdownScratch,
    'quickattack': BattleMoveVisualRecipeId.showdownQuickAttack,
    'slash': BattleMoveVisualRecipeId.showdownSlash,
    'aerialace': BattleMoveVisualRecipeId.showdownAerialAce,
    'closecombat': BattleMoveVisualRecipeId.showdownCloseCombat,
    'thunderbolt': BattleMoveVisualRecipeId.showdownThunderbolt,
    'chargebeam': BattleMoveVisualRecipeId.showdownChargeBeam,
    'doomdesire': BattleMoveVisualRecipeId.showdownDoomDesire,
    'seedflare': BattleMoveVisualRecipeId.showdownSeedFlare,
    'icywind': BattleMoveVisualRecipeId.showdownIcyWind,
    'weatherball': BattleMoveVisualRecipeId.showdownWeatherBall,
    'scald': BattleMoveVisualRecipeId.showdownScald,
    'triattack': BattleMoveVisualRecipeId.showdownTriAttack,
    'clangingscales': BattleMoveVisualRecipeId.showdownClangingScales,
    'flameburst': BattleMoveVisualRecipeId.showdownFlameBurst,
    'steameruption': BattleMoveVisualRecipeId.showdownSteamEruption,
    'watersport': BattleMoveVisualRecipeId.showdownWaterSport,
    'shadowball': BattleMoveVisualRecipeId.showdownShadowBall,
    'darkpulse': BattleMoveVisualRecipeId.showdownDarkPulse,
    'aurasphere': BattleMoveVisualRecipeId.showdownAuraSphere,
    'bubblebeam': BattleMoveVisualRecipeId.showdownBubbleBeam,
    'fireblast': BattleMoveVisualRecipeId.showdownFireBlast,
    'blizzard': BattleMoveVisualRecipeId.showdownBlizzard,
    'dazzlinggleam': BattleMoveVisualRecipeId.showdownDazzlingGleam,
    'growl': BattleMoveVisualRecipeId.showdownGrowl,
    'thunderwave': BattleMoveVisualRecipeId.showdownThunderWave,
    'calmmind': BattleMoveVisualRecipeId.showdownCalmMind,
    'swordsdance': BattleMoveVisualRecipeId.showdownSwordsDance,
    'agility': BattleMoveVisualRecipeId.showdownAgility,
    'bulkup': BattleMoveVisualRecipeId.showdownBulkUp,
    'focusenergy': BattleMoveVisualRecipeId.showdownBulkUp,
    'harden': BattleMoveVisualRecipeId.showdownReflect,
    'defensecurl': BattleMoveVisualRecipeId.showdownReflect,
    'irondefense': BattleMoveVisualRecipeId.showdownReflect,
    'cottonguard': BattleMoveVisualRecipeId.showdownReflect,
    'defendorder': BattleMoveVisualRecipeId.showdownReflect,
    'barrier': BattleMoveVisualRecipeId.showdownReflect,
    'flowershield': BattleMoveVisualRecipeId.showdownReflect,
    'howl': BattleMoveVisualRecipeId.showdownBulkUp,
    'meditate': BattleMoveVisualRecipeId.showdownBulkUp,
    'laserfocus': BattleMoveVisualRecipeId.showdownBulkUp,
    'sharpen': BattleMoveVisualRecipeId.showdownSwordsDance,
    'honeclaws': BattleMoveVisualRecipeId.showdownSwordsDance,
    'charge': BattleMoveVisualRecipeId.showdownCalmMind,
    'luckychant': BattleMoveVisualRecipeId.showdownCalmMind,
    'growth': BattleMoveVisualRecipeId.showdownCalmMind,
    'cosmicpower': BattleMoveVisualRecipeId.showdownCalmMind,
    'chargeup': BattleMoveVisualRecipeId.showdownCalmMind,
    'rockpolish': BattleMoveVisualRecipeId.showdownAgility,
    'autotomize': BattleMoveVisualRecipeId.showdownAgility,
    'shiftgear': BattleMoveVisualRecipeId.showdownAgility,
    'magnetrise': BattleMoveVisualRecipeId.showdownAgility,
    'minimize': BattleMoveVisualRecipeId.showdownAgility,
    'gearup': BattleMoveVisualRecipeId.showdownAgility,
    'tailglow': BattleMoveVisualRecipeId.showdownQuiverDance,
    'geomancy': BattleMoveVisualRecipeId.showdownQuiverDance,
    'charm': BattleMoveVisualRecipeId.showdownCharm,
    'confuseray': BattleMoveVisualRecipeId.showdownConfuseRay,
    'stealthrock': BattleMoveVisualRecipeId.showdownStealthRock,
    'spikes': BattleMoveVisualRecipeId.showdownSpikes,
    'raindance': BattleMoveVisualRecipeId.showdownRainDance,
    'sandstorm': BattleMoveVisualRecipeId.showdownSandstorm,
    'trickroom': BattleMoveVisualRecipeId.showdownTrickRoom,
    'protect': BattleMoveVisualRecipeId.showdownProtect,
    'detect': BattleMoveVisualRecipeId.showdownProtect,
    'kingsshield': BattleMoveVisualRecipeId.showdownProtect,
    'spikyshield': BattleMoveVisualRecipeId.showdownProtect,
    'endure': BattleMoveVisualRecipeId.showdownProtect,
    'magiccoat': BattleMoveVisualRecipeId.showdownProtect,
    'craftyshield': BattleMoveVisualRecipeId.showdownQuickGuard,
    'matblock': BattleMoveVisualRecipeId.showdownQuickGuard,
    'burningbulwark': BattleMoveVisualRecipeId.showdownBurningBulwark,
    'banefulbunker': BattleMoveVisualRecipeId.showdownBanefulBunker,
    'reflect': BattleMoveVisualRecipeId.showdownReflect,
    'lightscreen': BattleMoveVisualRecipeId.showdownLightScreen,
    'mist': BattleMoveVisualRecipeId.showdownMist,
    'auroraveil': BattleMoveVisualRecipeId.showdownAuroraVeil,
    'safeguard': BattleMoveVisualRecipeId.showdownSafeguard,
    'quickguard': BattleMoveVisualRecipeId.showdownQuickGuard,
    'wideguard': BattleMoveVisualRecipeId.showdownWideGuard,
    'tailwind': BattleMoveVisualRecipeId.showdownTailwind,
    'aquajet': BattleMoveVisualRecipeId.showdownAquaJet,
    'extremespeed': BattleMoveVisualRecipeId.showdownExtremeSpeed,
    'machpunch': BattleMoveVisualRecipeId.showdownMachPunch,
    'shadowpunch': BattleMoveVisualRecipeId.showdownShadowPunch,
    'focuspunch': BattleMoveVisualRecipeId.showdownFocusPunch,
    'drainpunch': BattleMoveVisualRecipeId.showdownDrainPunch,
    'dynamicpunch': BattleMoveVisualRecipeId.showdownDynamicPunch,
    'cometpunch': BattleMoveVisualRecipeId.showdownCometPunch,
    'megapunch': BattleMoveVisualRecipeId.showdownMegaPunch,
    'poweruppunch': BattleMoveVisualRecipeId.showdownPowerUpPunch,
    'dizzypunch': BattleMoveVisualRecipeId.showdownDizzyPunch,
    'jetpunch': BattleMoveVisualRecipeId.showdownJetPunch,
    'firepunch': BattleMoveVisualRecipeId.showdownFirePunch,
    'icepunch': BattleMoveVisualRecipeId.showdownIcePunch,
    'thunderpunch': BattleMoveVisualRecipeId.showdownThunderPunch,
    'blazekick': BattleMoveVisualRecipeId.showdownBlazeKick,
    'thunderouskick': BattleMoveVisualRecipeId.showdownThunderousKick,
    'tropkick': BattleMoveVisualRecipeId.showdownTropKick,
    'doublekick': BattleMoveVisualRecipeId.showdownDoubleKick,
    'bodyslam': BattleMoveVisualRecipeId.showdownBodySlam,
    'heavyslam': BattleMoveVisualRecipeId.showdownBodySlam,
    'bodypress': BattleMoveVisualRecipeId.showdownBodySlam,
    'dragonhammer': BattleMoveVisualRecipeId.showdownBodySlam,
    'jumpkick': BattleMoveVisualRecipeId.showdownHighJumpKick,
    'highjumpkick': BattleMoveVisualRecipeId.showdownHighJumpKick,
    'lowkick': BattleMoveVisualRecipeId.showdownHighJumpKick,
    'circlethrow': BattleMoveVisualRecipeId.showdownHighJumpKick,
    'axekick': BattleMoveVisualRecipeId.showdownHighJumpKick,
    'megakick': BattleMoveVisualRecipeId.showdownHighJumpKick,
    'karatechop': BattleMoveVisualRecipeId.showdownKarateChop,
    'forcepalm': BattleMoveVisualRecipeId.showdownKarateChop,
    'brickbreak': BattleMoveVisualRecipeId.showdownKarateChop,
    'throatchop': BattleMoveVisualRecipeId.showdownKarateChop,
    'stormthrow': BattleMoveVisualRecipeId.showdownKarateChop,
    'vitalthrow': BattleMoveVisualRecipeId.showdownKarateChop,
    'drillrun': BattleMoveVisualRecipeId.showdownDrillRun,
    'hyperdrill': BattleMoveVisualRecipeId.showdownDrillRun,
    'gunkshot': BattleMoveVisualRecipeId.showdownGunkShot,
    'sludge': BattleMoveVisualRecipeId.showdownGunkShot,
    'acid': BattleMoveVisualRecipeId.showdownSmog,
    'acidspray': BattleMoveVisualRecipeId.showdownSmog,
    'belch': BattleMoveVisualRecipeId.showdownGunkShot,
    'venomdrench': BattleMoveVisualRecipeId.showdownSmog,
    'mudshot': BattleMoveVisualRecipeId.showdownMudShot,
    'mudbomb': BattleMoveVisualRecipeId.showdownMudShot,
    'mudslap': BattleMoveVisualRecipeId.showdownMudShot,
    'electroball': BattleMoveVisualRecipeId.showdownElectroBall,
    'thundershock': BattleMoveVisualRecipeId.showdownElectroBall,
    'rockblast': BattleMoveVisualRecipeId.showdownRockBlast,
    'smackdown': BattleMoveVisualRecipeId.showdownRockBlast,
    'dualwingbeat': BattleMoveVisualRecipeId.showdownDualWingBeat,
    'bonemerang': BattleMoveVisualRecipeId.showdownBoneMerang,
    'spark': BattleMoveVisualRecipeId.showdownSpark,
    'wildcharge': BattleMoveVisualRecipeId.showdownWildCharge,
    'flareblitz': BattleMoveVisualRecipeId.showdownFlareBlitz,
    'accelerock': BattleMoveVisualRecipeId.showdownAccelerock,
    'wickedblow': BattleMoveVisualRecipeId.showdownWickedBlow,
    'doublehit': BattleMoveVisualRecipeId.showdownDoubleHit,
    'crunch': BattleMoveVisualRecipeId.showdownCrunch,
    'flamethrower': BattleMoveVisualRecipeId.showdownFlamethrower,
    'icebeam': BattleMoveVisualRecipeId.showdownIceBeam,
    'psychic': BattleMoveVisualRecipeId.showdownPsychic,
    'moonblast': BattleMoveVisualRecipeId.showdownMoonBlast,
    'poisonjab': BattleMoveVisualRecipeId.showdownPoisonJab,
    'earthquake': BattleMoveVisualRecipeId.showdownEarthquake,
    'energyball': BattleMoveVisualRecipeId.showdownEnergyBall,
    'rockslide': BattleMoveVisualRecipeId.showdownRockSlide,
    'nightslash': BattleMoveVisualRecipeId.showdownNightSlash,
    'gigaimpact': BattleMoveVisualRecipeId.showdownGigaImpact,
    'powerwhip': BattleMoveVisualRecipeId.showdownPowerWhip,
    'woodhammer': BattleMoveVisualRecipeId.showdownWoodHammer,
    'ivycudgel': BattleMoveVisualRecipeId.showdownIvyCudgel,
    'ivycudgelwater': BattleMoveVisualRecipeId.showdownIvyCudgelWater,
    'ivycudgelfire': BattleMoveVisualRecipeId.showdownIvyCudgelFire,
    'ivycudgelrock': BattleMoveVisualRecipeId.showdownIvyCudgelRock,
    'cut': BattleMoveVisualRecipeId.showdownCut,
    'shadowclaw': BattleMoveVisualRecipeId.showdownShadowClaw,
    'multiattack': BattleMoveVisualRecipeId.showdownMultiAttack,
    'bite': BattleMoveVisualRecipeId.showdownBite,
    'superfang': BattleMoveVisualRecipeId.showdownSuperFang,
    'bugbite': BattleMoveVisualRecipeId.showdownBugBite,
    'psychicfangs': BattleMoveVisualRecipeId.showdownPsychicFangs,
    'ironhead': BattleMoveVisualRecipeId.showdownIronHead,
    'headbutt': BattleMoveVisualRecipeId.showdownHeadbutt,
    'stomp': BattleMoveVisualRecipeId.showdownStomp,
    'hammerarm': BattleMoveVisualRecipeId.showdownHammerArm,
    'icehammer': BattleMoveVisualRecipeId.showdownIceHammer,
    'skyuppercut': BattleMoveVisualRecipeId.showdownSkyUppercut,
    'needlearm': BattleMoveVisualRecipeId.showdownNeedleArm,
    'rocksmash': BattleMoveVisualRecipeId.showdownRockSmash,
    'highhorsepower': BattleMoveVisualRecipeId.showdownStomp,
    'hyperfang': BattleMoveVisualRecipeId.showdownSuperFang,
    'firelash': BattleMoveVisualRecipeId.showdownMultiAttack,
    'crabhammer': BattleMoveVisualRecipeId.showdownCrabHammer,
    'discharge': BattleMoveVisualRecipeId.showdownDischarge,
    'smartstrike': BattleMoveVisualRecipeId.showdownSmartStrike,
    'megahorn': BattleMoveVisualRecipeId.showdownMegaHorn,
    'dragonclaw': BattleMoveVisualRecipeId.showdownDragonClaw,
    'psychocut': BattleMoveVisualRecipeId.showdownPsychoCut,
    'waterpulse': BattleMoveVisualRecipeId.showdownWaterPulse,
    'powergem': BattleMoveVisualRecipeId.showdownPowerGem,
    'heatwave': BattleMoveVisualRecipeId.showdownHeatWave,
    'muddywater': BattleMoveVisualRecipeId.showdownMuddyWater,
    'earthpower': BattleMoveVisualRecipeId.showdownEarthPower,
    'bugbuzz': BattleMoveVisualRecipeId.showdownBugBuzz,
    'hypervoice': BattleMoveVisualRecipeId.showdownHyperVoice,
    'hyperbeam': BattleMoveVisualRecipeId.showdownHyperBeam,
    'flashcannon': BattleMoveVisualRecipeId.showdownFlashCannon,
    'signalbeam': BattleMoveVisualRecipeId.showdownSignalBeam,
    'dragonpulse': BattleMoveVisualRecipeId.showdownDragonPulse,
    'sludgebomb': BattleMoveVisualRecipeId.showdownSludgeBomb,
    'magicalleaf': BattleMoveVisualRecipeId.showdownMagicalLeaf,
    'electroweb': BattleMoveVisualRecipeId.showdownElectroweb,
    'bulletseed': BattleMoveVisualRecipeId.showdownBulletSeed,
    'slam': BattleMoveVisualRecipeId.showdownSlam,
    'spore': BattleMoveVisualRecipeId.showdownSpore,
    'painsplit': BattleMoveVisualRecipeId.showdownPainSplit,
    'skillswap': BattleMoveVisualRecipeId.showdownSkillSwap,
    'playrough': BattleMoveVisualRecipeId.showdownPlayRough,
    'surf': BattleMoveVisualRecipeId.showdownSurf,
    'hydropump': BattleMoveVisualRecipeId.showdownHydroPump,
    'leafblade': BattleMoveVisualRecipeId.showdownLeafBlade,
    'xscissor': BattleMoveVisualRecipeId.showdownXScissor,
    'firefang': BattleMoveVisualRecipeId.showdownFireFang,
    'icefang': BattleMoveVisualRecipeId.showdownIceFang,
    'thunderfang': BattleMoveVisualRecipeId.showdownThunderFang,
    'airslash': BattleMoveVisualRecipeId.showdownAirSlash,
    'dracometeor': BattleMoveVisualRecipeId.showdownDracoMeteor,
    'fleurcannon': BattleMoveVisualRecipeId.showdownFleurCannon,
    'armorcannon': BattleMoveVisualRecipeId.showdownArmorCannon,
    'steelbeam': BattleMoveVisualRecipeId.showdownSteelBeam,
    'beakblast': BattleMoveVisualRecipeId.showdownBeakBlast,
    'twinbeam': BattleMoveVisualRecipeId.showdownTwinBeam,
    'spikecannon': BattleMoveVisualRecipeId.showdownSpikeCannon,
    'terastarstorm': BattleMoveVisualRecipeId.showdownTerastarStorm,
    'meteormash': BattleMoveVisualRecipeId.showdownMeteorMash,
    'toxic': BattleMoveVisualRecipeId.showdownToxic,
    'toxicspikes': BattleMoveVisualRecipeId.showdownToxicSpikes,
    'poisongas': BattleMoveVisualRecipeId.showdownPoisonGas,
    'smog': BattleMoveVisualRecipeId.showdownSmog,
    'clearsmog': BattleMoveVisualRecipeId.showdownClearSmog,
    'poisonfang': BattleMoveVisualRecipeId.showdownPoisonFang,
    'crosspoison': BattleMoveVisualRecipeId.showdownCrossPoison,
    'direclaw': BattleMoveVisualRecipeId.showdownDireClaw,
    'quiverdance': BattleMoveVisualRecipeId.showdownQuiverDance,
    'victorydance': BattleMoveVisualRecipeId.showdownVictoryDance,
    'dragondance': BattleMoveVisualRecipeId.showdownDragonDance,
    'featherdance': BattleMoveVisualRecipeId.showdownFeatherDance,
    'bravebird': BattleMoveVisualRecipeId.showdownAerialAce,
    'acrobatics': BattleMoveVisualRecipeId.showdownAerialAce,
    'flyingpress': BattleMoveVisualRecipeId.showdownAerialAce,
    'steelwing': BattleMoveVisualRecipeId.showdownAerialAce,
    'wingattack': BattleMoveVisualRecipeId.showdownAerialAce,
    'fly': BattleMoveVisualRecipeId.showdownAerialAce,
    'skyattack': BattleMoveVisualRecipeId.showdownAerialAce,
    'dragonbreath': BattleMoveVisualRecipeId.showdownDragonPulse,
    'focusblast': BattleMoveVisualRecipeId.showdownFocusBlast,
    'uturn': BattleMoveVisualRecipeId.showdownSpinAttack,
    'rapidspin': BattleMoveVisualRecipeId.showdownSpinAttack,
    'gyroball': BattleMoveVisualRecipeId.showdownSpinAttack,
    'flipturn': BattleMoveVisualRecipeId.showdownSpinAttack,
    'mortalspin': BattleMoveVisualRecipeId.showdownSpinAttack,
    'icespinner': BattleMoveVisualRecipeId.showdownSpinAttack,
    'voltswitch': BattleMoveVisualRecipeId.showdownVoltSwitch,
    'shockwave': BattleMoveVisualRecipeId.showdownShockWave,
    'explosion': BattleMoveVisualRecipeId.showdownExplosion,
    'populationbomb': BattleMoveVisualRecipeId.showdownPopulationBomb,
    'aircutter': BattleMoveVisualRecipeId.showdownAirCutter,
    'hurricane': BattleMoveVisualRecipeId.showdownHurricane,
    'sunnyday': BattleMoveVisualRecipeId.showdownSunnyDay,
    'hail': BattleMoveVisualRecipeId.showdownHail,
    'snowscape': BattleMoveVisualRecipeId.showdownHail,
    'chillyreception': BattleMoveVisualRecipeId.showdownHail,
    'magicroom': BattleMoveVisualRecipeId.showdownTrickRoom,
    'wonderroom': BattleMoveVisualRecipeId.showdownTrickRoom,
    'afteryou': BattleMoveVisualRecipeId.showdownAgility,
    'babydolleyes': BattleMoveVisualRecipeId.showdownBabyDollEyes,
    'faketears': BattleMoveVisualRecipeId.showdownGrowl,
    'tearfullook': BattleMoveVisualRecipeId.showdownGrowl,
    'foresight': BattleMoveVisualRecipeId.showdownKinesis,
    'sketch': BattleMoveVisualRecipeId.showdownSkillSwap,
    'doodle': BattleMoveVisualRecipeId.showdownSkillSwap,
    'odorsleuth': BattleMoveVisualRecipeId.showdownKinesis,
    'playnice': BattleMoveVisualRecipeId.showdownGrowl,
    'tailwhip': BattleMoveVisualRecipeId.showdownGrowl,
    'leer': BattleMoveVisualRecipeId.showdownGrowl,
    'snatch': BattleMoveVisualRecipeId.showdownFollowMe,
    'electricterrain': BattleMoveVisualRecipeId.showdownElectricTerrain,
    'grassyterrain': BattleMoveVisualRecipeId.showdownGrassyTerrain,
    'mistyterrain': BattleMoveVisualRecipeId.showdownMistyTerrain,
    'junglehealing': BattleMoveVisualRecipeId.showdownGrassyTerrain,
    'followme': BattleMoveVisualRecipeId.showdownFollowMe,
    'kinesis': BattleMoveVisualRecipeId.showdownKinesis,
    'technoblast': BattleMoveVisualRecipeId.showdownFocusBlast,
    'flail': BattleMoveVisualRecipeId.showdownSlam,
    'facade': BattleMoveVisualRecipeId.showdownSlam,
    'furyattack': BattleMoveVisualRecipeId.showdownDoubleHit,
    'flamecharge': BattleMoveVisualRecipeId.showdownFlareBlitz,
    'leafstorm': BattleMoveVisualRecipeId.showdownMagicalLeaf,
    'solarbeam': BattleMoveVisualRecipeId.showdownSolarBeam,
    'thunder': BattleMoveVisualRecipeId.showdownThunder,
    'zapcannon': BattleMoveVisualRecipeId.showdownThunder,
    'sludgewave': BattleMoveVisualRecipeId.showdownSludgeBomb,
    'meteorbeam': BattleMoveVisualRecipeId.showdownSolarBeam,
    'blastburn': BattleMoveVisualRecipeId.showdownArmorCannon,
    'chloroblast': BattleMoveVisualRecipeId.showdownFleurCannon,
    'simplebeam': BattleMoveVisualRecipeId.showdownSignalBeam,
    'magnetbomb': BattleMoveVisualRecipeId.showdownSteelBeam,
    'maxstarfall': BattleMoveVisualRecipeId.showdownTerastarStorm,
    'storedpower': BattleMoveVisualRecipeId.showdownStoredPower,
    'powertrip': BattleMoveVisualRecipeId.showdownStoredPower,
    'psychoboost': BattleMoveVisualRecipeId.showdownPsychoBoost,
    'psychicnoise': BattleMoveVisualRecipeId.showdownPsychoBoost,
    'prismaticlaser': BattleMoveVisualRecipeId.showdownPsychoBoost,
    'psyshock': BattleMoveVisualRecipeId.showdownPsyshock,
    'psystrike': BattleMoveVisualRecipeId.showdownPsyshock,
    'hex': BattleMoveVisualRecipeId.showdownHex,
    'nightshade': BattleMoveVisualRecipeId.showdownHex,
    'ominouswind': BattleMoveVisualRecipeId.showdownHex,
    'blackholeeclipse': BattleMoveVisualRecipeId.showdownHex,
    'neverendingnightmare': BattleMoveVisualRecipeId.showdownHex,
    'moongeistbeam': BattleMoveVisualRecipeId.showdownHex,
    'astralbarrage': BattleMoveVisualRecipeId.showdownHex,
    'soulstealing7starstrike': BattleMoveVisualRecipeId.showdownHex,
    'willowisp': BattleMoveVisualRecipeId.showdownWillOWisp,
    'lifedew': BattleMoveVisualRecipeId.showdownLifeDew,
    'healpulse': BattleMoveVisualRecipeId.showdownLifeDew,
    'aquaring': BattleMoveVisualRecipeId.showdownLifeDew,
    'softboiled': BattleMoveVisualRecipeId.showdownLifeDew,
    'moonlight': BattleMoveVisualRecipeId.showdownLifeDew,
    'lunarblessing': BattleMoveVisualRecipeId.showdownLifeDew,
    'revivalblessing': BattleMoveVisualRecipeId.showdownLifeDew,
    'recover': BattleMoveVisualRecipeId.showdownLifeDew,
    'roost': BattleMoveVisualRecipeId.showdownLifeDew,
    'healorder': BattleMoveVisualRecipeId.showdownLifeDew,
    'aromatherapy': BattleMoveVisualRecipeId.showdownAromatherapy,
    'healbell': BattleMoveVisualRecipeId.showdownAromatherapy,
    'refresh': BattleMoveVisualRecipeId.showdownAromatherapy,
    'rest': BattleMoveVisualRecipeId.showdownRest,
    'swallow': BattleMoveVisualRecipeId.showdownRest,
    'milkdrink': BattleMoveVisualRecipeId.showdownRest,
    'ingrain': BattleMoveVisualRecipeId.showdownIngrain,
    'morningsun': BattleMoveVisualRecipeId.showdownMorningSun,
    'shoreup': BattleMoveVisualRecipeId.showdownShoreUp,
    'absorb': BattleMoveVisualRecipeId.showdownDrain,
    'megadrain': BattleMoveVisualRecipeId.showdownDrain,
    'gigadrain': BattleMoveVisualRecipeId.showdownDrain,
    'leechlife': BattleMoveVisualRecipeId.showdownLeechLife,
    'strengthsap': BattleMoveVisualRecipeId.showdownLeechLife,
    'hornleech': BattleMoveVisualRecipeId.showdownHornLeech,
    'paraboliccharge': BattleMoveVisualRecipeId.showdownParabolicCharge,
    'drainingkiss': BattleMoveVisualRecipeId.showdownDrainingKiss,
    'oblivionwing': BattleMoveVisualRecipeId.showdownOblivionWing,
    'leechseed': BattleMoveVisualRecipeId.showdownLeechSeed,
    'whirlwind': BattleMoveVisualRecipeId.showdownWhirlwind,
    'gust': BattleMoveVisualRecipeId.showdownWhirlwind,
    'silverwind': BattleMoveVisualRecipeId.showdownWhirlwind,
    'twister': BattleMoveVisualRecipeId.showdownWhirlwind,
    'freezedry': BattleMoveVisualRecipeId.showdownFreezeDry,
    'frostbreath': BattleMoveVisualRecipeId.showdownFreezeDry,
    'glaciate': BattleMoveVisualRecipeId.showdownFreezeDry,
    'magmastorm': BattleMoveVisualRecipeId.showdownMagmaStorm,
    'fierydance': BattleMoveVisualRecipeId.showdownMagmaStorm,
    'inferno': BattleMoveVisualRecipeId.showdownMagmaStorm,
    'originpulse': BattleMoveVisualRecipeId.showdownOriginPulse,
    'hydrovortex': BattleMoveVisualRecipeId.showdownOriginPulse,
    'maxgeyser': BattleMoveVisualRecipeId.showdownOriginPulse,
    'gmaxcannonade': BattleMoveVisualRecipeId.showdownOriginPulse,
    'gmaxhydrosnipe': BattleMoveVisualRecipeId.showdownOriginPulse,
    'psybeam': BattleMoveVisualRecipeId.showdownPsybeam,
    'psywave': BattleMoveVisualRecipeId.showdownPsybeam,
    'expandingforce': BattleMoveVisualRecipeId.showdownPsybeam,
    'aeroblast': BattleMoveVisualRecipeId.showdownAeroblast,
    'terablastflying': BattleMoveVisualRecipeId.showdownAeroblast,
    'roaroftime': BattleMoveVisualRecipeId.showdownRoarOfTime,
    'eternabeam': BattleMoveVisualRecipeId.showdownRoarOfTime,
    'revelationdance': BattleMoveVisualRecipeId.showdownRevelationDance,
    'pollenpuff': BattleMoveVisualRecipeId.showdownRevelationDance,
    'taunt': BattleMoveVisualRecipeId.showdownTaunt,
    'instruct': BattleMoveVisualRecipeId.showdownInstruct,
    'doubleteam': BattleMoveVisualRecipeId.showdownAgility,
    'metronome': BattleMoveVisualRecipeId.showdownSkillSwap,
    'teeterdance': BattleMoveVisualRecipeId.showdownConfuseRay,
    'encore': BattleMoveVisualRecipeId.showdownEncore,
    'gravity': BattleMoveVisualRecipeId.showdownTrickRoom,
    'topsyturvy': BattleMoveVisualRecipeId.showdownSkillSwap,
    'allyswitch': BattleMoveVisualRecipeId.showdownAgility,
    'healblock': BattleMoveVisualRecipeId.showdownGrowl,
    'flash': BattleMoveVisualRecipeId.showdownKinesis,
    'transform': BattleMoveVisualRecipeId.showdownSkillSwap,
    'bellydrum': BattleMoveVisualRecipeId.showdownBulkUp,
    'bide': BattleMoveVisualRecipeId.showdownBulkUp,
    'acupressure': BattleMoveVisualRecipeId.showdownCalmMind,
    'curse': BattleMoveVisualRecipeId.showdownBulkUp,
    'shellsmash': BattleMoveVisualRecipeId.showdownQuiverDance,
    'coil': BattleMoveVisualRecipeId.showdownBulkUp,
    'powertrick': BattleMoveVisualRecipeId.showdownSkillSwap,
    'recycle': BattleMoveVisualRecipeId.showdownCalmMind,
    'teleport': BattleMoveVisualRecipeId.showdownAgility,
    'happyhour': BattleMoveVisualRecipeId.showdownCalmMind,
    'acidarmor': BattleMoveVisualRecipeId.showdownReflect,
    'batonpass': BattleMoveVisualRecipeId.showdownAgility,
    'nastyplot': BattleMoveVisualRecipeId.showdownCalmMind,
    'takeheart': BattleMoveVisualRecipeId.showdownCalmMind,
    'trick': BattleMoveVisualRecipeId.showdownSkillSwap,
    'switcheroo': BattleMoveVisualRecipeId.showdownSkillSwap,
    'haze': BattleMoveVisualRecipeId.showdownMist,
    'assist': BattleMoveVisualRecipeId.showdownSkillSwap,
    'mirrormove': BattleMoveVisualRecipeId.showdownSkillSwap,
    'naturepower': BattleMoveVisualRecipeId.showdownSkillSwap,
    'copycat': BattleMoveVisualRecipeId.showdownSkillSwap,
    'sleeptalk': BattleMoveVisualRecipeId.showdownSkillSwap,
    'yawn': BattleMoveVisualRecipeId.showdownConfuseRay,
    'sing': BattleMoveVisualRecipeId.showdownHyperVoice,
    'perishsong': BattleMoveVisualRecipeId.showdownHyperVoice,
    'screech': BattleMoveVisualRecipeId.showdownHyperVoice,
    'snore': BattleMoveVisualRecipeId.showdownHyperVoice,
    'synchronoise': BattleMoveVisualRecipeId.showdownHyperVoice,
    'sonicboom': BattleMoveVisualRecipeId.showdownHyperVoice,
    'eerieimpulse': BattleMoveVisualRecipeId.showdownGrowl,
    'metalsound': BattleMoveVisualRecipeId.showdownGrowl,
    'supersonic': BattleMoveVisualRecipeId.showdownConfuseRay,
    'confide': BattleMoveVisualRecipeId.showdownGrowl,
    'defog': BattleMoveVisualRecipeId.showdownMist,
    'grasswhistle': BattleMoveVisualRecipeId.showdownHyperVoice,
    'boomburst': BattleMoveVisualRecipeId.showdownHyperVoice,
    'snarl': BattleMoveVisualRecipeId.showdownDarkPulse,
    'fairylock': BattleMoveVisualRecipeId.showdownMist,
    'spicyextract': BattleMoveVisualRecipeId.showdownCharm,
    'tickle': BattleMoveVisualRecipeId.showdownCharm,
    'disarmingvoice': BattleMoveVisualRecipeId.showdownHyperVoice,
    'round': BattleMoveVisualRecipeId.showdownHyperVoice,
    'splash': BattleMoveVisualRecipeId.showdownSplash,
    'celebrate': BattleMoveVisualRecipeId.showdownCelebrate,
    'holdback': BattleMoveVisualRecipeId.showdownTackle,
    'knockdown': BattleMoveVisualRecipeId.showdownBodySlam,
    'seismictoss': BattleMoveVisualRecipeId.showdownBodySlam,
    'irontail': BattleMoveVisualRecipeId.showdownIronHead,
    'pursuit': BattleMoveVisualRecipeId.showdownNightSlash,
    'dragontail': BattleMoveVisualRecipeId.showdownBodySlam,
    'reversal': BattleMoveVisualRecipeId.showdownCloseCombat,
    'punishment': BattleMoveVisualRecipeId.showdownNightSlash,
    'knockoff': BattleMoveVisualRecipeId.showdownNightSlash,
    'assurance': BattleMoveVisualRecipeId.showdownNightSlash,
    'chipaway': BattleMoveVisualRecipeId.showdownTackle,
    'bloodmoon': BattleMoveVisualRecipeId.showdownMoonBlast,
    'gigatonhammer': BattleMoveVisualRecipeId.showdownHammerArm,
    'pound': BattleMoveVisualRecipeId.showdownTackle,
    'clamp': BattleMoveVisualRecipeId.showdownCrabHammer,
    'lick': BattleMoveVisualRecipeId.showdownShadowPunch,
    'visegrip': BattleMoveVisualRecipeId.showdownCrabHammer,
    'block': BattleMoveVisualRecipeId.showdownConfuseRay,
    'guillotine': BattleMoveVisualRecipeId.showdownDrillRun,
    'return': BattleMoveVisualRecipeId.showdownTackle,
    'endeavor': BattleMoveVisualRecipeId.showdownTackle,
    'strength': BattleMoveVisualRecipeId.showdownBodySlam,
    'ragefist': BattleMoveVisualRecipeId.showdownShadowPunch,
    'fakeout': BattleMoveVisualRecipeId.showdownQuickAttack,
    'covet': BattleMoveVisualRecipeId.showdownTackle,
    'feint': BattleMoveVisualRecipeId.showdownQuickAttack,
    'thief': BattleMoveVisualRecipeId.showdownNightSlash,
    'shadowsneak': BattleMoveVisualRecipeId.showdownShadowPunch,
    'struggle': BattleMoveVisualRecipeId.showdownTackle,
    'bulldoze': BattleMoveVisualRecipeId.showdownEarthquake,
    'shadowbone': BattleMoveVisualRecipeId.showdownShadowPunch,
    'spinout': BattleMoveVisualRecipeId.showdownIronHead,
    'geargrind': BattleMoveVisualRecipeId.showdownSpikeCannon,
    'iciclespear': BattleMoveVisualRecipeId.showdownBulletSeed,
    'tailslap': BattleMoveVisualRecipeId.showdownDoubleHit,
    'furyswipes': BattleMoveVisualRecipeId.showdownDoubleHit,
    'twineedle': BattleMoveVisualRecipeId.showdownBulletSeed,
    'aquastep': BattleMoveVisualRecipeId.showdownAquaJet,
    'iceshard': BattleMoveVisualRecipeId.showdownQuickAttack,
    'ancientpower': BattleMoveVisualRecipeId.showdownPowerGem,
    'rockwrecker': BattleMoveVisualRecipeId.showdownRockSlide,
    'stoneedge': BattleMoveVisualRecipeId.showdownRockBlast,
    'hiddenpower': BattleMoveVisualRecipeId.showdownHiddenPower,
    'vacuumwave': BattleMoveVisualRecipeId.showdownAuraSphere,
    'burnup': BattleMoveVisualRecipeId.showdownFlamethrower,
    'springtidestorm': BattleMoveVisualRecipeId.showdownMoonBlast,
    'sandsearstorm': BattleMoveVisualRecipeId.showdownEarthPower,
    'leaftornado': BattleMoveVisualRecipeId.showdownMagicalLeaf,
    'roar': BattleMoveVisualRecipeId.showdownHyperVoice,
    'bounce': BattleMoveVisualRecipeId.showdownHighJumpKick,
    'dig': BattleMoveVisualRecipeId.showdownDrillRun,
    'skydrop': BattleMoveVisualRecipeId.showdownAerialAce,
    'skullbash': BattleMoveVisualRecipeId.showdownHeadbutt,
    'vcreate': BattleMoveVisualRecipeId.showdownFlareBlitz,
    'ragingfury': BattleMoveVisualRecipeId.showdownFlareBlitz,
    'zenheadbutt': BattleMoveVisualRecipeId.showdownHeadbutt,
    'firespin': BattleMoveVisualRecipeId.showdownMagmaStorm,
    'thundercage': BattleMoveVisualRecipeId.showdownChargeBeam,
    'wavecrash': BattleMoveVisualRecipeId.showdownOriginPulse,
    'freezingglare': BattleMoveVisualRecipeId.showdownFreezeDry,
    'stickyweb': BattleMoveVisualRecipeId.showdownElectroweb,
    'mysticalpower': BattleMoveVisualRecipeId.showdownPsychic,
    'barbbarrage': BattleMoveVisualRecipeId.showdownBulletSeed,
    'sandtomb': BattleMoveVisualRecipeId.showdownMagmaStorm,
    'lusterpurge': BattleMoveVisualRecipeId.showdownPsychic,
    'grassknot': BattleMoveVisualRecipeId.showdownMagicalLeaf,
    'makeitrain': BattleMoveVisualRecipeId.showdownFlashCannon,
    'brine': BattleMoveVisualRecipeId.showdownWaterPulse,
    'octazooka': BattleMoveVisualRecipeId.showdownWaterPulse,
    'waterpledge': BattleMoveVisualRecipeId.showdownBubbleBeam,
    'soak': BattleMoveVisualRecipeId.showdownWaterSport,
    'lavaplume': BattleMoveVisualRecipeId.showdownHeatWave,
    'eruption': BattleMoveVisualRecipeId.showdownFireBlast,
    'waterspout': BattleMoveVisualRecipeId.showdownOriginPulse,
    'solarblade': BattleMoveVisualRecipeId.showdownLeafBlade,
    'lightofruin': BattleMoveVisualRecipeId.showdownDazzlingGleam,
    'glaciallance': BattleMoveVisualRecipeId.showdownIceHammer,
    'freezeshock': BattleMoveVisualRecipeId.showdownBlizzard,
    'overheat': BattleMoveVisualRecipeId.showdownFireBlast,
    'sacredfire': BattleMoveVisualRecipeId.showdownFireBlast,
    'blueflare': BattleMoveVisualRecipeId.showdownFireBlast,
    'rockthrow': BattleMoveVisualRecipeId.showdownRockBlast,
    'hypnosis': BattleMoveVisualRecipeId.showdownConfuseRay,
    'darkvoid': BattleMoveVisualRecipeId.showdownConfuseRay,
    'spacialrend': BattleMoveVisualRecipeId.showdownDracoMeteor,
    'dragonascent': BattleMoveVisualRecipeId.showdownAerialAce,
    'petalblizzard': BattleMoveVisualRecipeId.showdownMagicalLeaf,
    'leafage': BattleMoveVisualRecipeId.showdownMagicalLeaf,
    'lockon': BattleMoveVisualRecipeId.showdownKinesis,
    'avalanche': BattleMoveVisualRecipeId.showdownIceHammer,
    'thousandarrows': BattleMoveVisualRecipeId.showdownEarthquake,
    'thousandwaves': BattleMoveVisualRecipeId.showdownEarthquake,
    'iciclecrash': BattleMoveVisualRecipeId.showdownIceHammer,
    'fierywrath': BattleMoveVisualRecipeId.showdownDarkPulse,
    'terrainpulse': BattleMoveVisualRecipeId.showdownWeatherBall,
    'naturesmadness': BattleMoveVisualRecipeId.showdownPainSplit,
    'ruination': BattleMoveVisualRecipeId.showdownPainSplit,
    'flowertrick': BattleMoveVisualRecipeId.showdownLeafBlade,
    'worryseed': BattleMoveVisualRecipeId.showdownMagicalLeaf,
    'tripleaxel': BattleMoveVisualRecipeId.showdownDoubleKick,
    'hyperspacehole': BattleMoveVisualRecipeId.showdownPsychic,
    'hyperspacefury': BattleMoveVisualRecipeId.showdownNightSlash,
    'bestow': BattleMoveVisualRecipeId.showdownSkillSwap,
    'finalgambit': BattleMoveVisualRecipeId.showdownPainSplit,
    'forestscurse': BattleMoveVisualRecipeId.showdownSkillSwap,
    'trickortreat': BattleMoveVisualRecipeId.showdownSkillSwap,
    'spite': BattleMoveVisualRecipeId.showdownHex,
    'spiritshackle': BattleMoveVisualRecipeId.showdownNightSlash,
    'brutalswing': BattleMoveVisualRecipeId.showdownDarkPulse,
    'firstimpression': BattleMoveVisualRecipeId.showdownQuickAttack,
    'plasmafists': BattleMoveVisualRecipeId.showdownThunderPunch,
    'collisioncourse': BattleMoveVisualRecipeId.showdownCloseCombat,
    'electrodrift': BattleMoveVisualRecipeId.showdownWildCharge,
    'sunsteelstrike': BattleMoveVisualRecipeId.showdownSmartStrike,
    'photongeyser': BattleMoveVisualRecipeId.showdownPsychic,
    'coreenforcer': BattleMoveVisualRecipeId.showdownDragonPulse,
    'stokedsparksurfer': BattleMoveVisualRecipeId.showdownThunderbolt,
    'catastropika': BattleMoveVisualRecipeId.showdownThunderbolt,
    'sinisterarrowraid': BattleMoveVisualRecipeId.showdownNightSlash,
    'oceanicoperetta': BattleMoveVisualRecipeId.showdownOriginPulse,
    'splinteredstormshards': BattleMoveVisualRecipeId.showdownRockSlide,
    'letssnuggleforever': BattleMoveVisualRecipeId.showdownPlayRough,
    'clangoroussoulblaze': BattleMoveVisualRecipeId.showdownClangingScales,
    'searingsunrazesmash': BattleMoveVisualRecipeId.showdownFlareBlitz,
    'supercellslam': BattleMoveVisualRecipeId.showdownWildCharge,
    'fishiousrend': BattleMoveVisualRecipeId.showdownAquaJet,
    'stompingtantrum': BattleMoveVisualRecipeId.showdownStomp,
    'temperflare': BattleMoveVisualRecipeId.showdownFlareBlitz,
    'thunderclap': BattleMoveVisualRecipeId.showdownSpark,
    'spiritbreak': BattleMoveVisualRecipeId.showdownPlayRough,
    'stoneaxe': BattleMoveVisualRecipeId.showdownRockBlast,
    'malignantchain': BattleMoveVisualRecipeId.showdownToxic,
    'hardpress': BattleMoveVisualRecipeId.showdownBodySlam,
    'dragoncheer': BattleMoveVisualRecipeId.showdownDragonDance,
    'upperhand': BattleMoveVisualRecipeId.showdownMachPunch,
    'blazingtorque': BattleMoveVisualRecipeId.showdownFlareBlitz,
    'combattorque': BattleMoveVisualRecipeId.showdownCloseCombat,
    'magicaltorque': BattleMoveVisualRecipeId.showdownPlayRough,
    'noxioustorque': BattleMoveVisualRecipeId.showdownGunkShot,
    'wickedtorque': BattleMoveVisualRecipeId.showdownNightSlash,
    'watershuriken': BattleMoveVisualRecipeId.showdownWaterShuriken,
    'triplearrows': BattleMoveVisualRecipeId.showdownBulletSeed,
    'judgment': BattleMoveVisualRecipeId.showdownFocusBlast,
    'gmaxsteelsurge': BattleMoveVisualRecipeId.showdownFlashCannon,
    'saltcure': BattleMoveVisualRecipeId.showdownStealthRock,
    'iceburn': BattleMoveVisualRecipeId.showdownFireBlast,
    'orderup': BattleMoveVisualRecipeId.showdownOrderUp,
    'heartstamp': BattleMoveVisualRecipeId.showdownHeartStamp,
    'matchagotcha': BattleMoveVisualRecipeId.showdownMatchaGotcha,
    'present': BattleMoveVisualRecipeId.showdownPresent,
    'payday': BattleMoveVisualRecipeId.showdownPayDay,
    'fling': BattleMoveVisualRecipeId.showdownGunkShot,
    'swift': BattleMoveVisualRecipeId.showdownMagicalLeaf,
    'guardianofalola': BattleMoveVisualRecipeId.showdownMoonBlast,
    'ragepowder': BattleMoveVisualRecipeId.showdownFollowMe,
    'spotlight': BattleMoveVisualRecipeId.showdownFollowMe,
    'wish': BattleMoveVisualRecipeId.showdownLifeDew,
    'healingwish': BattleMoveVisualRecipeId.showdownLifeDew,
    'nobleroar': BattleMoveVisualRecipeId.showdownGrowl,
    'partingshot': BattleMoveVisualRecipeId.showdownGrowl,
    'sandattack': BattleMoveVisualRecipeId.showdownKinesis,
    'smokescreen': BattleMoveVisualRecipeId.showdownKinesis,
    'swagger': BattleMoveVisualRecipeId.showdownSwagger,
    'mimic': BattleMoveVisualRecipeId.showdownSkillSwap,
    'conversion': BattleMoveVisualRecipeId.showdownCalmMind,
    'shelltrap': BattleMoveVisualRecipeId.showdownMagmaStorm,
    'outrage': BattleMoveVisualRecipeId.showdownDragonClaw,
    'bind': BattleMoveVisualRecipeId.showdownPowerWhip,
    'thrash': BattleMoveVisualRecipeId.showdownGigaImpact,
    'quash': BattleMoveVisualRecipeId.showdownQuash,
    'boneclub': BattleMoveVisualRecipeId.showdownDrillRun,
    'mindreader': BattleMoveVisualRecipeId.showdownKinesis,
    'meanlook': BattleMoveVisualRecipeId.showdownConfuseRay,
    'attract': BattleMoveVisualRecipeId.showdownCharm,
    'smellingsalts': BattleMoveVisualRecipeId.showdownBodySlam,
    'shadowforce': BattleMoveVisualRecipeId.showdownShadowClaw,
    'lovelykiss': BattleMoveVisualRecipeId.showdownDrainingKiss,
    'embargo': BattleMoveVisualRecipeId.showdownKinesis,
    'petaldance': BattleMoveVisualRecipeId.showdownMagicalLeaf,
    'pulverizingpancake': BattleMoveVisualRecipeId.showdownBodySlam,
    'precipiceblades': BattleMoveVisualRecipeId.showdownEarthquake,
    'sheercold': BattleMoveVisualRecipeId.showdownBlizzard,
    'fusionflare': BattleMoveVisualRecipeId.showdownFireBlast,
    'gigavolthavoc': BattleMoveVisualRecipeId.showdownThunderbolt,
    'alloutpummeling': BattleMoveVisualRecipeId.showdownCloseCombat,
    'infernooverdrive': BattleMoveVisualRecipeId.showdownFireBlast,
    'supersonicskystrike': BattleMoveVisualRecipeId.showdownHurricane,
    'aciddownpour': BattleMoveVisualRecipeId.showdownSludgeBomb,
    'continentalcrush': BattleMoveVisualRecipeId.showdownRockSlide,
    'corkscrewcrash': BattleMoveVisualRecipeId.showdownSmartStrike,
    'extremeevoboost': BattleMoveVisualRecipeId.showdownQuiverDance,
    'stockpile': BattleMoveVisualRecipeId.showdownBulkUp,
    'feintattack': BattleMoveVisualRecipeId.showdownNightSlash,
    'steamroller': BattleMoveVisualRecipeId.showdownStomp,
    'spectralthief': BattleMoveVisualRecipeId.showdownHex,
    'memento': BattleMoveVisualRecipeId.showdownPainSplit,
    'esperwing': BattleMoveVisualRecipeId.showdownPsyshock,
    'substitute': BattleMoveVisualRecipeId.showdownProtect,
    'withdraw': BattleMoveVisualRecipeId.showdownReflect,
    'infernalparade': BattleMoveVisualRecipeId.showdownHex,
    'dive': BattleMoveVisualRecipeId.showdownAquaJet,
    'torchsong': BattleMoveVisualRecipeId.showdownFireBlast,
    'iceball': BattleMoveVisualRecipeId.showdownFreezeDry,
    'boltstrike': BattleMoveVisualRecipeId.showdownThunderbolt,
    'electroshot': BattleMoveVisualRecipeId.showdownChargeBeam,
    'anchorshot': BattleMoveVisualRecipeId.showdownSpikeCannon,
    'diamondstorm': BattleMoveVisualRecipeId.showdownPowerGem,
    'twinkletackle': BattleMoveVisualRecipeId.showdownPlayRough,
    'headlongrush': BattleMoveVisualRecipeId.showdownEarthquake,
    'crosschop': BattleMoveVisualRecipeId.showdownKarateChop,
    'crushclaw': BattleMoveVisualRecipeId.showdownShadowClaw,
    'falseswipe': BattleMoveVisualRecipeId.showdownCut,
    'metalclaw': BattleMoveVisualRecipeId.showdownShadowClaw,
    'furycutter': BattleMoveVisualRecipeId.showdownXScissor,
    'razorshell': BattleMoveVisualRecipeId.showdownCut,
    'aquacutter': BattleMoveVisualRecipeId.showdownCut,
    'bitterblade': BattleMoveVisualRecipeId.showdownLeafBlade,
    'sacredsword': BattleMoveVisualRecipeId.showdownLeafBlade,
    'secretsword': BattleMoveVisualRecipeId.showdownPsychoCut,
    'mightycleave': BattleMoveVisualRecipeId.showdownLeafBlade,
    'tachyoncutter': BattleMoveVisualRecipeId.showdownXScissor,
  };

  static const Map<String, String> aliasByShowdownMoveId = <String, String>{
    'bubble': 'bubblebeam',
    'sparklingaria': 'bubble',
    'electrify': 'thunderwave',
    'nightdaze': 'darkpulse',
    'comeuppance': 'darkpulse',
    'retaliate': 'closecombat',
    'superpower': 'closecombat',
    'submission': 'closecombat',
    'fairywind': 'dazzlinggleam',
    'strangesteam': 'dazzlinggleam',
    'meteorassault': 'aurasphere',
    'workup': 'bulkup',
    'tidyup': 'workup',
    'coaching': 'workup',
    'filletaway': 'workup',
    'waterfall': 'aquajet',
    'surgingstrikes': 'aquajet',
    'bulletpunch': 'machpunch',
    'wringout': 'forcepalm',
    'rollingkick': 'doublekick',
    'triplekick': 'doublekick',
    'suckerpunch': 'quickattack',
    'astonish': 'quickattack',
    'rollout': 'quickattack',
    'boltbeak': 'spark',
    'wideguard': 'quickguard',
    'volttackle': 'wildcharge',
    'zingzap': 'wildcharge',
    'doubleshock': 'wildcharge',
    'terablastelectric': 'thunderbolt',
    'terablastdark': 'darkpulse',
    'terablastpsychic': 'psychic',
    'terablastfairy': 'moonblast',
    'terablastfire': 'flamethrower',
    'terablastice': 'icebeam',
    'heatcrash': 'flareblitz',
    'darkestlariat': 'flareblitz',
    'nuzzle': 'spark',
    'doubleslap': 'doublehit',
    'dualchop': 'doublehit',
    'lashout': 'nightslash',
    'ceaselessedge': 'nightslash',
    'kowtowcleave': 'nightslash',
    'jawlock': 'crunch',
    'hyperfang': 'superfang',
    'highhorsepower': 'stomp',
    'firelash': 'multiattack',
    'mysticalfire': 'flamethrower',
    'firepledge': 'flamethrower',
    'ember': 'flamethrower',
    'incinerate': 'flamethrower',
    'aurorabeam': 'icebeam',
    'appleacid': 'energyball',
    'gravapple': 'energyball',
    'poisonsting': 'poisonjab',
    'poisontail': 'poisonjab',
    'shellsidearmphysical': 'poisonjab',
    'magnitude': 'earthquake',
    'fissure': 'earthquake',
    'landswrath': 'earthquake',
    'rocktomb': 'rockslide',
    'headsmash': 'gigaimpact',
    'headcharge': 'gigaimpact',
    'takedown': 'gigaimpact',
    'dragonrush': 'gigaimpact',
    'lastresort': 'gigaimpact',
    'horndrill': 'gigaimpact',
    'trumpcard': 'gigaimpact',
    'doubleedge': 'gigaimpact',
    'breakneckblitz': 'gigaimpact',
    'ragingbull': 'gigaimpact',
    'vinewhip': 'powerwhip',
    'grassyglide': 'powerwhip',
    'trailblaze': 'powerwhip',
    'branchpoke': 'vinewhip',
    'aquatail': 'crabhammer',
    'liquidation': 'crabhammer',
    'aurawheel': 'discharge',
    'overdrive': 'discharge',
    'risingvoltage': 'discharge',
    'behemothblade': 'smartstrike',
    'behemothbash': 'smartstrike',
    'hornattack': 'megahorn',
    'lunge': 'megahorn',
    'skittersmack': 'megahorn',
    'breakingswipe': 'dragonclaw',
    'psyblade': 'psychocut',
    'chillingwater': 'waterpulse',
    'snipeshot': 'waterpulse',
    'mountaingale': 'powergem',
    'terablastrock': 'powergem',
    'burningjealousy': 'heatwave',
    'paleowave': 'muddywater',
    'scorchingsands': 'earthpower',
    'terablastground': 'earthpower',
    'terablastbug': 'bugbuzz',
    'chatter': 'hypervoice',
    'echoedvoice': 'hypervoice',
    'relicsong': 'hypervoice',
    'uproar': 'hypervoice',
    'mirrorshot': 'flashcannon',
    'mirrorcoat': 'flashcannon',
    'metalburst': 'flashcannon',
    'terablaststeel': 'flashcannon',
    'devastatingdrake': 'dragonpulse',
    'dynamaxcannon': 'dragonpulse',
    'terablastdragon': 'dragonpulse',
    'venoshock': 'sludgebomb',
    'shellsidearmspecial': 'sludgebomb',
    'terablastpoison': 'sludgebomb',
    'gastroacid': 'toxic',
    'razorleaf': 'magicalleaf',
    'grasspledge': 'magicalleaf',
    'drumbeating': 'magicalleaf',
    'snaptrap': 'magicalleaf',
    'spiderweb': 'electroweb',
    'stringshot': 'electroweb',
    'toxicthread': 'electroweb',
    'corrosivegas': 'poisongas',
    'savagespinout': 'electroweb',
    'pinmissile': 'bulletseed',
    'attackorder': 'bulletseed',
    'fellstinger': 'bulletseed',
    'strugglebug': 'bulletseed',
    'infestation': 'bulletseed',
    'beatup': 'slam',
    'counter': 'slam',
    'payback': 'slam',
    'revenge': 'slam',
    'rockclimb': 'slam',
    'sleeppowder': 'spore',
    'poisonpowder': 'spore',
    'stunspore': 'spore',
    'powder': 'spore',
    'cottonspore': 'spore',
    'magicpowder': 'spore',
    'decorate': 'spore',
    'psychoshift': 'painsplit',
    'helpinghand': 'painsplit',
    'entrainment': 'painsplit',
    'roleplay': 'painsplit',
    'psychup': 'painsplit',
    'destinybond': 'painsplit',
    'reflecttype': 'painsplit',
    'guardsplit': 'skillswap',
    'powersplit': 'skillswap',
    'guardswap': 'skillswap',
    'heartswap': 'skillswap',
    'powerswap': 'skillswap',
    'speedswap': 'skillswap',
    'courtchange': 'skillswap',
    'powershift': 'skillswap',
    'hydrocannon': 'hydropump',
    'terablastwater': 'hydropump',
    'razorwind': 'airslash',
    'terablaststellar': 'dracometeor',
    'gmaxfinale': 'maxstarfall',
    'gmaxsmite': 'maxstarfall',
    'selfdestruct': 'explosion',
    'mindblown': 'explosion',
    'mistyexplosion': 'explosion',
    'drillpeck': 'bravebird',
    'peck': 'bravebird',
    'pluck': 'bravebird',
    'bleakwindstorm': 'hurricane',
    'dragonenergy': 'dragonbreath',
    'futuresight': 'doomdesire',
    'powdersnow': 'icywind',
    'purify': 'weatherball',
    '10000000voltthunderbolt': 'triattack',
    'dragondarts': 'dragonbreath',
    'pyroball': 'flameburst',
    'scaleshot': 'clangingscales',
    'terablast': 'scald',
    'terablastgrass': 'seedflare',
    'hydrosteam': 'steameruption',
    'watergun': 'watersport',
    'extrasensory': 'psychic',
    'confusion': 'psychic',
    'shatteredpsyche': 'psychic',
    'maximumpsybreaker': 'psychic',
    'torment': 'swagger',
    'mefirst': 'mimic',
    'conversion2': 'conversion',
    'searingshot': 'shelltrap',
    'flamewheel': 'flamecharge',
    'whirlpool': 'watersport',
    'magikarpsrevenge': 'outrage',
    'constrict': 'bind',
    'wrap': 'bind',
    'lowsweep': 'lowkick',
    'wakeupslap': 'smellingsalts',
    'frustration': 'thrash',
    'rage': 'thrash',
    'frenzyplant': 'leafstorm',
    'holdhands': 'painsplit',
    'lunardance': 'moonlight',
    'crushgrip': 'quash',
    'bonerush': 'boneclub',
    'dragonrage': 'dragonbreath',
    'camouflage': 'tailglow',
    'telekinesis': 'kinesis',
    'foulplay': 'psyshock',
    'miracleeye': 'mindreader',
    'glare': 'meanlook',
    'grudge': 'meanlook',
    'scaryface': 'meanlook',
    'disable': 'meanlook',
    'captivate': 'attract',
    'flatter': 'attract',
    'armthrust': 'smellingsalts',
    'shadowstrike': 'shadowforce',
    'phantomforce': 'shadowforce',
    'nightmare': 'nightshade',
    'dreameater': 'drainingkiss',
    'sweetkiss': 'lovelykiss',
    'mudsport': 'mudbomb',
    'barrage': 'magnetbomb',
    'eggbomb': 'magnetbomb',
    'spitup': 'magnetbomb',
    'aromaticmist': 'mistyterrain',
    'sweetscent': 'mistyterrain',
    'psychicterrain': 'mistyterrain',
    'iondeluge': 'electricterrain',
    'magneticflux': 'electricterrain',
    'rototiller': 'electricterrain',
    'imprison': 'embargo',
    'synthesis': 'recover',
    'floralhealing': 'healpulse',
    'amnesia': 'rest',
    'slackoff': 'rest',
    'secretpower': 'technoblast',
    'naturalgift': 'technoblast',
    'bloomdoom': 'petaldance',
    'maliciousmoonsault': 'pulverizingpancake',
    'tectonicrage': 'precipiceblades',
    'subzeroslammer': 'sheercold',
    'genesissupernova': 'psychoboost',
    'menacingmoonrazemaelstrom': 'moongeistbeam',
    'lightthatburnsthesky': 'fusionflare',
    'maxflutterby': 'savagespinout',
    'gmaxbefuddle': 'savagespinout',
    'maxdarkness': 'maliciousmoonsault',
    'gmaxsnooze': 'maliciousmoonsault',
    'maxwyrmwind': 'devastatingdrake',
    'gmaxdepletion': 'devastatingdrake',
    'maxlightning': 'gigavolthavoc',
    'maxknuckle': 'alloutpummeling',
    'gmaxoneblow': 'alloutpummeling',
    'gmaxrapidflow': 'alloutpummeling',
    'maxflare': 'infernooverdrive',
    'gmaxcentiferno': 'infernooverdrive',
    'gmaxfireball': 'infernooverdrive',
    'maxairstream': 'supersonicskystrike',
    'maxphantasm': 'neverendingnightmare',
    'maxovergrowth': 'bloomdoom',
    'gmaxvinelash': 'bloomdoom',
    'gmaxdrumsolo': 'bloomdoom',
    'maxquake': 'tectonicrage',
    'gmaxsandblast': 'tectonicrage',
    'maxhailstorm': 'subzeroslammer',
    'gmaxresonance': 'subzeroslammer',
    'maxstrike': 'breakneckblitz',
    'gmaxcuddle': 'breakneckblitz',
    'gmaxreplenish': 'breakneckblitz',
    'maxooze': 'aciddownpour',
    'gmaxmalodor': 'aciddownpour',
    'maxmindstorm': 'shatteredpsyche',
    'gmaxgravitas': 'shatteredpsyche',
    'maxrockfall': 'continentalcrush',
    'maxsteelspike': 'corkscrewcrash',
    'stuffcheeks': 'stockpile',
    'noretreat': 'stockpile',
    'tarshot': 'mudbomb',
    'teatime': 'healbell',
    'octolock': 'bind',
    'clangoroussoul': 'extremeevoboost',
    'obstruct': 'kingsshield',
    'maxguard': 'banefulbunker',
    'falsesurrender': 'feintattack',
    'poltergeist': 'neverendingnightmare',
    'steelroller': 'steamroller',
    'eeriespell': 'psyshock',
    'bittermalice': 'spectralthief',
    'glaiverush': 'outrage',
    'lastrespects': 'memento',
    'luminacrash': 'esperwing',
    'pounce': 'bodyslam',
    'shedtail': 'substitute',
    'shelter': 'withdraw',
    'terablastfighting': 'focusblast',
    'terablastghost': 'infernalparade',
    'terablastnormal': 'technoblast',
    'tripledive': 'dive',
    'polarflare': 'torchsong',
    'mistball': 'iceball',
    'fusionbolt': 'boltstrike',
    'wildboltstorm': 'boltstrike',
    'seedbomb': 'bulletseed',
    'syrupbomb': 'sludgebomb',
  };

  static const Set<String> explicitNoAnimationShowdownIds = <String>{};

  static String? normalizeShowdownMoveId(String? value) {
    if (value == null) {
      return null;
    }
    final normalized = value.trim().toLowerCase().replaceAll(
          RegExp(r'[^a-z0-9]+'),
          '',
        );
    return normalized.isEmpty ? null : normalized;
  }
}
