// Generated by tool/import_pokemon_sdk_rmxp_animations.py.
// Sources:
// - /Users/karim/Project/pokemonProject/pokémon_sdk_test_project/Data/Animations.rxdata.yml
// - /Users/karim/Project/pokemonProject/pokémon_sdk_test_project/Data/PSP_MTAU.dat
// - /Users/karim/Project/pokemonProject/pokémon_sdk_test_project/Data/PSP_MTAT.dat
//
// Do not edit by hand. Re-run the importer when SDK data changes.

// ignore_for_file: lines_longer_than_80_chars

enum RmxpAnimationOption {
  normal,
  rotateOnReverse,
  mirrorOnReverse,
}

final class RmxpAnimationCellSpec {
  const RmxpAnimationCellSpec({
    required this.index,
    required this.pattern,
    required this.x,
    required this.y,
    required this.zoom,
    required this.angle,
    required this.mirror,
    required this.opacity,
    required this.blendType,
  });

  final int index;
  final int pattern;
  final int x;
  final int y;
  final int zoom;
  final int angle;
  final bool mirror;
  final int opacity;
  final int blendType;
}

final class RmxpAnimationFrameSpec {
  const RmxpAnimationFrameSpec({
    required this.cellMax,
    required this.cells,
  });

  final int cellMax;
  final List<RmxpAnimationCellSpec> cells;
}

final class RmxpAnimationTimingSpec {
  const RmxpAnimationTimingSpec({
    required this.frame,
    required this.condition,
    required this.flashScope,
    required this.flashDuration,
    required this.flashRed,
    required this.flashGreen,
    required this.flashBlue,
    required this.flashAlpha,
    required this.seName,
    required this.seVolume,
    required this.sePitch,
  });

  final int frame;
  final int condition;
  final int flashScope;
  final int flashDuration;
  final int flashRed;
  final int flashGreen;
  final int flashBlue;
  final int flashAlpha;
  final String? seName;
  final int seVolume;
  final int sePitch;
}

final class RmxpAnimationSpec {
  const RmxpAnimationSpec({
    required this.id,
    required this.name,
    required this.animationName,
    required this.assetId,
    required this.animationHue,
    required this.position,
    required this.frameMax,
    required this.option,
    required this.forceNoReverse,
    required this.frames,
    required this.timings,
  });

  static const double frameDurationSeconds = 0.05;

  final int id;
  final String name;
  final String animationName;
  final String assetId;
  final int animationHue;
  final int position;
  final int frameMax;
  final RmxpAnimationOption option;
  final bool forceNoReverse;
  final List<RmxpAnimationFrameSpec> frames;
  final List<RmxpAnimationTimingSpec> timings;

  double get durationSeconds => frameMax * frameDurationSeconds;
}
