/// Canonical pure-Dart authoring contracts for PokeMap.
///
/// Platform adapters and MCP protocol translation deliberately live outside
/// this package. Keeping this barrel free of those dependencies is an
/// architectural invariant tested by `package_boundary_test.dart`.
library;

export 'src/api/authoring_read_api.dart';
export 'src/api/authoring_mutation_api.dart';
export 'src/api/local_map_authoring_mutation_api.dart';
export 'src/architecture/package_boundaries.dart';
export 'src/contracts/action_descriptor.dart';
export 'src/contracts/capability_descriptor.dart';
export 'src/contracts/authoring_diff.dart';
export 'src/contracts/authoring_error.dart';
export 'src/contracts/authoring_receipt.dart';
export 'src/contracts/authoring_request.dart';
export 'src/contracts/authoring_result.dart';
export 'src/contracts/resource_ref.dart';
export 'src/contracts/schema_descriptor.dart';
export 'src/contracts/query_page.dart';
export 'src/contracts/query_request.dart';
export 'src/domains/maps/map_region_query.dart';
export 'src/domains/maps/map_lifecycle_actions.dart';
export 'src/domains/maps/map_lifecycle_adapter.dart';
export 'src/domains/maps/map_mutation_dispatcher.dart';
export 'src/domains/project/capability_truth_adapter.dart';
export 'src/history/authoring_history.dart';
export 'src/history/content_blob_store.dart';
export 'src/history/file_history_store.dart';
export 'src/history/history_store.dart';
export 'src/history/revision_revert_service.dart';
export 'src/history/undo_service.dart';
export 'src/ports/project_file_reader.dart';
export 'src/ports/idempotency_store.dart';
export 'src/ports/transaction_file_gateway.dart';
export 'src/registry/action_registry.dart';
export 'src/registry/mutation_registry.dart';
export 'src/registry/resource_kind_registry.dart';
export 'src/references/project_reference_index.dart';
export 'src/references/reference_impact.dart';
export 'src/references/reference_queries.dart';
export 'src/security/audit_log.dart';
export 'src/security/audit_record.dart';
export 'src/security/authoring_permission.dart';
export 'src/security/authorization_policy.dart';
export 'src/security/confirmation_token.dart';
export 'src/security/output_redaction.dart';
export 'src/security/secure_mutation_executor.dart';
export 'src/support/authoring_fingerprint.dart';
export 'src/tooling/cli_exit_codes.dart';
export 'src/tooling/jsonl_worker.dart';
export 'src/tooling/registry_documentation.dart';
export 'src/transactions/action_planner.dart';
export 'src/transactions/authoring_plan.dart';
export 'src/transactions/batch_executor.dart';
export 'src/transactions/change_set.dart';
export 'src/transactions/file_idempotency_store.dart';
export 'src/transactions/idempotency_ledger.dart';
export 'src/transactions/journaled_transaction.dart';
export 'src/transactions/local_transaction_file_gateway.dart';
export 'src/transactions/plan_store.dart';
export 'src/transactions/recovery_service.dart';
export 'src/transactions/revision_set.dart';
export 'src/transactions/transaction_journal.dart';
export 'src/workspace/project_open_service.dart';
export 'src/workspace/project_query_service.dart';
export 'src/workspace/project_snapshot.dart';
export 'src/workspace/project_snapshot_loader.dart';
export 'src/workspace/workspace_handle_store.dart';
export 'src/workspace/workspace_policy.dart';
