name: pokemap_hub
description: PokeMap Hub composition root and player application.
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  archive: 4.0.9
  crypto: ^3.0.7
  flame: ^1.35.0
  flutter:
    sdk: flutter
  map_core:
    path: ../../packages/map_core
  map_distribution:
    path: ../../packages/map_distribution
  map_player_ui:
    path: ../../packages/map_player_ui
  map_runtime:
    path: ../../packages/map_runtime
  path: ^1.9.0
  path_provider: ^2.1.6
  pub_semver: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  lints: ^3.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true
