import 'dart:io';

import '../lib/src/presentation/flame/battle_sdk_rmxp_animation_codec.dart';

/// BETA-BAT-014 — embarque les sons de combat référencés par le catalogue.
///
/// Le catalogue RMXP (`rmxp_animation_catalog.bin`, généré depuis le projet de
/// test PSDK) porte un `seName` par timing depuis sa création, et rien ne les
/// jouait : les fichiers audio n'avaient jamais été embarqués. Cet outil suit
/// le précédent des 181 planches : il copie depuis le même projet de test les
/// sons que le catalogue référence, plus les quatre sons système que la
/// référence nomme (hit, hitplus, hitlow pour l'efficacité, down pour le K.O.),
/// et il écrit le manifeste Dart qui fait correspondre chaque nom de timing à
/// son fichier.
///
/// La résolution imite le chargeur PSDK : nom littéral puis minuscules, avec
/// les extensions .ogg, .mp3, .wav, .flac dans cet ordre. Un son introuvable
/// est signalé et laissé absent du manifeste — le runtime joue alors
/// silencieusement, comme la référence.
///
/// Usage :
///   dart run tool/import_battle_se_assets.dart \
///     "/chemin/vers/pokémon_sdk_test_project"
void main(List<String> arguments) {
  if (arguments.length != 1) {
    stderr.writeln(
      'Usage: dart run tool/import_battle_se_assets.dart <sdk_project_root>',
    );
    exitCode = 64;
    return;
  }
  final seRoot = Directory('${arguments.first}/audio/se');
  if (!seRoot.existsSync()) {
    stderr.writeln('Missing directory: ${seRoot.path}');
    exitCode = 66;
    return;
  }

  final catalog = decodeRmxpAnimationCatalog(
    File('assets/battle_animations/rmxp_animation_catalog.bin')
        .readAsBytesSync(),
  );
  final names = <String>{
    // Les sons système de la référence : le coup selon l'efficacité, et le K.O.
    'hit',
    'hitplus',
    'hitlow',
    'down',
  };
  for (final spec in catalog.values) {
    for (final timing in spec.timings) {
      final name = timing.seName;
      if (name != null && name.isNotEmpty) names.add(name);
    }
  }

  final targetDirectory = Directory('assets/audio/battle/se')
    ..createSync(recursive: true);
  final manifest = <String, String>{};
  final missing = <String>[];
  for (final name in names.toList()..sort()) {
    final source = _resolve(seRoot, name);
    if (source == null) {
      missing.add(name);
      continue;
    }
    final fileName = source.uri.pathSegments.last.toLowerCase();
    source.copySync('${targetDirectory.path}/$fileName');
    manifest[name] = fileName;
  }

  // Les music effects de la référence consommés par la présentation :
  // PSDK les joue via `me_play` (022 SoundDesignConfig / 500 ExpDistribution),
  // PokeMap les adapte en SE par-dessus la fanfare. Nom logique → fichier ME.
  const musicEffects = <String, String>{
    'level_up': 'rosa_levelup',
  };
  // Les sons de Poké Ball de la référence (sound_design_config.json du
  // projet de test) : le lancer et l'ouverture/rappel — BETA-BAT-022.
  const ballSounds = <String, String>{
    'ball_throw': 'fall',
    'ball_open': 'pokeopen',
  };
  for (final entry in ballSounds.entries) {
    final source = _resolve(seRoot, entry.value);
    if (source == null) {
      missing.add(entry.key);
      continue;
    }
    final fileName = source.uri.pathSegments.last.toLowerCase();
    source.copySync('${targetDirectory.path}/$fileName');
    manifest[entry.key] = fileName;
  }
  final meRoot = Directory('${arguments.first}/audio/me');
  for (final entry in musicEffects.entries) {
    final source = meRoot.existsSync() ? _resolve(meRoot, entry.value) : null;
    if (source == null) {
      missing.add(entry.key);
      continue;
    }
    final fileName = source.uri.pathSegments.last.toLowerCase();
    source.copySync('${targetDirectory.path}/$fileName');
    manifest[entry.key] = fileName;
  }

  final buffer = StringBuffer()
    ..writeln('// Generated by tool/import_battle_se_assets.dart.')
    ..writeln('// Source: the PSDK test project audio/se directory; the names')
    ..writeln('// are the ones the RMXP animation catalog timings reference,')
    ..writeln('// plus the hit/hitplus/hitlow/down system sounds, plus the')
    ..writeln('// level_up music effect (audio/me) adapted as a battle SE.')
    ..writeln('// Do not edit by hand. Re-run the importer when data changes.')
    ..writeln()
    ..writeln(
        '/// Nom de timing → fichier embarqué sous assets/audio/battle/se/.')
    ..writeln('const Map<String, String> battleSeManifest = <String, String>{');
  for (final entry in manifest.entries) {
    buffer.writeln("  '${entry.key}': '${entry.value}',");
  }
  buffer.writeln('};');
  File('lib/src/presentation/flame/battle_se_manifest.dart')
      .writeAsStringSync(buffer.toString());

  stdout.writeln(
    'embedded=${manifest.length} missing=${missing.length} '
    '${missing.isEmpty ? '' : missing.join(', ')}',
  );
}

File? _resolve(Directory root, String name) {
  for (final candidate in <String>{name, name.toLowerCase()}) {
    for (final extension in const <String>[
      '',
      '.ogg',
      '.mp3',
      '.wav',
      '.flac'
    ]) {
      final file = File('${root.path}/$candidate$extension');
      if (file.existsSync()) return file;
    }
  }
  return null;
}
