name: AveluneiOS
options:
  bundleIdPrefix: com.avelune
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

schemes:
  AveluneiOS:
    build:
      targets:
        AveluneiOS: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

packages:
  FlutterNativeIntegration:
    path: flutter_runtime/build/swift-package/FlutterNativeIntegration

settings:
  base:
    SWIFT_VERSION: "5.9"
    INFOPLIST_FILE: AveluneiOS/Resources/Info.plist
    PRODUCT_BUNDLE_IDENTIFIER: com.avelune.ios
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    ENABLE_BITCODE: "NO"

targets:
  AveluneiOS:
    type: application
    platform: iOS
    sources:
      - path: AveluneiOS
    resources:
      - path: AveluneiOS/Resources
    dependencies:
      - package: FlutterNativeIntegration
    settings:
      base:
        INFOPLIST_FILE: AveluneiOS/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.avelune.ios
        DEVELOPMENT_TEAM: NLNMNV3B3S
        FRAMEWORK_SEARCH_PATHS:
          - "$(inherited)"
          - "$(PROJECT_DIR)/flutter_runtime/build/ios/framework/Release"
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/Frameworks"
