import 'dart:io';

import 'package:map_core/map_core.dart';
import 'package:map_core/src/tooling/repository_authoring_capability_collector.dart';

void main() {
  final packageRoot = Directory.current.absolute;
  final repositoryRoot = packageRoot.parent.parent;
  final inventory = RepositoryAuthoringCapabilityCollector(
    repositoryRoot: repositoryRoot,
  ).collect();
  final output = File(
    '${repositoryRoot.path}/reports/analysis/'
    'pmcp_000_authoring_capability_baseline.md',
  );

  output.parent.createSync(recursive: true);
  output.writeAsStringSync(_renderReport(inventory));
  stdout.writeln(
    'Generated ${inventory.entries.length} capability rows at '
    '${output.path}',
  );
}

String _renderReport(AuthoringCapabilityInventory inventory) {
  final byKind = <AuthoringCapabilityKind, int>{
    for (final kind in AuthoringCapabilityKind.values) kind: 0,
  };
  final byStatus = <AuthoringCapabilityStatus, int>{
    for (final status in AuthoringCapabilityStatus.values) status: 0,
  };
  for (final entry in inventory.entries) {
    byKind[entry.kind] = byKind[entry.kind]! + 1;
    byStatus[entry.status] = byStatus[entry.status]! + 1;
  }

  final buffer = StringBuffer()
    ..writeln('# PMCP-000 — Authoring capability baseline')
    ..writeln()
    ..writeln(
      '> Generated deterministically by '
      '`packages/map_core/tool/generate_authoring_capability_inventory.dart`. '
      'Do not edit this file manually.',
    )
    ..writeln()
    ..writeln('## Scope')
    ..writeln()
    ..writeln(
      'This baseline inventories model fields, editor use cases, pure core '
      'authoring operations, PokeMap Eval commands, and dotted actions from '
      'the approved Authoring API catalog.',
    )
    ..writeln()
    ..writeln(
      '`SUPPORTED` means that the row has an existing repository proof. '
      'Source code without canonical API evidence remains `MISSING`.',
    )
    ..writeln()
    ..writeln('## Counts')
    ..writeln()
    ..writeln('| Dimension | Value | Count |')
    ..writeln('|---|---|---:|');

  for (final kind in AuthoringCapabilityKind.values) {
    buffer.writeln('| Kind | `${kind.wireName}` | ${byKind[kind]} |');
  }
  for (final status in AuthoringCapabilityStatus.values) {
    buffer.writeln('| Status | `${status.wireName}` | ${byStatus[status]} |');
  }

  buffer
    ..writeln()
    ..writeln(
      inventory.toMarkdown(title: 'Capability matrix').trimRight(),
    )
    ..writeln();
  return buffer.toString();
}
