
import '../exceptions/map_exceptions.dart';
import '../models/enums.dart';
import '../models/project_manifest.dart';
import 'map_placed_element_animation.dart';
import 'tile_visual_frame_vertical_atlas.dart';

/// Explicit mapping from [TerrainPathVariant] to vertical atlas column.
///
/// This small value describes one visual variant in a vertical atlas:
/// - [variant] = the path role (e.g., isolated, horizontal, cornerNE)
/// - [column] = the x-coordinate in the atlas grid
/// - [startRow] = optional y-offset for this variant
///
/// V0 deliberately does not enforce a complete variant set. Callers can map only
/// the variants they need, in any order. This keeps the builder flexible for
/// partial atlases or custom layouts.
final class PathVariantVerticalAtlasColumn {
  const PathVariantVerticalAtlasColumn({
    required this.variant,
    required this.column,
    this.startRow = 0,
  });

  /// The path role this column represents.
  final TerrainPathVariant variant;

  /// The x-coordinate in the atlas grid.
  final int column;

  /// Optional y-offset for this variant.
  final int startRow;
}

/// Generates [PathPresetVariantMapping] from a vertical atlas layout.
///
/// This helper bridges the Lot 11 frame builder and legacy path presets:
///
/// Input:  [TerrainPathVariant -> column] mappings
/// Output: [PathPresetVariantMapping] for legacy presets
///
/// Each mapping becomes a [PathPresetVariantMapping] with:
/// - variant = input variant
/// - frames = frames generated by Lot 11 helper
///
/// The function preserves input order and validates that no variant appears twice.
///
/// V0 intentionally does not:
/// - auto-map all [TerrainPathVariant] values
/// - create [ProjectPathPreset]
/// - validate against real image dimensions
/// - load images
///
/// Those are future lots.
List<PathPresetVariantMapping> createPathVariantMappingsFromVerticalAtlas({
  required List<PathVariantVerticalAtlasColumn> columns,
  required int frameCount,
  int sourceWidth = 1,
  int sourceHeight = 1,
  String tilesetId = '',
  int defaultDurationMs = defaultPlacedElementAnimationFrameDurationMs,
  List<int?>? frameDurationsMs,
}) {
  // Validate input list
  _validateColumns(columns);

  // Validate frame parameters
  _validateFrameParameters(
    frameCount: frameCount,
    sourceWidth: sourceWidth,
    sourceHeight: sourceHeight,
    defaultDurationMs: defaultDurationMs,
    frameDurationsMs: frameDurationsMs,
  );

  final mappings = <PathPresetVariantMapping>[];

  for (final column in columns) {
    // Generate frames for this column
    final frames = createTileVisualFramesFromVerticalAtlas(
      column: column.column,
      startRow: column.startRow,
      frameCount: frameCount,
      sourceWidth: sourceWidth,
      sourceHeight: sourceHeight,
      tilesetId: tilesetId,
      defaultDurationMs: defaultDurationMs,
      frameDurationsMs: frameDurationsMs,
    );

    // Create mapping
    mappings.add(
      PathPresetVariantMapping(
        variant: column.variant,
        frames: frames,
      ),
    );
  }

  // Return unmodifiable list
  return List.unmodifiable(mappings);
}

void _validateColumns(List<PathVariantVerticalAtlasColumn> columns) {
  if (columns.isEmpty) {
    throw const ValidationException('columns must not be empty');
  }

  // Check for duplicate variants
  final seenVariants = <TerrainPathVariant>{};
  for (final column in columns) {
    if (column.column < 0) {
      throw const ValidationException('column must be non-negative');
    }
    if (column.startRow < 0) {
      throw const ValidationException('startRow must be non-negative');
    }
    if (!seenVariants.add(column.variant)) {
      throw ValidationException(
        'Duplicate TerrainPathVariant: ${column.variant}',
      );
    }
  }
}

void _validateFrameParameters({
  required int frameCount,
  required int sourceWidth,
  required int sourceHeight,
  required int defaultDurationMs,
  required List<int?>? frameDurationsMs,
}) {
  if (frameCount <= 0) {
    throw const ValidationException('frameCount must be positive');
  }
  if (sourceWidth <= 0) {
    throw const ValidationException('sourceWidth must be positive');
  }
  if (sourceHeight <= 0) {
    throw const ValidationException('sourceHeight must be positive');
  }
  if (defaultDurationMs <= 0) {
    throw const ValidationException('defaultDurationMs must be positive');
  }
  if (frameDurationsMs != null && frameDurationsMs.length != frameCount) {
    throw ValidationException(
      'frameDurationsMs length (${frameDurationsMs.length}) '
      'must equal frameCount ($frameCount)',
    );
  }
  if (frameDurationsMs != null) {
    for (var i = 0; i < frameDurationsMs.length; i += 1) {
      final duration = frameDurationsMs[i];
      if (duration != null && duration <= 0) {
        throw ValidationException(
          'frameDurationsMs[$i] must be positive (got $duration)',
        );
      }
    }
  }
}
