
import '../exceptions/map_exceptions.dart';
import '../models/enums.dart';
import '../models/project_manifest.dart';
import 'map_placed_element_animation.dart';
import 'path_variant_vertical_atlas_mapping.dart';

/// Generates a complete legacy [ProjectPathPreset] from a vertical atlas layout.
///
/// This helper bridges Lot 11/Lot 12 vertical atlas builders and legacy path presets:
///
/// Input:  [TerrainPathVariant -> column] mappings + metadata
/// Output: [ProjectPathPreset] ready for legacy runtime/editor
///
/// The preset preserves:
/// - id, name, surfaceKind, tilesetId, categoryId, sortOrder from arguments
/// - variant order exactly as provided in [columns]
/// - frame structure generated by Lot 11 via Lot 12
///
/// V0 intentionally does not:
/// - create [SurfaceDefinition] or persistent Surface models
/// - auto-map all [TerrainPathVariant] values
/// - validate against real image dimensions
/// - load images or resolve playback timing
/// - branch runtime/editor or modify JSON contracts
///
/// Those are future Surface Engine lots.
ProjectPathPreset createProjectPathPresetFromVerticalAtlas({
  required String id,
  required String name,
  required PathSurfaceKind surfaceKind,
  required String tilesetId,
  String? categoryId,
  int sortOrder = 0,
  required List<PathVariantVerticalAtlasColumn> columns,
  required int frameCount,
  int sourceWidth = 1,
  int sourceHeight = 1,
  String frameTilesetId = '',
  int defaultDurationMs = defaultPlacedElementAnimationFrameDurationMs,
  List<int?>? frameDurationsMs,
}) {
  // Validate preset-level fields
  _validatePresetParameters(
    id: id,
    name: name,
    tilesetId: tilesetId,
    columns: columns,
    frameCount: frameCount,
    sourceWidth: sourceWidth,
    sourceHeight: sourceHeight,
    defaultDurationMs: defaultDurationMs,
    frameDurationsMs: frameDurationsMs,
  );

  // Generate variant mappings using Lot 12 helper
  final variants = createPathVariantMappingsFromVerticalAtlas(
    columns: columns,
    frameCount: frameCount,
    sourceWidth: sourceWidth,
    sourceHeight: sourceHeight,
    tilesetId: frameTilesetId,
    defaultDurationMs: defaultDurationMs,
    frameDurationsMs: frameDurationsMs,
  );

  // Build the legacy preset
  return ProjectPathPreset(
    id: id,
    name: name,
    surfaceKind: surfaceKind,
    tilesetId: tilesetId,
    categoryId: categoryId,
    sortOrder: sortOrder,
    variants: variants,
  );
}

void _validatePresetParameters({
  required String id,
  required String name,
  required String tilesetId,
  required List<PathVariantVerticalAtlasColumn> columns,
  required int frameCount,
  required int sourceWidth,
  required int sourceHeight,
  required int defaultDurationMs,
  required List<int?>? frameDurationsMs,
}) {
  // Preset-level validations
  if (id.trim().isEmpty) {
    throw const ValidationException('id must not be empty');
  }
  if (name.trim().isEmpty) {
    throw const ValidationException('name must not be empty');
  }
  if (tilesetId.trim().isEmpty) {
    throw const ValidationException('tilesetId must not be empty');
  }

  // Delegate column and frame validations to Lot 12 helper
  // This keeps validation logic centralized and consistent
  _validateColumns(columns);
  _validateFrameParameters(
    frameCount: frameCount,
    sourceWidth: sourceWidth,
    sourceHeight: sourceHeight,
    defaultDurationMs: defaultDurationMs,
    frameDurationsMs: frameDurationsMs,
  );
}

// Re-export Lot 12 validation helpers for consistency
void _validateColumns(List<PathVariantVerticalAtlasColumn> columns) {
  if (columns.isEmpty) {
    throw const ValidationException('columns must not be empty');
  }

  final seenVariants = <TerrainPathVariant>{};
  for (final column in columns) {
    if (column.column < 0) {
      throw const ValidationException('column must be non-negative');
    }
    if (column.startRow < 0) {
      throw const ValidationException('startRow must be non-negative');
    }
    if (!seenVariants.add(column.variant)) {
      throw ValidationException(
        'Duplicate TerrainPathVariant: ${column.variant}',
      );
    }
  }
}

void _validateFrameParameters({
  required int frameCount,
  required int sourceWidth,
  required int sourceHeight,
  required int defaultDurationMs,
  required List<int?>? frameDurationsMs,
}) {
  if (frameCount <= 0) {
    throw const ValidationException('frameCount must be positive');
  }
  if (sourceWidth <= 0) {
    throw const ValidationException('sourceWidth must be positive');
  }
  if (sourceHeight <= 0) {
    throw const ValidationException('sourceHeight must be positive');
  }
  if (defaultDurationMs <= 0) {
    throw const ValidationException('defaultDurationMs must be positive');
  }
  if (frameDurationsMs != null && frameDurationsMs.length != frameCount) {
    throw ValidationException(
      'frameDurationsMs length (${frameDurationsMs.length}) '
      'must equal frameCount ($frameCount)',
    );
  }
  if (frameDurationsMs != null) {
    for (var i = 0; i < frameDurationsMs.length; i += 1) {
      final duration = frameDurationsMs[i];
      if (duration != null && duration <= 0) {
        throw ValidationException(
          'frameDurationsMs[$i] must be positive (got $duration)',
        );
      }
    }
  }
}
